PlasmaPy/PlasmaPy

.gitignore
README.rst
docs/README.rst
licenses/README.md
licenses/README.rst
plasmapy/__init__.py
setup.py

* Added setup.py
* Added folders for documentation and licenses.
* Added .gitignore file 
* Including a test function in plasmapy called write_science_fiction_musical
* Creating directories with readme files for utilities, visualization, input/output, analytic_functions, and constants

Adding minimal infrastructure and starting directory tree

---

README.md
licenses/README.md

* Changed README.md to README.rst in various folders
* Changed package directory to "plasmapy" (instead of "PlasmaPy" with capitalization)

Removing old versions of files

---

plasmapy/__init__.py
plasmapy/analytic_functions/__init__.py
plasmapy/analytic_functions/dispersion.py
plasmapy/analytic_functions/tests/__init__.py
plasmapy/analytic_functions/tests/test_dispersion.py

My major changes are:
- Creating `plasma_dispersion_func` and `plasma_dispersion_func_deriv` in analytic_functions, with detailed docstrings and tests
- Created `tests` subdirectories in folders with empty __init__.py files for organization
- Added a warning to top-level __init__.py that says that PlasmaPy does not guarantee support for Python versions older than 3.6
Any suggestions are appreciated!

Plasma dispersion function added to analytic_functions

---

CONTRIBUTE.md

More discussion on this happened here: https://github.com/PlasmaPy/PlasmaPy/pull/20

Creating CONTRIBUTE.md as a guide to contributing to PlasmaPy (second try)

---

.coveragerc
.travis.yml
README.md
plasmapy/travis-testing.txt
requirements/base.txt

Work in progress, please don't merge yet.
I'm learning a lot about Travis at Python in Astronomy, so I may be adding features to our setup over the next few days.

More travis [WIP]

---

.gitignore

That one was easy to solve ;)
I've followed the CONTRIBUTE help, it seems clear enough to me, but I'm not totally new to github as well.

Solving issue #57

---

README.md

Can we all just agree that this is lovely enough to include?

Inherit yt's Impostor Syndrome Disclaimer

---

plasmapy/physics/parameters.py

Added further physical notes and mathematical explanation to the electron_plasma_frequency(n_e) function.
This is my first foray into this world, so feedback is very warmly welcome.

Added further physical notes to electron_plasma_frequency(n_e)

---

.coveragerc
plasmapy/__init__.py

As per the discussion on #58 , here is a new coveralls directive that we can use to discount things in the tests.

New coveralls directive

---

CONTRIBUTE.md

Specifying that you can delete a branch after the pull request
associated with that branch has been merged.

Add sentence to code contribution guide

---

plasmapy/atomic/atomic.py
plasmapy/atomic/tests/test_atomic.py

As @namurphy requested I added a function that returns the actual charge as a `Quantity` along with some basic test cases.

Added electric_charge function and test cases

---

.github/PULL_REQUEST_TEMPLATE.md

A relatively minor change that only affects the Pull Request process.

Add note about referring to issue in Pull Request template

---

README.md

Update README to mention pip and anaconda

---

.gitignore
plasmapy/classes/species.py

I add some issue during the developpement of some feature.
I think that this is better.

Removed auto-referencement in importation

---

.coveragerc
.gitignore
.gitmodules
.travis.yml
MANIFEST.in
ah_bootstrap.py
ez_setup.py
plasmapy/__init__.py
plasmapy/_metadata.py
pytest.ini
setup.cfg
setup.py

This pull request adds astropy_helpers as a submodule to PlasmaPy.  Additionally, development version numbers are now appended by the commit number.

Include astropy_helpers as a submodule

---

docs/development/code_guide.rst
docs/development/coding_guidelines.rst
docs/development/doc_guide.rst
docs/development/release_guide.rst
docs/index.rst

This pull request includes a first draft of coding guidelines for developers, and brief documentation guidelines as well.  This is meant to start this part of the documentation rather than complete it.  Hence there will be more work to do later.  Please feel free to make any suggestions on how to improve these docs.
The resolution of https://github.com/PlasmaPy/PlasmaPy/issues/131 should be added to the coding guide as well.  Closes #111.

Begin narrative code development guide

---

plasmapy/__init__.py
plasmapy/atomic/atomic.py
plasmapy/atomic/nuclear.py
plasmapy/classes/species.py
plasmapy/classes/tests/test_Plasma.py
plasmapy/classes/tests/test_Species.py
plasmapy/math/math.py
plasmapy/math/tests/test_dispersion.py
plasmapy/physics/tests/test_distribution.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/tests/test_relativity.py
plasmapy/utils/checks.py

Fixes #146,
Hi I've made a python script for this which I can share with you on gist. Its not a super efficient script, as I haven't used RegEx as I am not that proficient in it.
Please let me know if any changes are required.
Thanks

Fix #146 - Convert doc string to raw string

---

CONTRIBUTING.md

Added directions on how to setup virtualenv, install plasmapy dependencies, and setup plasmapy development files within virtualenv. Some of this is Linux specific.
This addresses issue #151

Added info on virtualenv and setup.py in CONTRIBUTING.MD

---

plasmapy/physics/parameters.py

For some reason plasma_frequency mentioned an error with gyrofrequency.

Small correction in parameters.py

---

plasmapy/physics/__init__.py
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/tests/test_distribution.py
plasmapy/physics/tests/test_parameters.py

Adding 1D and 3D kappa velocity distribution functions.
Addresses #101 
There are still some issues with the 1D distribution in particular not integrating to 1. Need to figure out the correct normalization constant for that function. The other 1D tests are failing because I haven't added the expected values yet. I don't want to do this until we figure out the correct normalization constant as the expected values will change.
There is another issue that for large values of kappa both the 1D and 3D functions return NaNs. This makes it difficult to test if the kappa distribution converges to a Maxwellian as kappa approaches infinity.
Help on these would be appreciated!

Kappa function

---

ROADMAP.md

Updated the roadmap following [the telecon on 2017-12-12](https://docs.google.com/document/d/1pJhLxeNJAdHeu4RFjOGHO2ksunmjHKZ2bxBIZZuYiGA/edit?usp=sharing).

Update roadmap for 0.1

---

README.md

Added Gitter and Matrix badges to README

---

plasmapy/physics/parameters.py
plasmapy/physics/tests/test_parameters.py

This PR should close issue #206

Added a `signed` option in gyrofrequency

---

docs/index.rst
docs/species/index.rst
plasmapy/classes/species.py

Going to put in a few PRs to update the docs this morning. This one adds the "Species" class to the documentation.

Add species docs

---

.gitignore
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/transport.py

A bunch of cleaning on the physics docstrings. Mainly adding full stops... (but a few math fixes too!)

Clean physics docstrings

---

docs/index.rst
docs/utils/index.rst
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/transport.py
plasmapy/utils/__init__.py
plasmapy/utils/checks.py
plasmapy/utils/exceptions.py

I think this finishes off adding everything to the docs!

Add util docs

---

plasmapy/physics/distribution.py

Trying to get that RTD badge green.

Fix sphinx build bugs

---

.circleci/config.yml

Print out doc URL from CircleCI

---

plasmapy/utils/checks.py

Just needed an extra line before the 2nd example to parse it as code. Hopefully with the shiny new CircleCi doc viewing you should be able to see this change in all it's glory!

Fix example in betafrac doc

---

LICENSE.md
plasmapy/examples/plot_cold_plasma_tensor_elements.py
plasmapy/physics/__init__.py
plasmapy/physics/dielectric.py
plasmapy/physics/tests/test_dielectric.py

Added functions to calculate Magnetized Cold Plasma tensor elements (aka "Stix" tensor), which is useful for waves in plasma physics. Also added an example which plot a graph for a wide range of frequencies.

Magnetized Cold Plasma tensor elements functions

---

plasmapy/atomic/atomic.py
plasmapy/atomic/nuclear.py
plasmapy/mathematics/mathematics.py
plasmapy/physics/dielectric.py
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/utils/checks.py

Closes #229 .
A day may come where I come to enjoy the bugfixes and printing conventions of numpy 1.14.
But it is not this day.

All docstrings are fixed.

---

docs/conf.py

Very minor addition to the `conf.py` for the docs. I have it on good authority from @Cadair that it does a useful thing.

Doc config tweak

---

plasmapy/atomic/__init__.py
plasmapy/mathematics/__init__.py
plasmapy/physics/__init__.py
plasmapy/utils/__init__.py

Closes #227 
Doctests are failing for me because I am using Conda env which won't let me install the newest numpy due to dependency issues.

Fix init py

---

.circleci/config.yml
docs/conf.py
docs/physics/index.rst
plasmapy/__init__.py
plasmapy/examples/plot_braginskii.py
plasmapy/physics/__init__.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/tests/test_transport.py
plasmapy/physics/transport.py

Working on Issue #35 . I've put in some functionality and done some preliminary checks and tests. Definitely still a work in progress, needs tests and documentation and then is going to need some ruthless refactoring. Oh shoot, and the PEP8 checking-thing is going to have a fit.

Braginskii

---

plasmapy/atomic/__init__.py
plasmapy/atomic/atomic.py
plasmapy/atomic/names.py
plasmapy/atomic/nuclear.py
plasmapy/atomic/tests/test_atomic.py
plasmapy/classes/species.py
plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/tests/test_langmuir.py
plasmapy/mathematics/mathematics.py
plasmapy/physics/__init__.py
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/tests/test_dielectric.py
plasmapy/physics/tests/test_distribution.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/tests/test_transport.py
plasmapy/physics/transport.py
plasmapy/utils/checks.py

This pull request goes throughout the code and replaces `charge_state` with `integer_charge`, and makes a few other minor/formatting changes.  Closes #236.

Rename charge_state to _integer_charge

---

docs/development/code_guide.rst
plasmapy/__init__.py
plasmapy/atomic/atomic.py
plasmapy/atomic/classes.py
plasmapy/atomic/nuclear.py
plasmapy/mathematics/tests/test_dispersion.py
plasmapy/physics/dielectric.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/transport.py

Standardize import alias for astropy.units as u

---

appveyor.yml
docs/development/testing_guide.rst

Hello, I hear you want to run tests on windows! Here is a first attempt at that using Appveyor. I'm guessing someone with organisation access will need to enable the build on https://ci.appveyor.com - once that's done and this PR is building I'm happy to play around with it until it works.
Fixes #246

First attempt at an appveyor file

---

ah_bootstrap.py

I decided to give up on #270, so here's another (presumably cleaner) pull request to update astropy-helpers to v3.0.  Tests are still failing, but this may be related to something upstream.

Update astropy-helpers to v3.0, try 2

---

plasmapy/atomic/particle_class.py
plasmapy/atomic/tests/test_particle_class.py

A few minor improvements to `particle_class.py` as discussed today during the code review session.

Particle class code review fixes

---

docs/plasma/index.rst
plasmapy/__init__.py
plasmapy/classes/__init__.py
plasmapy/classes/plasma.py
plasmapy/classes/tests/__init__.py
plasmapy/classes/tests/test_Plasma.py
plasmapy/classes/tests/test_Species.py
plasmapy/physics/dimensionless.py

Addresses #156 
Here is a prototype PlasmaBlob class implementing one way of handling regime assessment.
This is still a work in progress, but I'd like feedback on whether people think this is a good way of approaching this issue.

Plasma blob

---

plasmapy/physics/distribution.py

There's a few things that needed cleaning; I haven't looked at the Kappa stuff at all.

Clean distribution docstrings

---

plasmapy/examples/plot_distribution.py

This gives a bit of a clean to the example.

Clean up 1D maxwellian example

---

plasmapy/physics/dimensionless.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/tests/test_dimensionless.py
plasmapy/physics/tests/test_parameters.py

Add plasma beta method

---

plasmapy/physics/distribution.py

Avoids quite a bit of code repetition in distributions.py

Use helper method to fix up drift units

---

plasmapy/physics/dielectric.py

Correcting a single import statement which was failing.

Corrected an import statement

---

docs/development/code_guide.rst

[WIP] Code guide improvements

---

docs/development/code_guide.rst

I mixed up pull requests and merged the wrong one yesterday. Here's a follow up for the one I intended to finish.

Finish cython documentation for now

---

.circleci/config.yml
.travis.yml
appveyor.yml
requirements/automated-documentation-tests.txt
requirements/environment.txt
requirements/environment.yml

Python 3.7 tests

---

MANIFEST.in

Include LICENSE.md in MANIFEST.in

---

.github/PULL_REQUEST_TEMPLATE.md

Up until now, our PR template made the suggestion to add `Closes #404.`  I updated this template with several more points that new contributors would likely find to be helpful.

Update pull request template on GitHub

---

plasmapy/atomic/nuclear.py

Change relative to absolute imports

---

docs/development/code_guide.rst
plasmapy/atomic/atomic.py
plasmapy/atomic/nuclear.py
plasmapy/atomic/symbols.py
plasmapy/physics/parameters.py

Add Optional type hint for arguments with a default value of None

---

plasmapy/atomic/atomic.py

Edited lines using relative imports to absolute standard

Change relative to absolute imports in PlasmaPy

---

docs/atomic/nuclear.rst
docs/development/testing_guide.rst

As discussed on Riot: https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$154031375461886xDfIo:matrix.org

Follow up fixes to RST documentation errors

---

plasmapy/transport/collisions.py

Fix #584 broken link to Coulomb Logarithm in doc

---

README.md

Self explanatory. Picked up the idea from [CuPy](https://github.com/cupy/cupy/blob/master/README.md).

Make README more beautiful by adding logo

---

plasmapy/__init__.py
plasmapy/data/__init__.py

Closes #610 and closes #575. This is how `help(plasmapy)` now looks like:
```rst
Help on package plasmapy:
NAME
plasmapy
DESCRIPTION
PlasmaPy: A plasma physics Python package
================================================
Documentation is available in the docstrings,
online at https://docs.plasmapy.org (accessible also using
the ``plasmapy.online_help`` function).
Contents
--------
PlasmaPy provides the following functionality:
Subpackages
-----------
Each of these subpackages requires an explicit import, for example,
via ``import plasmapy.physics``.
::
atomic                            --- Database for atoms, isotopes, ions...
classes                           --- (WIP) classes used in multiple places
constants                         --- (WIP?) wrapper for astropy.constants.si
data …
```

Improve package init, drop unused packages

---

plasmapy/transport/collisions.py

I started doing a little bit of tinkering with this to hopefully close #348. Just putting this in here for now so the tests show up.

Verify custom velocities not being passed in

---

README.md

As suggested by Erik at the telecon :)

Add link to meeting calendar

---

plasmapy/physics/drifts.py
plasmapy/physics/tests/test_drifts.py

I'm making another attempt at getting through Bellan's fundamentals of plasma physics again and I figured I'd add a couple of the better known particle drifts.
This includes changes from #481 as I started this on top of those changes, so it should not be merged before that one.
I'm still figuring out a good way to include the grad B drift... perhaps that should simply be another argument.

[WIP] Particle drifts

---

plasmapy/diagnostics/langmuir.py
plasmapy/examples/plot_langmuir_analysis.py

Closes #456 by refactoring the example and Langmuir analysis functionality a bit. Though, with [langmuir](https://github.com/langmuirproject/langmuir) now out there in the ecosystem, we'll have to look at that a little bit more closely and possibly wrap it...

Langmuir example improvement

---

docs/conf.py

Add binder links to gallery notebooks

---

changelog/655.doc.rst
docs/about/credits.rst
docs/index.rst
plasmapy/examples/plot_dispersion_function.py

Added some images from the examples section to the main page for issue #630
Thank you for contributing to PlasmaPy!  Please check out our development guide at:
http://docs.plasmapy.org/en/master/development/index.html
Here are a few things to keep in mind when making a pull request (PR).
* Tests and docstrings are required for new or changed functionality.
* Please take care to write helpful commit messages: https://chris.beams.io/posts/git-commit/
* As a PR nears completion, fellow developers will likely suggest changes
to be made before the PR is merged.
* Every pull request should include a changelog entry. Please see
`changelog/README.rst` for instructions.
* PlasmaPy follows the PEP 8 style guide: https://www.python.org/dev/peps/pep-0008
* Please double check that a new PR will not …

Closes #630 - Added Examples to Main page of Docs 

---

changelog/658.trivial.rst
docs/conf.py
tox.ini

Sphinx patch

---

.travis.yml
azure-pipelines.yml
plasmapy/atomic/tests/test_ionization_states.py
plasmapy/classes/sources/openpmd_hdf5.py
plasmapy/classes/sources/tests/test_openpmd_hdf5.py
plasmapy/classes/tests/test_plasma_factory.py
tox.ini

Reenable parallel testing

---

README.md

Thank you for contributing to PlasmaPy!  Please check out our development guide at:
http://docs.plasmapy.org/en/master/development/index.html
Here are a few things to keep in mind when making a pull request (PR).
* Tests and docstrings are required for new or changed functionality.
* Please take care to write helpful commit messages: https://chris.beams.io/posts/git-commit/
* As a PR nears completion, fellow developers will likely suggest changes
to be made before the PR is merged.
* Every pull request should include a changelog entry. Please see
`changelog/README.rst` for instructions.
* PlasmaPy follows the PEP 8 style guide: https://www.python.org/dev/peps/pep-0008
* Please double check that a new PR will not duplicate an existing PR.
* If this PR will solve an issue tracked by GitHub, …

Format Changes in Readme.md

---

changelog/716.trivial.rst
plasmapy/atomic/atomic.py
plasmapy/atomic/elements.py
plasmapy/atomic/isotopes.py
plasmapy/atomic/nuclear.py
plasmapy/atomic/parsing.py
plasmapy/atomic/particle_class.py
plasmapy/atomic/symbols.py
plasmapy/atomic/tests/test_ionization_state.py
plasmapy/atomic/tests/test_ionization_states.py
plasmapy/atomic/tests/test_parsing.py
plasmapy/atomic/tests/test_particle_class.py

This PR doesn't solve bugs, but improves the actual style guide of python3 in some modules using pylint3 as a standard score.
Great project!

Style improvements

---

pyproject.toml

This implements settings from https://github.com/Cadair/baldrick/blob/checks_towncrier/doc/plugins.rst

Fix Gilesbot settings

---

changelog/743.feature.rst
docs/about/credits.rst
plasmapy/formulary/magnetostatics.py
plasmapy/formulary/tests/test_magnetostatics.py

"Closes #740." 
Now there are units in reprs of magnetostatics classes. I also added `__repr__` to `GeneralWire`.
All the units are now attributes of corresponding objects.

Units in magnetostatics reps

---

.pre-commit-config.yaml
changelog/770.trivial.rst
docs/development/code_guide.rst
setup.cfg

- There are no new tests for this, but a doc update would be good to do.

Add pre-commit configuration

---

LICENSE.md
README.md
changelog/784.trivial.rst
docs/COMMUNICATION.rst
docs/about/credits.rst

Things I did:
- Update community meeting link to original Jitsi link
- Update community meeting time
- Update funding acknowledgments
- Alphabetize contributors
- Make minor formatting changes

Update community meeting link & time, add funding, and make minor updates to docs

---

changelog/805.feature.rst
plasmapy/formulary/relativity.py
plasmapy/formulary/tests/test_relativity.py

Add `relativistic_energy` to the Formulary

---

changelog/825.doc.rst
docs/about/credits.rst
docs/notebooks/braginskii.ipynb
docs/notebooks/cold_plasma_tensor_elements.ipynb
docs/notebooks/dispersion_function.ipynb
docs/notebooks/distribution.ipynb
docs/notebooks/langmuir_analysis.ipynb
docs/notebooks/magnetic_statics.ipynb
docs/notebooks/particle_stepper.ipynb
docs/notebooks/physics.ipynb

Closes #814 
> ![Screenshot from 2020-06-02 15-06-02](https://user-images.githubusercontent.com/39518771/83505159-095f6680-a4e3-11ea-9284-0119082228dc.png)
> Local doc build success with `tox -e build_docs`

Linking API docs from ipynb examples resolved

---

.github/workflows/flake8.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
changelog/845.trivial.rst

Uses template as per https://github.com/pre-commit/action
Closes #839
docstrings.

Add pre-commit github action

---

changelog/872.doc.rst
docs/development/release_guide.rst
docs/index.rst

Updates for release guide

---

changelog/886.bugfix.rst
docs/notebooks/thomson.ipynb
plasmapy/utils/decorators/tests/test_validators.py
plasmapy/utils/decorators/validators.py
plasmapy/utils/exceptions.py

Closes #885. Work in progress.

Allow eV inputs for temperature without conversion warnings

---

README.md
changelog/891.doc.rst
docs/COMMUNICATION.rst
docs/CONTRIBUTING.rst
plasmapy/particles/elements.py
plasmapy/particles/isotopes.py

Closes #890. Self-quoting from that:
> * Matrix is the chat platform we were and still are using;
> * Riot is the old name of the particular chat client we're using;
> * Element is the new name for that chat client.
> 
> > nowadays there are lots of other Matrix clients, vendors and hosting providers that demonstrate perfectly the diversity of the Matrix ecosystem.
> 
> (from the linked page)
> 
> So I'm going to standardize this to Matrix in most cases, but link to Element. I guess we could link to https://matrix.to/#/#plasmapy:openastronomy.org (I found the site by looking at what provides the ![Matrix](https://matrix.to/img/matrix-badge.svg) badge), but since Matrix is a bit niche as is, having the chat another step away and making people decide which chat client to use seems …

Replace instances of Riot with Matrix/Element

---

README.md
docs/COMMUNICATION.rst

Fixing the time of the community meeting after the change from DST to Standard time.

Update meeting time after time change

---

.github/workflows/linters.yml
.github/workflows/testing.yml
tox.ini

docstrings.
I started reading Astropy's github-actions config and picked up a ton of useful stuff. For example:
* I did some light refactoring of tox.ini and the configs.
* I split up tox envs between different github runners. I thus removed my previous idea of using tox-gh-actions, which I was dissatisfied with.
* Most importantly, the errors now pop up right away when looking at tests, making test output cleaner. and easier to understand.
Follow up to #952.

Pick up astropy's GitHub Actions config

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
README.md
codemeta.json
docs/COMMUNICATION.rst

Replace mentions of Discourse with Github Discussions

---

LICENSE.md

I have been waiting to submit this pull request for MONTHS. :tada: :fire_extinguisher: :volcano: :crystal_ball: :hankey: :comet: :clock12: 🍾 🚮 🪠 📢 🆘 🎊 🎙

Update copyright year to 2021

---

changelog/966.feature.rst
plasmapy/formulary/drifts.py
plasmapy/formulary/tests/test_drifts.py

Addresses issue #966. User inputs the pressure gradient, background field, density, and charge. I included descriptions and examples in the docstring. Also tests (similar to ExB and force drift) were made, with an addition of the case in Fig. 3.4 of Chen. I assumed the density scale n'/n were 1 / m and verified the magnitude of the drift.

Added diamagnetic drift 

---

.github/workflows/testing.yml
Dockerfile.documentation
README.md
changelog/987.breaking.rst
codemeta.json
docs/conf.py
docs/development/code_guide.rst
docs/index.rst
docs/install.rst
plasmapy/__init__.py
setup.cfg
tox.ini

Drop python 3.6

---

README.md

This is a quick follow-up to something I neglected to finish in #977.

Remove lingering git hashes in README.md

---

changelog/999.feature.rst
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/tests/test_checks.py
plasmapy/utils/decorators/tests/test_validators.py
plasmapy/utils/decorators/validators.py

Add can_be_zero option to CheckValues

---

docs/development/code_guide.rst
docs/development/doc_guide.rst
docs/development/release_guide.rst

A few parts of our development guide have become obsolete, so the purpose of this pull request is to provide some updates for those relevant parts.  There are a few broader things I'd like to do to revamp different parts of our development guide, but I think that would be best done incrementally over a few pull requests.

Update development guide

---

docs/development/code_guide.rst
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_ionization_collection.py

...when I try to use PyCharm's interface instead of the command line like I'm used to...

Revert changes accidentally committed to master

---

plasmapy/particles/tests/test_ionization_state.py

Test for nested iterator

---

changelog/1050.trivial.rst
plasmapy/diagnostics/proton_radiography.py
plasmapy/diagnostics/tests/test_proton_radiography.py

Addresses issue #844 for `proton_radiography.py`

Catch warnings in test_proton_radiography.py

---

docs/index.rst

add proton radiography introduction notebook to front page of docs

---

changelog/1081.doc.rst
docs/development/release_guide.rst

Here's a first attempt at including a feature freeze and code freeze in our release guide, which we can iterate upon.  Closes #1078.

Add feature freeze and code freeze to timeline

---

changelog/1088.trivial.rst
docs/notebooks/ExB_drift.ipynb

Started getting a CI error related to the thumbnail in this notebook. Trying to fix it in this PR just by splitting up some cells.
The error:
```
/home/runner/work/PlasmaPy/PlasmaPy/docs/notebooks/ExB_drift.ipynb:"nbsphinx-thumbnail": Unsupported output type in cell 11/output 0: "stream"
ERROR: InvocationError for command /home/runner/work/PlasmaPy/PlasmaPy/.tox/build_docs/bin/sphinx-build docs docs/_build/html -W -b html (exited with code 2)
```
Relevant documentation: https://nbsphinx.readthedocs.io/en/latest/code-cells.html#Plots

Trying to fix very minor error in ExB_drift.ipynb

---

README.md

A followup to #1106. The line ends in a space, which should be caught. I think.
docstrings.

Add badge to see whether pre-commit.ci works nicely

---

changelog/1116.trivial.rst
docs/about/credits.rst
plasmapy/analysis/fit_functions.py
plasmapy/analysis/swept_langmuir/helpers.py
plasmapy/analysis/tests/test_fit_functions.py
plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/tests/test_langmuir.py
plasmapy/dispersion/two_fluid_dispersion.py
plasmapy/formulary/__init__.py
plasmapy/particles/atomic.py
plasmapy/particles/decorators.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_class.py
plasmapy/particles/particle_collections.py
plasmapy/particles/serialization.py
plasmapy/particles/tests/test_decorators.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/plasma/grids.py
plasmapy/plasma/tests/test_grids.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/validators.py
plasmapy/utils/pytest_helpers/pytest_helpers.py
setup.cfg

Removed majority of the flake8 checks listed in #1116 under # TODO. Also edited the corresponding files that were throwing the flake8 checks once they were no longer being ignored. The only error code that was not handled completely was F541, only some of the F541 errors were handled, but not all. The remaining errors for F541 is for strings that begin with fr"string". Was a bit confused on if this was an intentional design so I wanted clarification before I handled them. I wanted feedback on if this seems good since this is my first contribution to Open Source and feel a bit anxious on if I was working on it incorrectly on my end.
docstrings.

Enable flake8 checks

---

docs/about/credits.rst
requirements/environment.yml

Added notebook to be installed by pip so jupyter notebook is there to be launched to run example cases with extensions ipynb without further steps.
docstrings.

Added notebook to environment.yml

---

docs/about/credits.rst
docs/development/code_guide.rst
requirements/environment.yml

Small edit to make it easier to find the clear all output option. For version 6.4.0 jupyter notebook (currently the newest version) it is located in Cell dropdown options.
docstrings.

Minor edit code development guidelines

---

changelog/1178.doc.rst
docs/development/index.rst
docs/development/workflow.rst

This pull request is to create the outline of a page in our code development guide that describes the development workflow that we use when contributing to PlasmaPy
docstrings.

Start a documentation page for workflow documentation

---

changelog/1180.doc.rst
docs/about/credits.rst
plasmapy/formulary/parameters.py

Triggered by the hack-week, I just added a little bit of physics information about the upper-hybrid resonance (my research are is basically plasma-microwave interaction). Let me know all the details that I missed :)
Just realized that I need to
- add something to the changelog
- add my name to the author list
docstrings.

Add physics info the upper-hybrid resonance docstring

---

changelog/1181.doc.rst
plasmapy/formulary/parameters.py

Triggered by the hack-week, I added a little bit of physics information about the lower-hybrid resonance.
Together with #1180, this should close #1172 
docstrings.

Add some physics into about lower-hybrid frequency

---

changelog/1218.doc.rst
plasmapy/formulary/parameters.py

Typo in Alfven_speed Docstring

---

.github/workflows/testing.yml
.github/workflows/weekly.yml
tox.ini

This is my attempt to set up cron jobs for running with numpy-dev, xarray-dev, and astropy-dev.  This also closes #1162, since I'm adding a test of sphinx-dev too.
This might be a PR that would need to get merged before we figure out if it works or not.  I'm attempting to use the `workflow_dispatch` option, which means that we should be able to request that any or all of these jobs be run.
I'm not really comfortable with the GitHub Actions schema yet...so wish me luck!

Create GitHub Action for tests that run on a schedule

---

.github/workflows/testing.yml
.github/workflows/weekly.yml
README.md

Fix inconsistency in xarray cron tests and update README badges

---

README.md
changelog/1327.doc.rst
docs/about/credits.rst

Deletes deprecated links, TO DO: add updated ones
Updates deprecated links

Update community meeting info in README file

---

plasmapy/formulary/tests/test_collisions.py
plasmapy/particles/tests/test_particle_class.py

Fixing remaining warnings in issue #844

---

changelog/1374.doc.rst
docs/bibliography.bib
plasmapy/diagnostics/thomson.py
plasmapy/formulary/radiation.py
plasmapy/simulation/particle_integrators.py
plasmapy/simulation/particletracker.py

This PR moves a few more references from individual docstrings to the bibliography page.

Put references in bibliography

---

plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/thomson.py

More reST fixes that I started after doing a `make nitpicky` doc build and looking at the errors, and then taking a few minutes to make a few other docstring edits.  I don't think that there are any substantive changes here at all.

Minor docstring fixes in `thomson.py` and `langmuir.py`

---

changelog/1309.feature.rst
plasmapy/particles/__init__.py
plasmapy/particles/parsing.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

This new functions is useful to build objects representing molecules from user input or when parsing input files The mass of the created `CustomParticle` is simply the sum of the masses of its components. If the input is a simple particle, then a `Particle` object is created.
docstrings.

Add a function to create CustomParticles from molecule symbols.

---

docs/conf.py

Due to https://github.com/scipy/scipy/issues/15545. This should fix the failing doc build - hopefully.
docstrings.

Adjust scipy intersphinx mapping

---

CODEOWNERS

As discussed in https://github.com/PlasmaPy/PlasmaPy/discussions/1348

Limit CODEOWNERS to pinging plasmapy-reviewers group

---

requirements/tests.txt
setup.cfg

Add pytest-xdist to test reqs

---

changelog/1427.trivial.rst
plasmapy/analysis/nullpoint.py
plasmapy/analysis/tests/test_nullpoint.py

Improving code coverage for null point finder by adding unit test for the case when vector values are entered by the user

---

changelog/1479.trivial.rst
plasmapy/particles/_elements.py
plasmapy/particles/_isotopes.py
plasmapy/particles/_parsing.py
plasmapy/particles/_special_particles.py
plasmapy/particles/atomic.py
plasmapy/particles/decorators.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_class.py
plasmapy/particles/particle_collections.py
plasmapy/particles/serialization.py
plasmapy/particles/tests/test_decorators.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/particles/tests/test_particle_collections.py

This PR uses the [Sourcery](https://sourcery.ai/) tool to automatically refactor plasmapy.particles (along with pre-commit auto-fixes)

Apply automated Sourcery refactorings to `plasmapy.particles`

---

plasmapy/formulary/braginskii.py
plasmapy/formulary/collisions.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/lengths.py
plasmapy/formulary/magnetostatics.py
plasmapy/formulary/mathematics.py
plasmapy/formulary/misc.py
plasmapy/formulary/quantum.py
plasmapy/formulary/radiation.py

These are a few quick minor automated fixes from using PyCharm's inspect code feature along with Sourcery.

Minor fixes in `plasmapy.formulary` from PyCharm & Sourcery

---

changelog/1558.trivial.rst
plasmapy/analysis/fit_functions.py
plasmapy/analysis/swept_langmuir/floating_potential.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/parameters.py
plasmapy/particles/__init__.py
plasmapy/particles/_parsing.py
plasmapy/plasma/grids.py
plasmapy/plasma/sources/plasma3d.py
plasmapy/plasma/sources/plasmablob.py
plasmapy/utils/__init__.py
plasmapy/utils/decorators/checks.py
requirements/tests.txt
setup.cfg
tox.ini

This PR adds [`flake8-simplify`](https://github.com/MartinThoma/flake8-simplify) as a flake8 extension, and implements most of the suggested changes.

Add `flake8-simplify` to linters

---

docs/about/credits.rst

 add my name to docs/about/credits.rst

---

plasmapy/README.md

This isn't needed so we can delete it.

Remove unneeded `plasmapy/README.md` file

---

changelog/1599.doc.rst
docs/about/credits.rst

These updates to the author list are in preparation for the 0.8.0 release (#1595).  I sorted the author list by given name because that way I was able to mostly automate it.  I also tracked down the names and ORCIDs of a few of the contributors too.

Alphabetize and update author list

---

CHANGELOG.rst
README.md
changelog/1397.breaking.rst
docs/about/_stability.rst
docs/about/citation.rst
docs/about/vision_statement.rst
docs/ad/index.rst
docs/contributing/doc_guide.rst
docs/notebooks/analysis/nullpoint.ipynb
docs/whatsnew/0.7.0.rst
plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/charged_particle_radiography.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/formulary/dielectric.py
plasmapy/formulary/distribution.py
plasmapy/formulary/tests/test_magnetostatics.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/plasma/grids.py
plasmapy/utils/datatype_factory_base.py
plasmapy/utils/tests/test_datatype_factory_base.py

This is from an interactive spellcheck with scspell, which has a lot more false positives than codespell.

Perform spellcheck with `scspell`

---

docs/plasma_calculator/index.rst
plasmapy/analysis/nullpoint.py
plasmapy/utils/calculator/__init__.py

This PR adds some documentation that the plasma calculator and null point finder are prototypes, and adds admonitions that state that the API might change in the future.

Mark features as prototypes

---

changelog/1649.doc.rst
docs/common_links.rst
docs/contributing/code_guide.rst

This PR splits the introductory paragraphs of the coding guide from #1305 into its own pull request.

Update the preamble to the coding guide

---

changelog/1705.trivial.rst
plasmapy/formulary/collisions.py
plasmapy/formulary/tests/test_collisions.py

Add check for unequal array lengths to `CollisionFrequencies`

---

changelog/1714.trivial.rst
plasmapy/__init__.py
plasmapy/analysis/fit_functions.py
plasmapy/analysis/swept_langmuir/tests/test_floating_potential.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/diagnostics/thomson.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/tests/test_Fermi_integral.py
plasmapy/formulary/tests/test_collisions.py
plasmapy/formulary/tests/test_distribution.py
plasmapy/formulary/tests/test_quantum.py
plasmapy/formulary/tests/test_thermal_speed.py
plasmapy/formulary/tests/test_transport.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_ionization_state.py

These are a scattering of automated refactorings that came from [Sourcery](https://sourcery.ai/) via this [PR to my fork](https://github.com/namurphy/PlasmaPy/pull/25) (which I'm doing before my Sourcery subscription ends shortly). I looked through the suggested refactorings and accepted most of them, though not all.  I made some slight (mostly inconsequential) changes to a few of the refactorings.  There are a lot of files being changed, but the refactorings are pretty straightforward.
The bulk of the changes are:
- Changing conditional blocks into one-line conditional expressions
- Changing `self` → `cls` for classmethods
- Simplifying `return` statements
- Changing things to f-strings

Apply automated Sourcery refactorings

---

CODEOWNERS

Reverts PlasmaPy/PlasmaPy#1351
We decided we like the more granular approach.

Revert "Limit CODEOWNERS to pinging plasmapy-reviewers group"

---

docs/about/credits.rst

Add elliotwutingfeng to credits.rst

---

changelog/1826.doc.rst
changelog/README.rst

This PR makes some minor updates to the changelog guide, including more example changelog entries and addressing whether or not changes to be tests need to be described along with changes to functionality.

Update changelog guide

---

plasmapy/analysis/swept_langmuir/ion_saturation_current.py
plasmapy/analysis/tests/test_nullpoint.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_synthetic_radiography.py
plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/thomson.py
plasmapy/formulary/dimensionless.py
plasmapy/formulary/lengths.py
plasmapy/formulary/quantum.py
plasmapy/formulary/tests/test_lengths.py
plasmapy/simulation/tests/test_particletracker.py
plasmapy/utils/data/tests/test_downloader.py
plasmapy/utils/decorators/tests/test_checks.py
plasmapy/utils/decorators/tests/test_validators.py

This PR applies some changes made by `ruff`, which are mostly related to removing unused imports.

Apply ruff --fix to repository

---

README.md

This updates the links in `README.md` for feature requests and bug reports, as the old links were from before we started using issue forms.

Update create issue links in `README.md`

---

LICENSE.md
README.md

Following our longstanding tradition, this PR does a `copyright++` and makes some relatively minor updates to our README file.
Some of the changed lines are auto-justification to 72 characters. Most of the substantive changes are in the first paragraph or two.

Update README file and copyright year

---

docs/index.rst

As discussed on today's telecon. Not sure if the best place to put it.

Add plep link in docs

---

.pre-commit-config.yaml

As discussed in https://github.com/PlasmaPy/PlasmaPy/issues/1878#issuecomment-1382122622

Update pre-commit autoupdater to monthly

---

.github/workflows/add_comments.yml

This PR is to make a few adjustments to the code review checklist.  I want to make it so that it's directed not solely at the reviewer, but both the contributor and the reviewer. I'll probably make a few more adjustments too (like asking about SI units, and then shortening other parts if possible).
I'm also using this PR to test that the checklist is getting posted as intended after #1956.

Update pull request checklist

---

plasmapy/formulary/lengths.py

This PR fixes a minor formatting issue in the docstring for `plasmapy.formulary.lengths.Debye_length`.

Make mostly stylistic edits to `plasmapy.formulary.lengths`

---

docs/about/credits.rst
plasmapy/formulary/collisions/coulomb.py

Updated the Coulomb_log variable from 'n' to 'n_e'  in the example section (issue #2003)
Closes #2003

Updated Coulomb_log example to n_e

---

docs/common_links.rst
docs/contributing/workflow.rst

This PR updates the code contribution workflow page in the contributor guide to add a step for contributors to add their name to the list of contributors.

Add step in code contribution workflow to add name to list of contributors

---

plasmapy/dispersion/analytical/stix_.py
plasmapy/dispersion/analytical/tests/test_stix_.py
plasmapy/dispersion/analytical/tests/test_two_fluid_.py
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/dispersionfunction.py
plasmapy/dispersion/numerical/hollweg_.py
plasmapy/dispersion/numerical/tests/test_hollweg_.py
plasmapy/dispersion/numerical/tests/test_kinetic_alfven_.py
plasmapy/dispersion/tests/test_dispersion.py

This PR is a subset of the changes for `plasmapy.dispersion` made in https://github.com/PlasmaPy/PlasmaPy/pull/2080, which were made mostly automatically by ruff.

Apply `ruff` changes to `plasmapy.dispersion`

---

requirements.txt

This PR makes another automatic update for `requirements.txt` prior to our release this month.

Update `requirements.txt` prior to `v2023.5.0`

---

.github/workflows/close-pr.yml

This PR makes some minor updates, such as updating versions of GitHub Actions.

Update PR unlabeler GitHub Action

---

.github/workflows/update-pinned-reqs.yml

This PR fixes a few issues with this action, including formatting and that the checks will not be run

Update GitHub Action to update requirements

---

.github/workflows/update-pinned-reqs.yml

I'm still trying to get this action to work so that it will actually run the GitHub Actions when the pull request is created.
I'm following [these instructions](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) and using [this GitHub Action](https://github.com/tibdex/github-app-token).

Update GitHub Action to update requirements.txt

---

.github/workflows/update-pinned-reqs.yml
requirements.txt

Given that I had trouble with getting tests to run in this Action, I decided to add some comments. Also I needed to fix the link in the Easter egg.

Update GitHub Action to regenerate requirements

---

changelog/2219.trivial.rst
plasmapy/analysis/nullpoint.py
plasmapy/analysis/time_series/excess_statistics.py
plasmapy/formulary/collisions/helio/collisional_analysis.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/utils/calculator/widget_helpers.py
plasmapy/utils/decorators/helpers.py
plasmapy/utils/decorators/validators.py

This PR makes some automated changes by [Sourcery](https://docs.sourcery.ai).
I used the CLI:
```bash
sourcery review plasmapy --fix
```
I included some updates about comments.

Automated changes from Sourcery

---

docs/contributing/workflow.rst

Shell command correction (In contribution workflow)

---

changelog/2229.trivial.rst
plasmapy/formulary/distribution.py
plasmapy/formulary/tests/test_distribution.py

Raise ValueError for implicit cases in `distribution`

---

plasmapy/analysis/nullpoint.py
pyproject.toml

Resolves PERF401 error raised in #2238 by using list comprehensions in the `nullpoint` module

Appease Ruff in `nullpoint`

---

.github/workflows/pr-labeler-changelog.yml

This PR is to make some minor edits to the GitHub Action for adding no changelog entry needed labels, and to test it.

Update GitHub Action for adding no changelog entry needed label autoupdate

---

plasmapy/utils/decorators/tests/test_lite_func.py

Reduce number of warnings in `plasmapy.utils`

---

plasmapy/analysis/tests/test_nullpoint.py

Make it so no warnings are issued in tests of `plasmapy.analysis`

---

pyproject.toml
requirements.txt

Update sphinx-notfound-page and other reqs

---

plasmapy/formulary/collisions/helio/tests/test_collisional_analysis.py
plasmapy/formulary/collisions/tests/test_frequencies.py
plasmapy/formulary/lengths.py
plasmapy/formulary/tests/test_lengths.py
pyproject.toml

Reduce number of warnings issued during tests by `plasmapy.formulary`

---

.pre-commit-config.yaml
plasmapy/__init__.py
pyproject.toml
requirements.txt

...prior to releasing 2023.9.0.  Mostly these are auto-updates.

Update requirements, ruff rules, and pre-commit configuration

---

README.md

Nothing major, mostly just updating dates.

Minor updates to `README.md`

---

changelog/2300.bugfix.rst
docs/about/citation.rst
docs/install.rst

I also updated the DOI that cites all versions of PlasmaPy that are under the `team@plasmapy.org` account.

Update metadata for `v2023.10.0`

---

.github/labeler.yml

Version 5 of the `labeler` action includes breaking changes. This pull request updates our `labeler.yml` file to agree with the new update

Fix Labeler Action

---

.pre-commit-config.yaml
plasmapy/dispersion/dispersion_functions.py
plasmapy/dispersion/dispersionfunction.py
plasmapy/formulary/relativity.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_collections.py
plasmapy/particles/tests/test_ionization_state.py
pyproject.toml

I removed ruff rule RUF018 because it is experimental and started causing errors in CI.  While I was hanging out in the file, I did a `pre-commit autoupdate` as well.

Update pre-commit hooks and remove an experimental ruff rule

---

LICENSE.md
README.md
mypy.ini

- Updated copyright year to 2024 🎉 
- Updated meeting info in `README.md`
- Reverted the mypy configuration after inadvertent changes in another PR

Fix mypy configuration and routine updates 

---

plasmapy/analysis/fit_functions.py
plasmapy/analysis/time_series/conditional_averaging.py
plasmapy/diagnostics/charged_particle_radiography/detector_stacks.py
plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/formulary/collisions/helio/collisional_analysis.py
plasmapy/particles/particle_class.py
plasmapy/plasma/grids.py
plasmapy/simulation/particletracker.py
plasmapy/utils/_pytest_helpers/tests/test_pytest_helpers.py
plasmapy/utils/code_repr.py
plasmapy/utils/datatype_factory_base.py

This is a follow-up to #2437 and #2439.

Add type hints for bool default arguments

---

plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_synthetic_radiography.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/particles/ionization_state.py
plasmapy/plasma/grids.py
plasmapy/utils/calculator/widget_helpers.py
plasmapy/utils/decorators/checks.py

This PR is one in a series to use autotyping to add type hint arguments.

Add type hints for float default arguments

---

plasmapy/analysis/nullpoint.py
plasmapy/formulary/tests/test_distribution.py

This PR reduces the number of `DeprecationWarnings` that show up in our tests.

Resolve deprecation warnings in tests

---

plasmapy/formulary/distribution.py

Fixing a reStructuredText error found by @rocco8773.

Fix `kappa_velocity_3D` docstring

---

.github/workflows/tests.yml

The name of the associated tox environment has changed. This pull request updates the tests.yml workflow file to reflect these new changes

Fix Codecov Workflow

---

.github/workflows/weekly-tests.yml

I made some updates earlier which had inconsistent versions of Python in weekly tests. This PR fixes those problems, and makes some other minor updates.

Update versions of Python in weekly tests

---

.github/workflows/weekly-tests.yml

Fix coverage setup in weekly tests

---

changelog/2483.trivial.rst
changelog/2504.internal.rst
changelog/2519.trivial.rst
changelog/2522.doc.rst
changelog/2542.internal.rst
changelog/2543.internal.rst
changelog/2552.internal.rst
changelog/2584.internal.rst
changelog/2614.trivial.rst
changelog/2618.doc.rst
changelog/2627.bugfix.rst
changelog/2654.internal.rst
docs/conf.py

This PR makes a few slight adjustments to a few changelog entries ahead of our upcoming release.

Update changelog entries prior to v2024.5.0 release

---

binder/requirements.txt
changelog/2672.bugfix.rst

This is an attempt to fix the problem with opening binder links as described in #1635.

Update requirements for binder

---

CITATION.cff

Alphabetize author list in `CITATION.cff`

---

CITATION.cff
src/plasmapy/plasma/equilibria1d.py

Added examples for each of the methods in the HarissonSheet class. 
We could increase the readers understanding of HarrisSheet with some examples that replicate Harris Sheet results. [ref](https://www.nature.com/articles/s41467-023-35821-9)
Closes  #2530

HarrisSheet examples added

---

.github/workflows/comment-on-pr.yml
changelog/2765.trivial.rst

- I removed the notice about the switch to an `src` layout, since it's been several months.
- I shortened a few parts, such as the links to the contributor guide.  
- I added more emojis. 😅

Update comment that gets posted to pull requests

---

CITATION.cff
src/plasmapy/formulary/speeds.py

This PR adds a racecar zoom emoji to the Alfven Speed doc string to indicate that the Alfven speed is very fast.

Adding racecar emoji to Alfven Speed

---

CITATION.cff
docs/about/citation.rst

Adding emoji to documentation.

Added Memo Emoji to Citation Page (PlasmaPy Summer School Demo)

---

CITATION.cff
docs/getting_started.rst

added periods to getting started

---

CITATION.cff
changelog/2824.doc.rst
src/plasmapy/formulary/mathematics.py

Restructured sub sections for rot_a_to_b to be consistent with other pages and added a raises, example sub-section.

math formulary - restructured function page for rot_a_to_b and added raises, example section

---

CITATION.cff
docs/contributing/getting_ready.rst

add supervillian emoji next to cloning header.

add supervillian emoji next to cloning header.

---

CITATION.cff
docs/CODE_OF_CONDUCT.rst

Added pledge emoji to CoC page

---

CITATION.cff
docs/getting_started.rst

lil sloth dood hanging on a branch added to getting started

---

CITATION.cff

Some minor updates to `CITATION.cff` to alphabetize contributors following the summer school and add some missing metadata.

Organize `CITATION.cff`

---

.pre-commit-config.yaml
changelog/2800.feature.rst
changelog/2824.doc.rst
changelog/2831.doc.rst
changelog/2833.doc.rst
changelog/2843.breaking.rst
changelog/2857.internal.rst
changelog/2861.doc.rst

This PR makes a few slight updates to recent changelog entries ahead of the v2024.10.0 release which I'm planning to do today-ish.

Update changelog entries ahead of v2024.10.0 release

---

docs/COMMUNICATION.rst

Matrix chat room in documentation needs emoji

Add emoji for chat room

---

CHANGELOG.rst
CITATION.cff
changelog/2784.internal.rst
changelog/2794.internal.rst
changelog/2800.feature.rst
changelog/2822.doc.rst
changelog/2824.doc.rst
changelog/2830.doc.rst
changelog/2831.doc.rst
changelog/2832.feature.rst
changelog/2833.doc.rst
changelog/2834.internal.rst
changelog/2834.trivial.rst
changelog/2841.internal.rst
changelog/2843.breaking.rst
changelog/2843.bugfix.rst
changelog/2857.internal.rst
changelog/2861.doc.rst
changelog/2868.feature.1.rst
changelog/2868.feature.2.rst
changelog/2869.internal.rst
changelog/2871.breaking.rst
changelog/2879.internal.rst
docs/about/citation.rst
docs/changelog/2024.10.0.rst

This PR merges changes back in from the v2024.10.0 release.

Merge changes back in from v2024.10.x

---

changelog/2895.doc.rst
docs/about/credits.rst

This PR makes updates the acknowledgements page in the documentation by listing several projects and organizations that have supported the PlasmaPy project and/or are in alignment with our mission.
This is a spinoff of #2892 to reduce that PR size.

Update acknowledgements page in documentation

---

changelog/2901.doc.rst
docs/changelog/0.1.0.rst
docs/changelog/0.1.1.rst
docs/changelog/0.2.0.rst
docs/changelog/0.3.0.rst
docs/changelog/0.3.1.rst
docs/changelog/0.4.0.rst
docs/changelog/0.5.0.rst
docs/changelog/0.6.0.rst
docs/changelog/0.7.0.rst
docs/changelog/2023.10.0.rst
docs/changelog/2024.7.0.rst
docs/index.rst

- Fixed formatting and consistentified verb tenses in old changelogs
- Rearranged the index page of the documentation
- Made it so that emojis in titles don't show up in the sidebar (since on some browsers only the left half of the emoji showed up)

Make minor updates to documentation and changelog

---

CITATION.cff
changelog/2932.doc.rst
src/plasmapy/dispersion/__init__.py

Closes #2916 by providing a brief introduction on dispersion relation.

Added introduction for dispersion relation 

---

tests/formulary/test_distribution.py

This small PR evaluates and displays the integral value on test fail.

Display integral value on test fail

---

.github/workflows/mint-release.yml

This PR adds an extra space from changes made in #3081.

Fix typo in workflow

---

.github/workflows/mint-release.yml

Fix regular expression in workflow
