PlasmaPy/PlasmaPy

code_of_conduct.md

Beginning with version 1.3 of the Contributor Covenant code of conduct

Creating code_of_conduct.md

---

setup.py

Following the discussion in issue https://github.com/PlasmaPy/PlasmaPy/issues/37 about semantic versioning, this pull requests sets us as working towards version 0.1 as our initial minor release.  This also affects our discussion in issue https://github.com/PlasmaPy/PlasmaPy/issues/25.

Moving towards semantic versioning

---

plasmapy/constants/atomic.py
plasmapy/constants/tests/test_atomic.py

The changes to the docstrings are to make sure that the exceptions that are listed correspond to the exceptions that are called in the code.  The other change is that some of these functions now raise a UserWarning when the charge state is -4 or below, though we could potentially change this to -3 or below based on advice from my upstairs neighbor who is a chemist.
[These are fairly minor changes.]

Exception docstrings and negative charge states in atomic routines

---

plasmapy/analytic/analytic.py
plasmapy/analytic/tests/test_dispersion.py

This pull request has more detailed exception handling for `plasma_dispersion_function()` and `plasma_dispersion_function_deriv`.  These functions can yield a TypeError, UnitsError, or ValueError.  These exceptions are now tested.
I also added the ability for these functions to accept a `Quantity` as an input, as long as it is dimensionless.  However, the functions will not return a quantity but rather a `complex`, `float`, or `ndarray`.

Improved exception handling for plasma dispersion function

---

.travis.yml

Just a small addition to the travis config file that lets it send notifications about the current test status to the matrix room. Clearly this assumes we continue using the matrix room - it can be removed again if we don't.

Set up travis notifications for the matrix room

---

plasmapy/physics/parameters.py
plasmapy/utils/__init__.py
plasmapy/utils/checks.py
plasmapy/utils/tests/test_checks.py

Attempt to resolve issue: https://github.com/PlasmaPy/PlasmaPy/issues/55
Refactors `test_checks` to use `pytest.mark.parametrize` so the new decorators can use the same examples as `_check_quantity` and `_check_relativistic`.
Using `check_relativistic`:
```python
from astropy import units as u
@check_relativistic
def speed():
return 1*u.m/u.s
```
or with keywords:
```python
@check_relativistic(betafrac=0.01)
def speed():
return 1*u.m/u.s
```
Using `check_quantity`:
```python
@check_quantity("x")
@check_quantity("y", can_be_negative=False)
def func(x: u.m, y: u.s=1*u.s):
return x
func(1*u.m, 2*u.s)
```
I was able to convert most parameter functions. Parameter functions `electron_gyroradius`, `ion_gyroradius`, and `Alfven_speed` could not be converted because it does some preprocessing …

Check decorators

---

plasmapy/constants/__init__.py

Spotted this while I was doing something else. Since we decided a few weeks ago only to support astropy >2.x, checking for version seems redundant to me.

Small tweak for dropping astropy < 2.x

---

plasmapy/constants/atomic.py
plasmapy/physics/__init__.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/tests/test_quantum.py
plasmapy/physics/tests/test_relativity.py
plasmapy/physics/tests/test_transport.py
plasmapy/physics/transport.py
plasmapy/utils/checks.py

This pull request will create a function called `Coulomb_logarithm` that is needed for a bunch of transport coefficients that involve Coulomb collisions.  This function will need to specify what the particles are that are colliding (e.g., electron-electron or electron-proton collisions).  
There are approximations in the NRL Plasma Formulary, for example, but the expressions there do not contain the physics.  It will be better for people to be able to read the function and understand the physics of what is going on.  The documentation also should have a good, concise discussion of the physics.
The inner length scale is sometimes the de Broglie wavelength, which will require a new function...perhaps in `quantum.py`?  
I would like to get this to be as accurate as we can, so it is rather …

Calculate the Coulomb logarithm, Lorentz factor, and de Broglie wavelength

---

plasmapy/classes/species.py
plasmapy/classes/tests/test_Species.py

Modified the interpolation routine to allow unequal spatial dimension grid (nx,ny,nz) with nx!=ny!=nz. 
Also added a test case.

Stepper: Allowing unequal spatial dimensions grid

---

ROADMAP.md
vision_statement.md

This pull request contains updates to the vision statement after a few months into the project.  
The main change is to absorb the Code Development Committee into the Coordinating Committee.    The responsibilities for both of these committees are blurred, and this pull request combines the two committees into a single committee.  For the first few months of active code development, the organization has been very informal.  This pull request is in advance of solidifying committee membership.
Are there any other changes that we should make while we're revisiting the vision statement?  I'll read through this page again in case there are any other places we'd like to update this.

Revise vision statement and create roadmap document

---

CHANGE_LOG.md
RELEASE_NOTES.md
vision_statement.md

I added new files for the change log and release notes for our 0.1 release.  The content of these files is temporary and will need to be revised as we approach the release date.  I am not sure if it is best to store the change log and release notes here or elsewhere (such as in the docs subdirectory).
I edited the vision statement and change log to say that PlasmaPy uses [Semantic Versioning](http://semver.org/), which a few of us had informally decided upon in the past but I don't think we ever officially decided it.  Is it okay if we officially say that we're using Semantic Versioning?

Include versioning in vision statement and add change log/release notes

---

plasmapy/atomic/tests/test_atomic.py

Works on issue #118 for `atomic` module. There are some style changes, for example: `9.11e-31*u.kg` to `9.11e-31 * u.kg`.

Split tests in atomic

---

setup.py

Closes #121 
You can test out the fix in this pull request by starting a clean environment and running:
```bash
$ pip install git+https://github.com/thomasjpfan/PlasmaPy@setup_fix
```

Fix setup.py packaging

---

plasmapy/_metadata.py

Further to PR #123, addresses (indirectly) #121. Just an increment of the version number so there's a distinct build on PyPI.

increment dev version number

---

.travis.yml
requirements/base.txt

Closes #120.
It appears that `coveralls` is only required in a development environment, and has therefore been removed. 
Removing the coveralls dependency also removes the following dependencies:
* certifi-2017.7.27.1 
* chardet-3.0.4
* coverage-4.4.1 
* docopt-0.6.2 
* idna-2.6 
* requests-2.18.4 
* urllib3-1.22           
Only the following dependencies are installed:
* astropy-2.0.2 
* numpy-1.13.1 
* py-1.4.34 
* pytest-3.2.2 
* scipy-0.19.1

remove coveralls requirement as unnecessary dependency

---

plasmapy/physics/tests/test_transport.py
plasmapy/physics/transport.py

Closes #133
All the definitions in physics:
```
def Lorentz_factor(V):
def deBroglie_wavelength(V, particle):
def Alfven_speed(B, density, ion="p"):
def ion_sound_speed(*ignore, T_e=0*units.K, T_i=0*units.K,
gamma_e=1, gamma_i=3, ion='p'):
def electron_thermal_speed(T_e):
def ion_thermal_speed(T_i, ion='p'):
def electron_gyrofrequency(B):
def ion_gyrofrequency(B, ion='p'):
def electron_gyroradius(B, *args, Vperp=None, T_e=None):
def ion_gyroradius(B, *args, Vperp=None, T_i=None, ion='p'):
def electron_plasma_frequency(n_e):
def ion_plasma_frequency(n_i, ion='p'):
def Debye_length(T_e, n_e):
def Debye_number(T_e, n_e):
def ion_inertial_length(n_i, ion='p'):
def electron_inertial_length(n_e):
def magnetic_pressure(B):
def magnetic_energy_density(B: units.T):
def upper_hybrid_frequency(B, …
```

Check consistency of argument ordering in physics

---

LICENSE.md
README.md
licenses/PlasmaPy_LICENSE_preOct2017.md

The Open Source Initiative (OSI) recently approved a new license that consists of the [BSD 2-clause license with an added patent clause](https://opensource.org/licenses/BSDplusPatent).  The purpose of the patent clause is to give users the right to continue to use a package even if a contributor patents their contribution.  This new license resolves an issue that has been raised about the BSD license (and many others) that it does not explicitly protect against software patents.
This commit adds the patent clause to our BSD 3-clause license to ensure that future users have the right to continue to use the package even if part of it gets patented.
> Subject to the terms and conditions of this license, each copyright holder and contributor hereby grants to those receiving rights under this …

Add patent clause to license

---

plasmapy/physics/__init__.py
plasmapy/physics/quantum.py
plasmapy/physics/tests/test_quantum.py

Added functions for thermal deBroglie length, Thomas-Fermi screening length, and Fermi energy. Also added corresponding tests and imports in __init__.py. Added check to quantum.py and test_quantum.py for if module is called __main__, which then swaps from relative to absolute path imports. This allows for individual execution/testing of these modules.

Added functions to quantum.py

---

plasmapy/math/math.py
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/transport.py

Closes #155 
Changed some of the math formatting in the docstrings so that they appear correctly on Read the Docs, and fixed a few small other formatting errors too. A test version for the updated docs is [here](http://plasmapy-fixed-math-test.readthedocs.io/en/fixing_rtd_math/)!

Fixed math and minor errors in docstrings for Read the Docs

---

plasmapy/physics/__init__.py
plasmapy/physics/distribution.py
plasmapy/physics/tests/test_distribution.py

Added and modified 1D and 3D Maxwellian speed and velocity distribution functions. These functions also include optional drift velocities/speeds. I've included tests for these new functions, but the 3D tests fail because scipy's QUADPACK based triple integral doesn't play nice with units. I'm open to suggestions on how to work around this!
Contributions towards #101  and #141

Added/modified 1D and 3D Maxwellian speed/velocity distributions

---

plasmapy/atomic/atomic.py
plasmapy/atomic/nuclear.py
plasmapy/atomic/tests/test_atomic.py
plasmapy/atomic/tests/test_nuclear.py
plasmapy/physics/parameters.py
plasmapy/physics/tests/test_parameters.py

Prior to now, `nuclear_binding_energy` used `isotope_mass` to get the mass of the nuclide.  This is incorrect since `isotope_mass` gives the mass including the bound electrons.  Now `nuclear_binding_energy` uses `ion_mass` instead, and assumes that isotope is fully ionized to get the mass of the nucleus.
This pull request also implements the great suggestion by @jessicalostinspace in #110 to represent the reactants and products in a nuclear reaction as lists:
```Python
>>> nuclear_reaction_energy(reactants=['He-4', 'He-4'], products=['Be-8'])
```
For the time being, I decided to still allow the old API which has the argument being a string representing the reaction (e.g., `'He-4 + He-4 -> Be-8'`).  The advantage of allowing the old API is that it is more human readable.  The disadvantages …

Refactor nuclear_binding_energy and nuclear_reaction_rate

---

plasmapy/atomic/nuclear.py
plasmapy/atomic/tests/test_nuclear.py

Up until now, `nuclear_reaction_energy` allowed inputs such as:
```Python
nuclear_reaction_energy('Be-8 --> 2He-4')
```
where the `2` in the above code snippet has been treated as a multiplicative factor.  However, an idea has been brought up in #169 and #178 to allow a different format for isotopes where the mass number precedes the atomic symbol (e.g., `'4He'` would be the same as `'He-4'`).  If we do implement that idea, then there would have been ambiguity between mass numbers and multiplicative factors (e.g., would `'4He'` be one `'He-4'` isotope or four `'He'` atoms?).  This pull request changes the required format to
```Python
nuclear_reaction_energy('Be-8 -> 2*He-4')
```
to reduce the chance for ambiguity.  We're still discussing whether or not to allow isotopes to be represented …

Require an asterisk for multiplicative factors in nuclear_reaction_energy

---

plasmapy/classes/species.py
plasmapy/classes/tests/test_Species.py

As of now, PlasmaPy tests alone (I'm not counting the setup here) take 126.58 seconds on Travis. I'm going to see if I can trim some fat from tests in the Species submodule, which is currently pretty bad on performance.
This is heavily work in progress right now, I just don't feel like setting benchmarks up locally.

attempt at shortening a bunch of tests in Species

---

docs/conf.py
plasmapy/physics/parameters.py

This makes it possible to link to documentation in other Python projects - for example, I've changed the parameter documentation so now "Quantity" is a clickable link, that takes the reader to the Astropy website documentation for the `Quantity` class.

Use intersphinx to link to other python projects

---

.circleci/config.yml
doc-requirements.txt
docs/conf.py
docs/development/release_guide.rst
docs/mathematics/index.rst
plasmapy/mathematics/mathematics.py
plasmapy/physics/transport.py

Fixes #197. I think this will need someone who is a member of the PlasmaPy organisation to enable circleci at https://circleci.com if/once this PR is merged.
I had to fix a few documentation warnings, but now the build will fail if sphinx finds anything wrong with the docs that causes it to warn. Just calling `make html` will build regardless of warnings, which will show up in red in the terminal.
My branch builds here: https://circleci.com/gh/dstansby/PlasmaPy/9

Doc testing

---

plasmapy/mathematics/tests/test_dispersion.py

A long time ago in a galaxy far, far away in pull request #14, before I discovered GitHub emoji 🍝 , I created some tests for `plasma_dispersion_func` and `plasma_dispersion_func_deriv`.  In these old tests, I had a bunch of different `assert` statements.  This pull request makes use of `pytest.mark.parametrize` to better organize the tests and allow the tests to be extended more easily.  I updated the error messages to provide significantly more detail.
This pull request partially addresses #195.

Make plasma dispersion function tests less horrible

---

plasmapy/utils/exceptions.py
plasmapy/utils/tests/test_exceptions.py

The atomic ⚛️ subpackage currently raises `ValueError` and `TypeError` a whole bunch of times.  These exceptions are appropriate but are not specific enough to distinguish between different types of problems and make use of exception subclassing.  For example, a particle such as `'Fe-56'` is an invalid ion but a valid isotope.  In this case, this particle should raise something like an `IonError` but not an `IsotopeError`.
I started out by adding `AtomicError`, `IonError`, `IsotopeError`, `ElementError`, and `ParticleError` as exceptions and `AtomicWarning` as a warning.  We will need to think more carefully about how to handle subclassing.
I also added "pass" to each of the exceptions and warnings.  This does not appear to be needed, but I was thinking that this line would show up in …

Create exceptions and warnings for atomic subpackage

---

plasmapy/atomic/atomic.py

I was just reading about function annotations, and began to realize how awesome type hints are.  As an example, let's start with a simple function:
```Python
def add(a, b):
return a + b
```
Adding type hints changes this to:
```Python
def add(a: float, b: float) -> float:
return a + b
```
More complex things can be done with the [`typing`](https://docs.python.org/3/library/typing.html) module (including `Union`, `Any`, `Optional`, `List`, etc.), which is provisionally included in the standard library so backward compatibility is not guaranteed.  
While Python is a dynamically typed language and the type hints are never enforced, this is helpful because:
- Type hints make the code more readable
- Type hints allow optional static type checking with packages such as `mypy` (which is …

Add type hints to atomic subpackage

---

plasmapy/physics/parameters.py
plasmapy/physics/tests/test_parameters.py

Added optional argument `z_mean=None` to a bunch of functions in `parameters.py`. When value is `None` it defaults to using atomic charge state and signals a `PhysicsWarning`. These warnings may get annoying, so either tests need to be changed to use some value, like `z_mean=1` to avoid the warnings during pytest or can remove the warnings entirely.
I also added tests for `z_mean` under `test_parameters.py`.
Addresses #184

Average ionization

---

.circleci/config.yml

So I think it's a tragedy that we're currently waiting for Latex to slowly build at the end of the job after all the HTML is ready. I thus went ahead and split that in two.
Ideally I'd like to be able to install (PlasmaPy and its dependencies) and (latex from apt-get) simultaneously, but [I wasn't yet able to do that](https://github.com/StanczakDominik/PlasmaPy/commits/faster-circle).

Run two CircleCI jobs in parallel

---

plasmapy/mathematics/mathematics.py
plasmapy/mathematics/tests/test_dispersion.py

Modified plasma_dispersion_func to use wofz() in scipy as Faddeeva function in mathematic.py . Modified rtol values so the tests pass. Modified the values in Docstring so the Doctests pass.
Closes #208

Modified plasma_dispersion_func to use wofz() in scipy. Fixed tests

---

.circleci/config.yml
appveyor.yml

Fixes failing builds due to circleCI not having numpy available for Cython integration. Basically the dependencies and installation of PlasmaPy must be done in two separate steps.

Fixing circleCI failing builds cython

---

plasmapy/physics/transport.py

Fixes #254 
Included variables such as beta_par, beta_cross inside their respective & general "if" statements in the following functions:
1) _nondim_tc_e_braginskii
2) _nondim_tc_i_braginskii
3) _nondim_resist_braginskii
4) _nondim_tec_braginskii

Fix #254: Optimize Braginskii code

---

plasmapy/atomic/classes.py

Closes #262.
Should we the name module level function as `reduced_mass()` or something else (like `get_reduced_mass()`, the way it is in this PR)?
I think naming both `Particle.reduced_mass()` object method and module level function as `reduced_mass()` could confuse beginners, just my opinion however.
Let me know if there is anything that could be better!

Particle.reduced_mass() as a module level function

---

.pep8speaks.yml
docs/development/code_guide.rst
docs/development/doc_guide.rst
docs/development/testing_guide.rst
setup.cfg

The [pycodestyle](http://pycodestyle.readthedocs.io/en/latest/) and [pydocstyle](http://www.pydocstyle.org/en/2.1.1/) packages check code and docstrings against style guidelines.  This PR updates `setup.cfg` to include some configuration options for these two packages.  The code and docstring style customizations that I chose are not the ones that we want to go with, so other suggestions on ones to include or exclude would be great.  Alternatively, we could try these out and see how much we like or dislike them.  The most important things are consistency and readability.
The extra [pycodestyle error codes](http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes) are:
>  - E226: missing whitespace around arithmetic operator
>  - E241: multiple spaces after ‘,’
>  - E242: tab after …

Customize pycodestyle, pydocstyle, and pep8speaks

---

plasmapy/classes/plasma.py
plasmapy/constants/__init__.py
plasmapy/diagnostics/langmuir.py
plasmapy/mathematics/mathematics.py
plasmapy/physics/__init__.py
plasmapy/physics/dielectric.py
plasmapy/physics/dimensionless.py
plasmapy/physics/distribution.py
plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/utils/checks.py
plasmapy/utils/exceptions.py
plasmapy/utils/import_helpers.py

I am going through and doing things like changing `Quantity` to `~astropy.units.Quantity` so that the links work on our Read the Docs page.  This PR is to make some changes in preparation for code review.  
I also just noticed that we don't have anything in `dimensionless.py`.  I guess that will go in `v0.2.0`!

Update ReST formatting in docstrings

---

.circleci/config.yml

I have written a little bot that will add documentation preview links to your PRs. If you want to use it you need to merge this PR and go here: https://github.com/apps/giles and add the app to the repository.
It gives you a thing that looks like this:
Like this PR: https://github.com/Cadair/giles/pull/3

Add giles to circleci

---

docs/development/code_guide.rst
setup.cfg

The topic of the maximum line length came up in a recent code review session.  The PEP 8 limit is 79 characters because (1) really long lines adversely impact readability, (2) wrapping of long lines by editors disrupts the flow, and (3) this line length makes it easier to display two windows of code side by side.  The 79 character limit resulted in some awkward line breaks using backslashes in the Particle
class, whereas the code would be more readable were it just be on the same line.  Those of us who were present came to a consensus that we should increase the line length so that we can avoid awkward line breaks.
This commit increases the maximum line length by ten characters so that we can avoid these awkward line breaks while still avoiding really long lines.  Comments and docstrings …

Increase pycodestyle maximum line length to 99

---

plasmapy/atomic/parsing.py
plasmapy/atomic/tests/test_parsing.py
requirements/automated-code-tests.txt
requirements/automated-documentation-tests.txt
requirements/environment.txt
requirements/environment.yml
requirements/requirements.txt

Closes #286.
This PR uses the [roman](https://pypi.python.org/pypi/roman) package to parse Roman numerals.
Some examples (same as in https://github.com/PlasmaPy/PlasmaPy/issues/286#issue-301633568):
```python
>>> from plasmapy.atomic import *
>>> integer_charge('Fe X')
9
>>> Particle('O VI').ion
'O 5+'
```
It may raise a `ValueError` with strings like `O -VI` or `O +VI` as `-VI` and `+VI` won't be recognized as roman numerals. So, I've added a try-except block to supress `ValueError` and raise an `InvalidParticleError` instead.

Accept Roman numerals when specifying charge states

---

docs/atomic/decorators.rst
docs/atomic/functional.rst
docs/atomic/index.rst
docs/atomic/nuclear.rst
docs/atomic/particle_class.rst
docs/index.rst
plasmapy/atomic/__init__.py
plasmapy/atomic/particle_class.py
plasmapy/atomic/particle_input.py

This pull request will include narrative documentation for the atomic subpackage.  I've written a first draft for the `Particle` class and still need to write stuff for the functional interface, `@particle_input`, and the nuclear reaction functionality.  I want to make sure to link to the `mendeleev` package for more detailed information about elements (as opposed to, e.g., ions).  I should also make it more clear what valid/standard particle names are being set as.
This PR addresses part of #91.  This is also a test of #291.

Add narrative documentation for atomic subpackage

---

plasmapy/atomic/atomic.py

Hi, I'm looking through the codebase and find two small bugs.
The type annotations are inconsistent with their doc string, and I think the doc is more reasonable. 
I see the review issue #234 is still open, so you will probably notice anyhow. 😃

Correct annotation of atomic_number and isotopic_abundance

---

docs/atomic/particle_class.rst
plasmapy/atomic/__init__.py

I added `proton`, `electron`, `neutron`, `positron`, `deuteron`, `triton`, and `alpha` as pre-created instances of the `Particle` class in `atomic/__init__.py`.  This change allows us to import these `Particle` instances directly from the atomic subpackage, e.g.:
```Python
from plasmapy.atomic import proton, electron
```
These are the most frequently used particles in plasma physics, so I suspect that it will be a useful shortcut for many of us.

Pre-create commonly used Particle instances

---

plasmapy/physics/parameters.py
plasmapy/physics/quantum.py
plasmapy/physics/relativity.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/tests/test_quantum.py
plasmapy/physics/tests/test_relativity.py
plasmapy/physics/transport/collisions.py
plasmapy/utils/checks.py
plasmapy/utils/tests/test_checks.py

Closes #332.
Also likely closes some other older issues. I'll go through and check.
I thought I felt better with having some measure of leniency as to units, while keeping the fact that we're working with units explicit. So this is what I ended up with:
```python
>>> from plasmapy.physics import plasma_frequency
>>> from astropy import units as u
>>> plasma_frequency(10*u.m**-3)
<Quantity 178.39863647 rad / s>
>>> plasma_frequency(10)
WARNING: UnitsWarning: No units are specified for n = 10 in plasma_frequency. Assuming units of 1 / m3.
To silence this warning, explicitly pass in an Astropy Quantity (from astropy.units)
(see http://docs.astropy.org/en/stable/units/) [plasmapy.utils.checks]
<Quantity 178.39863647 rad / s>
>>> 
```
Notes:
* I went ahead and added UnitsWarning to Warns in a …

Fix check_quantity casting to default provided SI's

---

docs/atomic/functional.rst
plasmapy/atomic/__init__.py
plasmapy/atomic/symbols.py

These are a bunch of relatively minor changes to clean up `symbols.py`.  I updated a bunch of the docstrings, and renamed `ion_symbol` to `ionic_symbol` because this function works for neutral atoms where the charge information is given.  I updated a bunch of the docstrings too, and tried to make them more concise.

Update functions and docstrings in atomic/symbols.py

---

plasmapy/classes/tests/test_Plasma.py
plasmapy/mathematics/tests/test_Fermi_integral.py
plasmapy/physics/tests/test_distribution.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/tests/test_quantum.py
plasmapy/physics/tests/test_relativity.py
plasmapy/physics/transport/tests/test_collisions.py
plasmapy/physics/transport/tests/test_transport.py
plasmapy/utils/checks.py
plasmapy/utils/tests/test_checks.py
setup.cfg

It seemed like a good idea at the time, but it turns out everyone takes exception to a ton of `DeprecationWarning`s showing up in Pytest output. Who knew.
I still think it's a good idea somewhat, just that the implementation with pytest was not the right one. 
I'll merge this once tests pass and we're not getting anything too silly in Travis.

Revert "Explicitly show DeprecationWarning in tests"

---

plasmapy/classes/tests/test_Plasma.py

Addresses #315. I am not sure if it is possible to have a set of input values that would result in combination of such as strongly coupled regime with thermal kinetic energy dominant, etc.

Add tests for PlasmaBlob.regimes()

---

plasmapy/physics/transport/collisions.py

Closes #359.
This PR adds docstrings to mention about `RelativityError` raised when input velocity is same or greater than the speed of light.

Mention RelativityError in docstrings

---

plasmapy/examples/plot_braginskii.py
plasmapy/physics/dielectric.py
plasmapy/physics/transport/__init__.py
plasmapy/physics/transport/braginskii.py
plasmapy/physics/transport/collisions.py
plasmapy/physics/transport/tests/test_transport.py

The naming conventions in the PEP 8 style guide say that classes should be in CamelCase.  This PR adopts that naming convention for the class that calculates classical transport coefficients.

Rename classical_transport class to ClassicalTransport

---

plasmapy/classes/plasma.py
plasmapy/utils/pytest_helpers.py

Closes #337 and #331.
For example, now passing a `Quantity` object to `call_string` results in following output:
```python
>>> from plasmapy.utils import call_string
>>> import astropy.units as u
>>> def f(x, y, z):
...        pass
>>> call_string(f, 5 * u.m, {'y': 8*u.m, 'z': 5*u.kg})
'f(5.0 * u.m, y=8.0 * u.m, z=5.0 * u.kg)'
```
However, I personally find this a bit more readable :smile::
```python
'f(5.0*u.m, y=8.0*u.m, z=5.0*u.kg)'
```
What do you guys think?

Handle `Quantity` objects in `call_string()`

---

plasmapy/physics/parameters.py
plasmapy/physics/tests/test_distribution.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/transport/collisions.py
plasmapy/physics/transport/tests/test_collisions.py

Supersedes @apooravc 's #259 and closes #255 .
* Simplifies `_boilerPlate` via calling existing functionality. 
* Removes a bunch of tests now that we're testing their functionality in one centralized place
* Add a `mass` argument to `thermal_speed` (@lemmatum I think you wanted that?). I needed that o get _boilerPlate to work with the reduced mass.

Split boiler plate, add mass argument to thermal_speed

---

docs/index.rst
docs/stability.rst

Astropy's docs have a wonderfully useful page describing the [current status of subpackages](http://docs.astropy.org/en/stable/stability.html).  This page contains information on how stable Astropy's different subpackages are (e.g., if they're stable or undergoing active development).  It would be extremely useful for us to post that information for PlasmaPy's subpackages as well.  
Please let me know if you think we should change any of the subpackage statuses that I tentatively put in, since I wasn't quite sure what to put for `classes` since we'll be making major changes as will be described in PLEP 7 and for `diagnostics` since we're just now beginning to develop it and it's mostly in the planning stage.  I was thinking that we should err on the side of saying that a subpackage is …

Create subpackage stability table in docs

---

plasmapy/physics/distribution.py

This closes some un-closed brackets, which was making my editor render the whole file like a string (in only one text colour), which was really annoying!

Fix brackets in distribution docstrings

---

setup.cfg

For some odd reason, the comment section in `setup.cfg` for `pycodestyle` is causing an error in my linter. I'm guessing that it's because the apostrophe wasn't ascii, which I've now changed.
```
[Linter] Error running pycodestyle Error: Traceback (most recent call last):
File "/Users/dstansby/miniconda3/bin/pycodestyle", line 11, in <module>
sys.exit(_main())
File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pycodestyle.py", line 2302, in _main
style_guide = StyleGuide(parse_argv=True)
File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pycodestyle.py", line 1966, in __init__
arglist, parse_argv, config_file, parser)
File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pycodestyle.py", line 2259, in process_options
options = read_config(options, args, arglist, …
```

Fix pycodestyle error

---

plasmapy/examples/plot_distribution.py
plasmapy/physics/__init__.py
plasmapy/physics/distribution.py
plasmapy/physics/tests/test_distribution.py

Supersedes #451 
Closes #392 
Our speed distributions are all wrong. The 1D Maxwellian speed distribution is actually the 3D distribution, so that is being renamed. I'm also adding the correct form for the 1D distribution and adding 2D distributions.

Maxwellian 3D speed fixes

---

plasmapy/utils/checks.py

Can we get away with this?  It seemed to work much faster, cut the run time of my whole script by a factor of 3.
Hmm, using timeit shows a speedup from 4.019467848003842 to 1.8043721090070903 .... which I guess is kind of close to a factor of 3.
Closes #465

tried "try .to" approach in _check_relativistic to avoid .si

---

docs/plasma/index.rst
docs/plasma/sources.rst
plasmapy/classes/__init__.py
plasmapy/classes/plasma_base.py
plasmapy/classes/plasma_factory.py
plasmapy/classes/sources/__init__.py
plasmapy/classes/sources/plasma3d.py
plasmapy/classes/sources/plasmablob.py
plasmapy/classes/tests/test_Plasma.py
plasmapy/classes/tests/test_Species.py
plasmapy/classes/tests/test_plasma_base.py
plasmapy/classes/tests/test_plasma_factory.py
plasmapy/utils/datatype_factory_base.py
plasmapy/utils/tests/test_datatype_factory_base.py

We can now instantiate the expected plasma subclass based on input keyword arguments.
```python
>>> import astropy.units as u
>>> import numpy as np
>>> import plasmapy.classes
>>> T_e = 25 * 15e3 * u.K
>>> n_e = 1e26 * u.cm ** -3
>>> Z = 2.0
>>> particle = 'p'
>>> blob = plasmapy.classes.Plasma(T_e=T_e,
...                                n_e=n_e,
...                                Z=Z,
...                                particle=particle)
>>> type(blob)
plasmapy.classes.sources.plasmablob.PlasmaBlob
>>> three_dims = plasmapy.classes.Plasma(domain_x=np.linspace(0, 1, 3) * u.m,
...                                      domain_y=np.linspace(0, 1, 3) * u.m,
...                                      domain_z=np.linspace(0, 1, 3) * u.m)
>>> type(three_dims) …
```

[WIP] Basic plasma factory implementation

---

plasmapy/physics/parameters.py
plasmapy/physics/tests/test_parameters.py

First baby step of progress towards issue #469, this one is focused solely on the gyroradius function.
Gyroradius seemed to have trouble due to its unique feature, in which it will accept a T_i input, or a Vperp input, but not both.  I put in some conditional statements to hopefully extend this behavior to numpy array Quantities.  
The main new behavior that I have tried to test for and achieve is:
- If only Ti is input and is a no-nan-Qarray, function should work (result is a Qarray calculated with Ti)
- If only Vperp is input and is a no-nan-Qarray, function should work (result is a Qarray calculated with Vperp)
- If both Vperp and Ti are input and are both Qarray, but with nans in each array such that for each element there is exactly 1 nan, function should work (result is a Qarray …

Modify gyroradius function to work with numpy array Quantities

---

plasmapy/physics/transport/collisions.py
plasmapy/physics/transport/tests/test_collisions.py

Similar to before, the goal this time is to make it so that collision_frequency and friends work with len>1 array Quantities, such as `T_e = np.array([1, 2, 3]) * u.eV`.
Working on issue #469, hopefully this is the last PR needed that will touch the functions themselves.  Muahaha, can calculate so many numbers now! 
Still will probably need another PR to close the issue, just to add tests for array-capability to all the various functions that were already passing.  Aaaand probably Braginskii should be figured out to handle arrays, but... let's make that a separate issue. I'm not sure if it will be vectorize-able in all cases,  I think it will be.

Numpy array operations in collision_frequency 's

---

plasmapy/atomic/particle_input.py
plasmapy/atomic/tests/test_particle_input.py
plasmapy/physics/transport/collisions.py

Addresses #336.
I've used `@particle_input` decorator wherever possible on functions in `collisions.py`. Also, replaced `TypeError` with a `ValueError` in `particle_input` when number of input elements do not match expected elements in the tuple passed, since it seems more fitting. :)

Use @particle_input decorator on functions in collisions.py

---

plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/tests/test_langmuir.py

Some functions and lines of code in [langmuir.py](https://github.com/PlasmaPy/PlasmaPy/blob/9ec848cda75c997b2acb020a3fdcfa5a8a39004f/plasmapy/diagnostics/langmuir.py) were untested. So, I've added several more tests to cover up what has been missing.

Increase coverage in langmuir.py

---

plasmapy/physics/parameters.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/transport/collisions.py
plasmapy/physics/transport/tests/test_collisions.py
plasmapy/utils/__init__.py
plasmapy/utils/pytest_helpers.py

Working on issue #469 .  This adds tests to the functions in collisions.py and parameters.py to verify that they can work with nparray Quantities.
The main thing with this one is the addition of a helper function in the utils/pytest_helpers module, assert_can_handle_nparray, which I then used all over test_collision and test_parameters. This new test does test with multi-dimensional nparray Quantities. Comments and improvements welcome!
I was hoping this was going to close the issue, but under the cold light of all the new testing, I think there are a handful more issues, although they are mostly in non-default-argument nooks and crannies. For the time being I just added todo comments. I can address them as part of this pull request if you guys would like, or do a new one.

Numpy array tests

---

plasmapy/classes/plasma_base.py

I didn't realize a better idea would be to raise a `NotImplementedError` instead of just `pass` in our currently unimplemented properties in `BasePlasma` and `GenericPlasma`.
This would also help us increase code coverage since we mention to [skip such lines in coveragerc](https://github.com/PlasmaPy/PlasmaPy/blob/23b55eb569a1c7fbbf192827d889bf2d9a69b678/plasmapy/tests/coveragerc#L12).
(By the way, `coverage` at the moment still doesn't seem to read `exclude_lines` from our `coveragerc`. I made a *not-so-good* workaround in ritiek/PlasmaPy#4 to make it read them. I'll make a PR if it seems okay to you).

Raise `NotImplementedError` in `BasePlasma` and `GenericPlasma`

---

plasmapy/atomic/tests/test_atomic.py
plasmapy/atomic/tests/test_nuclear.py
plasmapy/atomic/tests/test_particle_class.py
plasmapy/physics/tests/test_parameters.py
plasmapy/physics/transport/collisions.py
plasmapy/physics/transport/tests/test_collisions.py

This PR just adds some more tests to cover a few lines we've been missing out in our codebase.

[WIP] Add a few more tests to improve our test coverage

---

plasmapy/atomic/particle_class.py
plasmapy/atomic/tests/test_particle_class.py

This makes `Particle(particle) == Particle(Particle(particle))` while making sure that `Particle(particle) is not Particle(Particle(particle))`. 
Closes #486, using the suggestion made by @colbych.  See #486 and the commit log for details.

Make Particle(particle) == Particle(Particle(particle))

---

plasmapy/atomic/particle_class.py
plasmapy/atomic/tests/test_particle_class.py

These methods take a `Particle` object and run `__init__` again for the same element/isotope but for a different charge.  The `Particle.ionize` method will raise an `InvalidIonError` if a bare nucleus is attempted to be ionized.  The `recombine` method will issue a warning if the charge becomes negative; however, no exception will be raised in that case.
One behavior that I'm not certain about is both running `__init__` again and returning the new Particle instance.  We may wish to have just one behavior or the other.  If we have just the in-place re-initialization, then a disadvantage is that we would not be able to do comparisons like:
```Python
Particle("Fe 5+").recombine() == Particle("Fe 4+")
```
which require the new `Particle` instance to be returned.  I would appreciate more …

Implement ionize and recombine methods in Particle class

---

plasmapy/physics/distribution.py

Drifts aren't currently implemented in the code, so I've corrected the equations to take this into account.

Remove drifts from speed distribution equations

---

plasmapy/atomic/particle_input.py
plasmapy/atomic/tests/test_particle_input.py

Now `@particle_input` treats parameters with default value correctly. For example, this code now works:
```python
>>> from plasmapy.atomic import particle_input, Particle
>>> @particle_input
... def make_particle(particle: Particle = "He"):
...     return particle
>>> make_particle()
Particle("He")
```
This would otherwise give a `KeyError `when calling `make_particle()`:
```python
KeyError: 'particle'
```

Fix `@particle_input` for optional parameters

---

plasmapy/physics/tests/test_dimensionless.py
plasmapy/physics/tests/test_parameters.py
plasmapy/utils/checks.py

I think this was the intended default (the documentation says the default should be `True`), and I also think in general most functions should be able to handle nans. Also added a test to check that `beta` passes through nans fine.

Allow nans by default when checking unit input

---

plasmapy/atomic/particle_input.py
plasmapy/atomic/tests/test_particle_input.py

Addresses #530.
This PR adds the ability to use `Optional[Particle]` as an annotation which allows passing `None` as a Particle when a function is decorated by `@particle_input`.
```python
>>> from plasmapy.atomic import Particle, particle_input
>>> from typing import Optional
>>> @particle_input
... def take_optional_particle(particle: Optional[Particle]):
...     return particle
>>> take_optional_particle(None)
None
```
It also works with collections!
```python
>>> @particle_input
... def take_optional_particles(particles: (Optional[Particle], Particle)):
...     return particles
>>> take_optional_particles((None, 'He'))
(None, Particle("He"))

Use `Optional[Particle]` as an annotation

---

plasmapy/physics/tests/test_dimensionless.py

__quantum_theta__ is used on line 18 of test_dimensionless.py but it is never defined or imported.
[flake8](http://flake8.pycqa.org) testing of https://github.com/PlasmaPy/PlasmaPy on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./plasmapy/physics/tests/test_dimensionless.py:18:11: F821 undefined name 'quantum_theta'
float(quantum_theta(T, n))
^
1     F821 undefined name 'quantum_theta'
1
```
Hello, thanks for contributing to PlasmaPy!
If you're contributing changes to solve an issue tracked by GitHub, please add a phrase like:
Closes #404.
Where 404 is the number of the issue you're attempting to solve!
This makes all our lives easier by automatically closing the issue once your pull request is merged.
If you don't think your Pull …

Undefined name 'quantum_theta' in test_dimensionless.py

---

CITATION.rst
README.md
docs/about/citation.rst
plasmapy/__init__.py

This PR updates the citation information to reflect that we now have DOIs for our source code!  The DOI that points to our latest release that has been archived on Zenodo is:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1436011.svg)](https://doi.org/10.5281/zenodo.1436011)
I uploaded versions 0.1.0 and 0.1.1 and right now the about link points to 0.1.1.  
Closes #144.  Cross-references: #432 and #450

Add DOI and citation for source code

---

.coveragerc
plasmapy/atomic/parsing.py
plasmapy/atomic/particle_class.py
plasmapy/atomic/special_particles.py
plasmapy/classes/species.py
plasmapy/diagnostics/langmuir.py
plasmapy/import_helpers.py
plasmapy/transport/collisions.py
plasmapy/utils/pytest_helpers.py

This PR renames the comment that we use to specify that a line of code should not be counted in coverage reports (e.g., these lines will not be marked as tested or untested).  We now use Codecov instead of Coveralls, and this commit makes it more general that we ignore these lines for coverage tests rather than one of the above specific platforms.
Additionally, lines with `NotImplementedError` & `SyntaxError` are now no longer automatically ignored in coverage reports.

Change `# coveralls: ignore` to `# coverage: ignore`

---

plasmapy/atomic/atomic.py
plasmapy/atomic/nuclear.py
plasmapy/atomic/parsing.py
plasmapy/atomic/particle_class.py
plasmapy/atomic/symbols.py
plasmapy/atomic/tests/test_atomic.py
plasmapy/atomic/tests/test_nuclear.py
plasmapy/atomic/tests/test_particle_class.py

These are mostly PEP 8 fixes, with one variable in tests of nuclear.py being renamed since it was the same as a function name that was declared immediate after (discovered in mypy test results in #548).

Style and naming fixes in atomic subpackage

---

setup.cfg

Closes #515 
You can specifically ignore CouplingWarning, RelativityWarning in setup.cfg. After looking at a couple of different options, this seemed to be the easiest and best approach. This doesn't ignore all warnings as mentioned as an undesirable approach in #515 comments, it ONLY ignores the two mentioned warning types.
This brings the number of warnings when running tests down to 85. The remaining warnings are likely valid and should be investigated separately.

Issue #515: ignore CouplingWarning, RelativityWarning when running tests

---

plasmapy/physics/dielectric.py
plasmapy/physics/tests/test_dielectric.py

Closes #539. Names can of course probably be improved.

Namedtuples for dielectric 

---

.github/PULL_REQUEST_TEMPLATE.md
docs/about/credits.rst

I went through and added our recent contributors to the list of PlasmaPy authors that we have in the docs.  I also added [ORCID](https://orcid.org/) unique author identifier numbers and linked to GitHub usernames in this list.  For people whose name I was not able to find, I included GitHub usernames directly in the list.
I'm going to add some information to the contribution guide and maybe the PR template about the credits list.

Update list of PlasmaPy contributors in docs

---

.circleci/config.yml

I have applied BASH MAGIC to the doc builder, it'll save stdout and stderr to files - now I can:

[WIP] Cleaner warning display in CircleCI

---

docs/install.rst
plasmapy/__init__.py
plasmapy/classes/sources/openpmd_hdf5.py
plasmapy/diagnostics/langmuir.py
plasmapy/mathematics/mathematics.py
plasmapy/optional_deps.py
plasmapy/physics/quantum.py
setup.cfg
setup.py

Closes #522 later.
This implements what I started writing in PLEP8 (`pip install plasmapy[all]`) and solves the issue of what @dstansby [was referring to over here](https://github.com/PlasmaPy/PlasmaPy/pull/533#discussion_r220880549). This is going to be a breaking change (I'm not yet 100% sure I've got the implementation right), but I believe it's one we need to make (will explain later).
Checklist:

Second attempt at optional dependencies

---

.travis.yml
plasmapy/mathematics/tests/test_Fermi_integral.py
plasmapy/physics/tests/test_quantum.py
plasmapy/utils/pytest_helpers.py

I guess f8fac842ea1e074aba60d93f91fbdecf153987bf was broken in that it provided two mentions of astropy and this is causing conflicts.
Closes #589 and closes #587 too.

Follow up to astropy 3.1.1 unit bug fix

---

plasmapy/atomic/tests/test_atomic.py
plasmapy/atomic/tests/test_ionization_state.py
plasmapy/atomic/tests/test_ionization_states.py
plasmapy/atomic/tests/test_parsing.py
plasmapy/atomic/tests/test_particle_class.py
plasmapy/atomic/tests/test_particle_input.py
plasmapy/utils/checks.py

The message keyword argument is being deprecated from pytest.raises and may be removed instead of renamed.  This PR removes the use of message in our tests and checks.  Closes #601.

Remove message keyword argument in pytest.raises and pytest.warns

---

plasmapy/examples/plot_cold_plasma_tensor_elements.py

As the functions `cold_plasma_permittivity_SDP` and `cold_plasma_permittivity_LRP` moved from the `physics` to `physics.dielectric`

updated the cold plasma example to match latest API changes

---

plasmapy/transport/collisions.py
plasmapy/utils/checks.py

Follow up to #607. This makes sure that `NaN`s don't raise warnings when they go through `<` or `>` comparisons.

Allow NaNs through collisional_frequency without any warnings

---

plasmapy/atomic/particle_input.py
plasmapy/utils/checks.py

Decorators in Python 3.4+ do preserve signatures of their wrapped functions, but they still loose the ability to give parameter hints in IDEs.
For example, in PyCharm, the current `master` branch would yield parameter hints for `plasmapy.physics.parameters.Alfven_speed()` as:
But after defining the `__signature__` method for the wrapper function, the parameter hint now shows the arguments as:
The `__signature__` dunder has existed since Python 3.3 and is well documented in [PEP 362](https://www.python.org/dev/peps/pep-0362/).

Presevering function hints when decorated by `check_quantity` and `check_relativistic`

---

.zenodo.json

The purpose of the `.zenodo.json` file is to store the metadata needed by Zenodo for when we upload releases.  The metadata fields for a Zenodo upload should be automatically populated with the metadata spelled out in this file.  
Unfortunately, if we create a codemeta file (#622), a lot of the information will probably be duplicated so we may end up having inconsistencies.

Add file with metadata for Zenodo upload

---

CITATION.rst
INSTALL.md
docs/about/citation.rst
plasmapy/__init__.py
setup.cfg

I updated some of the information about PlasmaPy in `setup.cfg` and the information on how to cite PlasmaPy (in particular by saying that users should cite both the specific version of PlasmaPy, as well as our standard informational reference from last year).  
I also changed `plasmapy.__citation__` to be a list of DOI links, partially because the metadata for a Zenodo upload has the potential to change, and DOIs are the most robust identifiers.  Another possibility would be to include a link to the directions in our documentation, though this approach might be prone to bit rot when releases become old in case we ever reorganize our docs.

Metadata updates prior to version 0.2.0

---

README.md
docs/COMMUNICATION.rst
docs/CONTRIBUTING.rst
docs/index.rst

Improve feedbackability

---

docs/conf.py

Reverts PlasmaPy/PlasmaPy#644. It seems I misunderstood how Binder works, and we'd need to host the notebooks themselves within a github repo (see https://github.com/sphinx-gallery/sphinx-gallery/issues/503 ).

Revert "Add binder links to gallery notebooks"

---

ah_bootstrap.py
requirements/automated-documentation-tests.txt

This is an automated update of the astropy-helpers submodule to v3.2.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
Please note that since v3.2, ``sphinx-astropy`` needs to be explicitely listed as a dependency for building the documentation. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.2.1/CHANGES.rst). 
We also wanted to let you know that we have made new releases of the astropy package-template. You can find the latest [cookiecutter template here](https://github.com/astropy/package-template) or if you prefer you can find a [rendered version of the template here](https://github.com/astropy/package-template/tree/master). 
*This is intended to be helpful, but if …

Update astropy-helpers to v3.2.1

---

changelog/666.bugfix.rst
docs/development/testing_guide.rst
plasmapy/atomic/tests/test_particle_input.py
plasmapy/classes/sources/plasma3d.py
plasmapy/classes/sources/plasmablob.py
plasmapy/classes/sources/tests/test_openpmd_hdf5.py
plasmapy/mathematics/tests/test_dispersion.py
plasmapy/utils/tests/test_exceptions.py
plasmapy/utils/tests/test_pytest_helpers.py
setup.cfg

This PR fixes currently failing tests caused by the final deprecation in Pytest 5.1 of the `message` argument to `pytest.raises`, which we had unwisely muted along with all deprecation warnings in setup.cfg.
It also removes the same argument used in pytest.warns, which is slated for deprecation
in a future release.

Fix failing Pytests (deprecation of `raises(message=)`)

---

plasmapy/classes/sources/tests/test_plasmablob.py
plasmapy/transport/tests/test_collisions.py
plasmapy/transport/tests/test_transport.py
plasmapy/utils/pytest_helpers.py
setup.cfg

This replaces the aforementioned filters from setup.cfg with `with pytest.warns(CouplingWarning)` statements in tests where we expect them.
Files remaining to be cover:

Remove pytest filters for Coupling/RelatityWarning

---

changelog/668.breaking.rst
docs/simulation/particletracker.rst
plasmapy/examples/plot_particle_stepper.py
plasmapy/simulation/__init__.py

As pointed out by @diego7319, this example wasn't running in CI and wasn't being actively tested. I simplified it a bit to run faster along the way.

Enable particle_stepper to run under CI

---

.coveragerc
MANIFEST.in
docs/development/release_guide.rst
docs/development/testing_guide.rst
setup.cfg

Following up on #663.  Pretty insignificant changes.

Remove lingering astropy-helpers references

---

changelog/676.trivial.rst
codemeta.json
docs/development/release_guide.rst

This PR adds a [codemeta](https://codemeta.github.io/) JSON file that contains the metadata for our project.  I created this initially with their [online tool](https://codemeta.github.io/create/) (which I had to use Chrome for instead of Firefox; see https://github.com/codemeta/codemeta.github.io/issues/18), and added [terms from the codemeta schema](https://codemeta.github.io/terms/) to my heart's content.  Things I still need to do are:
Closes #622.

Creating a Codemeta JSON file

---

changelog/677.feature.rst
docs/about/credits.rst
docs/development/testing_guide.rst
plasmapy/classes/sources/tests/test_plasmablob.py
plasmapy/conftest.py
plasmapy/simulation/tests/test_particletracker.py

Adds the functionality requested in #673
Adds a marker and two options to pytest to speed up the test suite for routine tests. Slow tests can be marked with ```@pytest.mark.slow```. These tests can then be skipped with ```pytest --not-slow``` or exclusively executed with ```pytest --slow```.

Enable skipping of slow tests when using pytest from the command line

---

docs/development/release_guide.rst

[NumPy Enhancement Proposal (NEP) 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) includes suggested community guidelines for the support of old versions of Python and NumPy.  The idea behind NEP 29 is to provide predictability to when old packages stop being supported throughout the scientific Python ecosystem.  This pull request adapts these guidelines for PlasmaPy, in particular by including requirements for older versions of Astropy.  
The guidelines were adjusted to allow us some flexibility, since there may be situations where it would provide a much greater benefit to update sooner.  While we are still early in the development phase, we can get away with being less strict with supporting older versions of packages.  As we build up a user base and improve package …

Guidelines for supporting old versions of Python, NumPy, and Astropy

---

requirements/environment.yml

I just read and went through @StanczakDominik's [helpful guide](https://stanczakdominik.github.io/posts/simple-binder-usage-with-sphinx-gallery-through-jupytext/) and applied it to my own repository, but I noticed the binder badges are not showing at the [end of the tutorials](http://docs.plasmapy.org/en/stable/auto_examples/particle_stepper.html#sphx-glr-auto-examples-particle-stepper-py).
For my repository the solution was [bumping the version of sphinx that needed to be installed](https://github.com/HBClab/NiBetaSeries/blob/76f9779c17ef8069410eb6774ac0bb95b917cefd/setup.cfg#L66) since readthedocs by default installs `sphinx==1.8.5`.
I'm hoping this solution works for this repository as a way of saying thank you for providing that guide.
P.S., I do not know if it is necessary, but [I …

bump sphinx version (>2) to generate binder link

---

CITATION.rst
README.md
docs/about/credits.rst
docs/plasma/index.rst
plasmapy/__init__.py

This PR is updating our funding acknowledgements in a bunch of places in our documentation, plus `plasmapy.__citation__`.  This shouldn't be merged until October 1 (and after I finish the rest of the updates that need to be included).  Closes #679.

Update funding acknowledgements to reflect NSF CSSI grant

---

README.md

The "contributing to PlasmaPy" and "Code of Conduct" links were not pointing to the documentation on `docs.plasmapy.org`, so these old links have been updated to point to the relevant documentation pages.

Fix README documentation URLs

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR modifies the existing PR template to make it less wall-of-texty
and creates two buttons in the GitHub issue interface to let people
use separate templates for bug reports and feature requests.
It also comments out the existing template, so people still see it, but it
doesn't get posted in each PR.
This follows changes from
https://github.com/numba/numba/commit/8e308f84d0d5b3249b22d1c198d308ecea00b03b#diff-faa36bc26a21ed93c8de974753b71507
originally made by @stuartarchibald, whom I would like to thank here -
I was not previously aware that GitHub lets you do this kind of thing.
I borrowed some parts, as they were particularly well formulated.

Modify GitHub issue and PR templates

---

changelog/703.feature.rst
docs/about/credits.rst
plasmapy/classes/sources/plasma3d.py

Moved the itertools out of the mstat for loop, so it's calculated only once instead of being calculated for every mstat.
I tested that function with a timer; the changed function takes lesser time.
Thank you for contributing to PlasmaPy!  Please check out our development guide at:
http://docs.plasmapy.org/en/master/development/index.html
Here are a few things to keep in mind when making a pull request (PR).
* Tests and docstrings are required for new or changed functionality.
* Please take care to write helpful commit messages: https://chris.beams.io/posts/git-commit/
* As a PR nears completion, fellow developers will likely suggest changes
to be made before the PR is merged.
* Every pull request should include a changelog entry. Please see
`changelog/README.rst` for instructions.
* …

Tweaked add__magnetostatics

---

.codecov.yaml

As per SunPy's codecov configuration.

Set codecov failure threshold to 0.2%

---

changelog/705.breaking.rst
plasmapy/examples/plot_braginskii.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/tests/test_transport.py

I went through the `ClassicalTransport` class and made all of the methods into attributes by using the `@property` decorator.  Before, we had to do:
```Python
>>> classical_transport_instance.resistivity()
```
Now, we have to do:
```Python
>>> classical_transport_instance.resistivity
```
This pull request is brought to you by procrastinating working on my poster for the APS DPP meeting.

Turn ClassicalTransport methods into attributes

---

README.md
changelog/715.trivial.rst
docs/COMMUNICATION.rst

I'm updating our lists of communication channels in `README.md` and `docs/COMMUNICATION.rst`.  I updated us from the [old Jitsi room](https://meet.jit.si/plasmapy) to the [new Jitsi room](https://jitsi.riot.im/plasmapy) (which we changed because the old one was having more frequent technical difficulties), and changed it from biweekly to weekly community meetings.  I changed the Matrix link to be the one for openastronomy, and added the Discourse group.  I'm hoping to make it more clear that the Matrix channel is the first place to go to join the conversation.  I want to make the two files a bit more consistent with each other before merging.

Update communication channels

---

changelog/717.bugfix.rst
plasmapy/classes/sources/openpmd_hdf5.py

This PR fixes the [h5py warning](https://travis-ci.org/PlasmaPy/PlasmaPy/jobs/601759732#L5820) during the build.

Fix h5py file warning

---

requirements/requirements.txt

Remove parenthesis from `requirements.txt`.  Parenthesis are not consistent with [expected `requirements.txt` format](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) and cause issues with IDE interpreters.

Reformat 'requirements/requirements.txt'

---

changelog/729.doc.rst
plasmapy/utils/decorators/converter.py

Added docstrings to  plasmapy/utils/decorators/converter.py
angular_freq_to_hz method
#723

Add docstring to converter.py

---

changelog/731.trivial.rst
docs/development/testing_guide.rst
plasmapy/atomic/particle_class.py
plasmapy/atomic/tests/test_atomic.py
plasmapy/atomic/tests/test_particle_class.py
plasmapy/classes/sources/plasmablob.py
plasmapy/classes/sources/tests/test_plasmablob.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/collisions.py
plasmapy/formulary/dielectric.py
plasmapy/formulary/dimensionless.py
plasmapy/formulary/dispersionfunction.py
plasmapy/formulary/distribution.py
plasmapy/formulary/drifts.py
plasmapy/formulary/parameters.py
plasmapy/formulary/tests/test_collisions.py
plasmapy/formulary/tests/test_dielectric.py
plasmapy/formulary/tests/test_dispersion.py
plasmapy/formulary/tests/test_distribution.py
plasmapy/formulary/tests/test_magnetostatics.py
plasmapy/formulary/tests/test_parameters.py
plasmapy/formulary/tests/test_quantum.py
plasmapy/formulary/tests/test_relativity.py
plasmapy/formulary/tests/test_transport.py

This PR is mostly changing things like
```Python
<Quantity 2.2347906415316helpimtrappedinafloatingpointnumber8795234896735489 MeV>
```
to 
```Python
<Quantity 2.234... MeV>
```
so that differences at the *n*th decimal point due to refined values for fundamental constants don't mess up our doctests.

Use `...` in doctests to avoid floating point errors

---

changelog/751.trivial.rst
plasmapy/atomic/particle_class.py

I noticed that there are mutable arguments in `Particle.is_category` method, that should never be done.
Nice article about its 'features' --> https://florimond.dev/blog/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil/
So the mutable arguments are removed and replaced by `None` with handling by `become_set` similarly as it was before.

Remove mutable arguments from `Particle.is_category` method

---

changelog/773.trivial.rst
setup.cfg

The default settings for [isort](https://readthedocs.org/projects/isort/) (which sorts imports) and [black](https://black.readthedocs.io/en/stable/) (which strictly formats code) are not consistent with each other.  This sets the default settings for isort to be consistent with black.  If you run black and isort once, then switching between them afterward will lead to no changes.

Set isort settings to be consistent with black

---

changelog/780.doc.rst
docs/conf.py
plasmapy/simulation/particletracker.py
requirements/automated-documentation-tests.txt
setup.cfg
tox.ini

This is an attempt to fix the documentation build errors via `tox` as seen on CircleCI (see #778)
1. Removed duplicate docstrings for `ParticleTracker.kinetic_energy_history`.  Docstrings were defined both in the method definition and class level docstrings. 
1. Added dependency `sphinx <= 2.4.4`, since [`sphinx-automodapi` is currently failing with `sphinx` `v3.0.0`](https://github.com/astropy/sphinx-automodapi/issues/99).
Closes #778

Fix building of documentaiton using tox

---

changelog/755.feature.rst
plasmapy/particles/__init__.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

My goals here are:
- Create an abstract particle class
- Have `Particle` inherit from that abstract class
- Create a class for dimensionless particles that inherits from the abstract class
- Create a class for custom (dimensional) particles that inherits from the abstract class
Thus far it looks like the classes will include `mass` and `charge` attributes.  I'm also wondering about creating a composite particle class, which would have things like the root mean square charge which comes up occasionally in `plasmapy.formulary`.
Closes #447.  Related to #687.  This pull request is brought to you by proudly procrastinating doing other things.

Create abstract and custom classes for particles

---

.circleci/config.yml
.pre-commit-config.yaml
plasmapy/conftest.py
requirements/environment.yml
tox.ini

This PR:
* cleans tox.ini up a bit
* decreases the amount of test envs that get spun up when running simply `tox` to two from way too many
* adds isort to pre-commit hooks
* prevents conda from nagging us about lack of `pip` as a conda dep in `environment.yml`
* adds a neat PLASMAPY_PLOT_TEST env variable that can be set when running tests; this makes plots appear
* removes a reference to a sunpy tox-env we don't use from .circleci/config

Various administrative cleanups

---

changelog/841.doc.rst
docs/development/code_guide.rst

Add doc notes on benchmarks

---

docs/notebooks/langmuir_analysis.ipynb

The original "output-index" (1) for "nbsphinx-thumbnail" was pointing to an invalid MIME (a python dictionary instead of an image).  I changed the "output-index" to 2, so the first image is take as the thumbnail.
The documentation build failure was first noted by @StanczakDominik ([comment](https://github.com/PlasmaPy/PlasmaPy/pull/864#issuecomment-660463536)).

Fix npsphinx-thumbnail for ./docs/notebooks/langmuir_analysis.ipynb

---

.readthedocs.yml
plasmapy/formulary/distribution.py

This drops the pdf and epub builds from read the docs.  The current builders are not adequate enough to produce a readable product when the documentation is primarily designed for an html interface.  Additionally, it's too restrictive to have contributors design for both an html and pdf interface.  The documentation is still downloadable as an html zip file for offline use.
Also, remove the unpaired `\left` from the equation in `Maxwellian_speed_3D()` distribution function.

Drop pdf and epub form RTD doc build

---

changelog/898.feature.rst
requirements/automated-documentation-tests.txt
requirements/environment.yml
setup.cfg

`nbconvert` recently (9/10/2020) released `v6.0.0` which puts a dependency on `pygments` of `2.4.1 <= pygments < 3.0.0`.  However, RTD was still installing `pygments==2.3.1`.  This PR places a `pygments >= 2.4.1` dependency on our pkg.

[RTD build repair] set dependency pygments >= 2.4.1

---

azure-pipelines.yml
tox.ini

Xdist seems to be breaking the minimal conda test now; I'm temporarily removing it from just that test.
docstrings.

Remove xdist from minimal-conda test

---

plasmapy/diagnostics/tests/test_langmuir.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/diagnostics/thomson.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/magnetostatics.py
plasmapy/formulary/tests/test_collisions.py
plasmapy/formulary/tests/test_dielectric.py
plasmapy/formulary/tests/test_distribution.py
plasmapy/formulary/tests/test_parameters.py
plasmapy/formulary/tests/test_quantum.py
plasmapy/formulary/tests/test_transport.py
plasmapy/particles/decorators.py
plasmapy/particles/parsing.py
plasmapy/particles/tests/test_parsing.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/plasma/sources/plasmablob.py
plasmapy/plasma/sources/tests/test_plasmablob.py
plasmapy/simulation/tests/test_particletracker.py
plasmapy/utils/datatype_factory_base.py

We use [black](https://black.readthedocs.io/en/stable/) as a code formatter.  One of black's idiosyncrasies is that it sometimes puts multiple strings on one line if they'll both fit.  This PR mostly includes formatting fixes, such as the change below:
```Python
f"Unknown field orientation " f"'{self.field_orientation}'"   # two strings
f"Unknown field orientation '{self.field_orientation}'"  # replace with one string
```
I'm skipping `ionization_state.py`, etc. because I'm doing these fixes in #796 for those files.

Formatting fixes such as for when multiple strings are on one line

---

changelog/943.feature.rst
plasmapy/utils/decorators/__init__.py
plasmapy/utils/decorators/helpers.py
plasmapy/utils/decorators/tests/test_helpers.py

This is a simple decorator that allows for the programmatic prepending and/or appending of docstrings.  The original docstring is stored in a new `__original_doc__` attribute so it can still be retrieved.
This is useful in a scenario where you are overriding a method and the signature does not change, but you want add a little more info to the original docstring.

Decorator @modify_docstring

---

docs/notebooks/analysis/fit_functions.ipynb

Removing bold highlighting on a link in the fit function jupyter notebook.  This syntax works in local builds, but it appears RTD can not handle it.

Fit Function documentation patch

---

changelog/959.bugfix.rst
plasmapy/analysis/fit_functions.py
plasmapy/analysis/tests/test_fit_functions.py

This patch updates the `root_solve()` method of `plasmapy.analysis.fit_function.Linear` to handle the case where the slope is zero.  If this scenario occurs, then there are not finite roots and `(np.nan, np.nan)` is returned.

Patch root_solve() of fit function Linear()

---

changelog/934.doc.rst
plasmapy/formulary/parameters.py

For issue #915 
I have added some docstrings for `hall_parameter`. Copied `particle` docstring from existing docstring of `kappa_thermal_speed`. .Wasn't sure with what to do with `ion` and `particle`. Also added `hall_parameter` equation.

Added more description to hall_parameter signature in parameters.py

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This replaces the few straggling Riot chat links with the Element chat links (Basically those in the `.github` templates).  Change Log references were not touched.
Closes #938

Replace last Riot chat links with Element

---

changelog/962.breaking.rst
plasmapy/formulary/braginskii.py
plasmapy/formulary/collisions.py
plasmapy/formulary/parameters.py
plasmapy/formulary/tests/test_collisions.py

docstrings.
-| Part of Issue #931.
-| Renames the methods for Coulomb logarithms to "LS", "LS_min_I", "LS_full_I", "LS_clamp", "hyp_LS", "hyp_LS_max_I", and "hyp_LS_full_I". Underscores could be removed, "hyp" could be shortened to "H", and "I" could be changed to "i", "interp", or something similar.
-| Other minor updates.

Update naming of methods for Coulomb logarithms

---

plasmapy/particles/particle_class.py

The `nuclide_mass` attribute was in `Particle` twice.  Now it is in there once.  And the universe is now safe once again.  But...for how long?

Delete duplicate attribute in Particle class

---

changelog/1015.feature.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

To help `CustomParticle` and `DimensionlessParticle` behave a little bit more like `Particle`, I've added a `symbol` attribute to both of these.  This will give users the opportunity to define a symbol for particles that can be used in, say, plotting.

Add symbol attribute to CustomParticle and DimensionlessParticle

---

plasmapy/particles/tests/test_ionization_state.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/particles/tests/test_pickling.py

This PR adds new tests in `plasmapy.particles` regarding the pickling of particles.  Both `CustomParticle` and `DimensionlessParticle` instances can be pickled, but `Particle` instances (and objects that contain `Particle` instances) cannot.  Hence, most of these tests are marked as failing.  These tests should help later on when we address #1011 and make particles piclkealble.  (Yeah, I gave up on trying to spell that.)

Add mostly failing tests for pickling various objects in plasmapy.particles

---

changelog/1013.trivial.rst
docs/development/code_guide.rst
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/utils/decorators/checks.py

This pull request removes some `lambda` expressions from `plasmapy.particles` and `plasmapy.utils` because `lambda` expressions cannot be pickled. This partially address #1011.  However, more would need to be done in order to pickle `Particle` instances.  I left the `lambda` expressions in Langmuir stuff to avoid conflicts with #889.  
I propose a new tongue twister:
> I pickled a Particle of pickled PEP8ers.

Remove lambda functions

---

.github/workflows/testing.yml
tox.ini

~~Okay, admittedly I'm doing a little bit of a trick here: I'm limiting our existing envs to tests NOT marked as slow, and having the slow tests env run either slow or not slow tests. This is because~~
1. ~~the not-slow tests aren't going to impact the runtime of the slow tests that much;~~
2. ~~I don't know how to merge coverage reports from different action runs.~~
cc @pheuer 
Turns out codecov is smarter than that, and doing it the simplest way does work!
I ended up running "not slow" tests in most envs and only the "slow" tests in a single env. This limits the variance in runtimes a little.

Separate tox env for slow tests

---

changelog/1025.bugfix.rst
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/particles/tests/test_ionization_state.py

Fixes the failing test contributed by @StanczakDominik in #1021.  This makes `IonizationState` and `IonizationStateCollection` multiply iterable by using `yield`.

Use yield in __iter__ for IonizationState and IonizationStateCollection

---

changelog/951.doc.rst
plasmapy/formulary/quantum.py

Cleanup quantum.py docstrings

---

changelog/1036.trivial.rst
plasmapy/particles/parsing.py
plasmapy/particles/tests/test_parsing.py

Because I'd apparently rather play with unicode than make the increasingly wise life decision of going to bed, this pull request adds a few additional unicode particle aliases (e.g., we would be able to do `Particle("α")` for an alpha particle).  This could be useful for code and examples that will be read much more frequently than they are written.
At present a lot of the aliases are not documented.  I wonder if it would be helpful to have an ``aliases`` attribute to `Particle` that could list all of the valid aliases for the different particles.  I've also been thinking about ``unicode_symbol``, ``mathml``, and ``latex_str`` attributes too for different representations, but that's not for this PR.

Add some unicode particle aliases

---

changelog/1039.doc.rst
changelog/1039.trivial.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

The purpose of this PR is to ~~procrastinate doing other things~~ make the docstring for `Particle.is_category` consistent with the numpydoc standard.

Improve docstring for `Particle.is_category`

---

requirements/environment.yml
requirements/requirements.txt
setup.cfg
setup.py

This does two things:
1. temporarily applies a fix from https://github.com/pypa/pip/issues/7953#issuecomment-645133255 that allows `pip install --user --editable .` to work despite our pyproject.toml
2. Temporarily filters out warnings I've been getting related to https://github.com/pypa/packaging/issues/368.
I will keep an eye out and remove those as they stop being useful.
---
This also temporarily limits xarray to <0.17, which got a few hours ago and broke some of our new grids functionality. I ran https://github.com/PlasmaPy/PlasmaPy/actions/runs/598915034, for which CI passed yesterday, to verify that.

Temporary workarounds to pip install -e, packaging, xarray 0.17 issues

---

docs/conf.py

Using `pkg_resources.get_distribution("plasmapy")` severely limits the use of `make html` to build documentation.  This forces `plasmapy` to be installed when building docs versus just being in the python path.  The later is my preferred workflow since editable installs don't properly reflect version increments unless you reinstall (version is frozen in the EGG info).  I don't want to reinstall `plasmapy` for each documentation build.
https://github.com/PlasmaPy/PlasmaPy/blob/d9f3b197fbaca9e875ce5ea34e79ef7aeb020159/plasmapy/__init__.py#L37-L42

Put back import of __version__ from plasmapy in conf.py

---

changelog/1064.doc.rst
plasmapy/particles/atomic.py
plasmapy/particles/elements.py
plasmapy/particles/exceptions.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/isotopes.py
plasmapy/particles/nuclear.py
plasmapy/particles/parsing.py
plasmapy/particles/particle_class.py
plasmapy/particles/particle_collections.py
plasmapy/particles/serialization.py
plasmapy/particles/tests/test_atomic.py
plasmapy/particles/tests/test_particle_class.py
setup.cfg

Here are a bunch of more docstring fixes using my new favorite programming paradigm of PDD.¹  This time these are for `plasmapy.particles`, and were primarily inspired by running `pydocstyle`.  If this looks good, I'm okay with it being merged.
I also renamed two private dictionaries to be more PEP8ish: `_Elements` to `_elements` and `_Isotopes` to `_isotopes` (since these aren't classes).  
¹Procrastination-driven development.

Minor docstring fixes in particles

---

changelog/1072.feature.rst
plasmapy/plasma/grids.py
plasmapy/plasma/tests/test_grids.py

Properly documented this property

Made `is_uniform` a documented public attribute of AbstractGrid (closes #1071)

---

.github/labeler.yml
.github/workflows/labeler.yml

This adds https://github.com/actions/labeler. PRs that modify, say, plasmapy.particles should now automatically get the Particles label. I mirrored the existing labels; we can add more if needed.
I'm not 100% sure I've got the YAML set up properly, but I don't want to duplicate our labels on my own fork, so I'll have to adjust things here afterwards, anyway.
This PR is more of a "do we want this cool new thing that astropy's already trying out?". It's also a prelude to [finally adding the new contributor greeter bot, which can be done here in a basic form](https://github.com/PlasmaPy/PlasmaPy/new/master?filename=.github%2Fworkflows%2Fgreetings.yml&workflow_template=greetings) but I need to write some concise greetings first.

Add github action to automatically label PRs

---

CODEOWNERS

Following #1080 and as discussed at [yesterday's telecon](https://hackmd.io/y3davOJCR36wJMaQx2uiBg), here's the next automationy/refactory/etc change from #1059.
The [CODEOWNERS file](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) automatically asks the people mentioned  (@PlasmaPy/plasmapy-reviewers in general, @namurphy for Particles, @rocco8773 for Analysis/Diagnostics, @pheuer for proton radiography and myself for simulation in this first draft) for review on any newly opened, non-draft PR that modifies the files relevant files.
If you don't feel up to a review, you can just un-request yourself from the PR and someone else will always take over asap.
If any of you want to adjust the scope or opt out, I can of course do that for you, or …

First draft of CODEOWNERS file

---

.github/workflows/stale.yml

Closes #1092
Configured as per https://github.com/marketplace/actions/close-stale-issues.
I went with a yearly cutoff; after that, it'll comment that whoa, what's *not* going on here, and then it'll wait 2 more weeks and close the issue.
I do not think this locks discussion by default. If it does and it's just not documented, I'm just going to purge it.

Add stale bot for PR

---

.github/labeler.yml

This adds the following label automations:
* "Continuous integration" for anything in `.github`
* "Breaking" if there's a *.breaking.rst changelog entry
* "Documentation" limited to changes outside of `docs/notebooks`
* "Notebooks" complementary to that

Adjust labeler bot a bit

---

requirements/automated-documentation-tests.txt
requirements/environment.yml
setup.cfg

The recent release (2021-04-03) of `docutils` `v0.17.0` is causing issues with rendering on RTD, https://github.com/readthedocs/sphinx_rtd_theme/issues/1115.  We are specifically suffering from improper rendering of the sidebar, like https://github.com/rdswift/picard-docs/issues/96.  This PR sets the requirement `docutils < 0.17`.

Set docutils < 0.17 requirement

---

.github/workflows/linters.yml
.pre-commit-config.yaml
changelog/1106.trivial.rst

I got the following email this morning:
> pre-commit.ci has just passed 45,000 total runs!
>
> A few new features to announce today:
>
> - pre-commit.ci runs on a pull requests can be retriggered by commenting "pre-commit.ci run" instead of needing to open / close the PR
>
> - pre-commit.ci pull request autofix can now be disabled using `autofix_prs: false` -- a manual trigger of autofixing can be done by commenting "pre-commit.ci autofix".  for more information see: https://pre-commit.ci/#configuration-autofix_prs
>
> Anthony
I believe that solves the issues raised by @rocco8773, so let's get this in!
:)

Move pre-commit to pre-commit.ci, but disable autofix

---

changelog/1122.bugfix.rst
plasmapy/particles/elements.py
plasmapy/particles/tests/test_pickling.py

Closes #1011!
I do not fully understand why this works. But it seems that it does.
I was tinkering with slicing of IonizationState as part of #1059 (@namurphy I have actual arguments for that, and it's just the first of many travesties I want to do to IonizationState). I then somehow stumbled upon [this](https://docs.python.org/3/library/pickle.html#pickle-picklable:~:text=instances%20of%20such%20classes%20whose%20__dict__,section%20Pickling%20Class%20Instances%20for%20details), that got me thinking, I started looking at `Particle.__dict__`, noticed that `json.dumps(particle)` complains about `_PeriodicTable` contained within that `__dict__`, realized that's a namedtuple, thought hey, if namedtuples have trouble pickling (I don't understand why they would, that's my whole problem with …

Pickleable particles

---

changelog/1125.bugfix.rst
changelog/1125.trivial.rst
conftest.py
plasmapy/formulary/mathematics.py
plasmapy/formulary/tests/test_Chandrasekhar_G.py
requirements/environment.yml
requirements/extras.txt
requirements/tests.txt
setup.cfg
tox.ini

From #1059. This PR:
* adds tests for `Chandrasekhar_G` using [`hypothesis`](https://hypothesis.readthedocs.io/); **I would like to use this as an example for the tutorial I was supposed to give yesterday and will give at the telecon sometime soon.** So I suspect it will become clearer what it does then. I suspect we'll record that, too. Thus, this is reviewable, but with that caveat.
* turns `Chandrasekhar_G` into a numpy `ufunc` using `numba.vectorize`. This lets me handle the cases of very small and very large arguments cleanly, while allowing application to numpy arrays, without the annoyances of floating point numerical errors.
* uses https://github.com/numba/numba-scipy 's implementation of `erf`. It does so implicitly through numba's clever overload mechanisms. I just import the …

`hypothesis` tests; numba-based fixes for `Chandrasekhar_G`

---

changelog/1146.removal.rst
plasmapy/particles/particle_class.py

This PR removes `Particle.particle`, which had previously been deprecated in favor of `Particle.symbol` in #984.  This wasn't a widely used feature so it should be fine to have it emit a `FutureWarning` in 0.6.0, and then to remove it in the next release (0.7.0).

Remove deprecated Particle.particle

---

CHANGELOG.rst
README.md
changelog/1150.doc.rst
docs/about/vision_statement.rst
docs/conf.py
docs/development/code_guide.rst
docs/development/doc_guide.rst
docs/development/release_guide.rst
docs/notebooks/langmuir_samples/_generate_noisy.ipynb
docs/whatsnew/0.1.0.rst
docs/whatsnew/0.5.0.rst
licenses/PlasmaPy_LICENSE_preOct2017.md
plasmapy/plasma/plasma_base.py
pyproject.toml
tox.ini

This PR makes the changes in the code associated with default branch name change from `master` to `main` in our repositories.  GitHub has made it [easier to change the name of the default branch](https://github.com/github/renaming), which will make this change significantly smoother.  For example, pull requests to `master` will be automagically shifted to `main`.  One-time instructions will pop up for people coming to the repository in order to update clones on their local computers.
A few other packages have changed `master` → `main`, including Astropy and NumPy, so some of the changes are associated with that.  Two packages that have not yet done so are Sphinx and xarray, so I've left those links alone.  The change in `conf.py` from `master_doc` → `root_doc` comes from a [name change in …

Change code & docs to reflect a default branch named main

---

changelog/1183.doc.rst
plasmapy/formulary/parameters.py

Make the gyrofrequency function more general by removing the, originally included, indications that it might only be the gyrofrequency for the ions. Should close #1169 
docstrings.

Make gyrofrequency more general (not just ions)

---

changelog/1187.feature.rst
plasmapy/formulary/parameters.py
plasmapy/formulary/tests/test_parameters.py

This PR closes #1022 . The general behaviour of `gyroradius` is changed such that if one of the arguments (`T_i`, `Vperp`) is nan, and the other is not supplied, no error is raised, but nan is returned.
docstrings.

change behaviour of gyroradius when arguments are nan

---

changelog/1190.bugfix.rst
docs/about/credits.rst
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/diagnostics/thomson.py

In calculation of the spectral density, wavevector k_vec was not unit normalized. Proper normalization noticeably changes the resultant spectra.

Normalize wavevector in thomson.spectral_density()

---

changelog/1195.doc.rst
changelog/1195.trivial.rst
docs/conf.py
requirements/extras.txt
setup.cfg

Following [this discussion](https://github.com/PlasmaPy/PlasmaPy/pull/1156#discussion_r653073272) in #1156, this PR adds tox to `requirements/extras.txt` since it's used a lot in tests and such.

Add tox and remove pytest from extra requirements

---

changelog/1199.doc.rst
plasmapy/analysis/fit_functions.py

As mentioned in issue #1197, the resent release of `sphinx>=4.1.0` has caused the "Documentation" check to start failing.  I currently don't know what was changed in the `sphinx.ext.autodoc` functionality that created this issue, but I'm side stepping it by making `AbstractFitFunction.FitParamTuple` a property instead of a document attribute in the `__init__` method.
----
Closes #1197

Patch to address the "Documention" check failure

---

requirements/docs.txt
setup.cfg

This is a follow up to PR #1203 that bumped `docutils < 0.18` without properly considering PR #1107.  The current documentation has been built using `v0.17.1` and does not show the same issue reported in #1107 that was seen with `v0.17`.  Thus, I'm removing the upper bound for `docutils` and just excluding `v0.17` instead.

Disallow v0.17 of docutils

---

changelog/1210.removal.rst
plasmapy/formulary/parameters.py
plasmapy/formulary/tests/test_parameters.py

Closes #1170 
Waiting for feedback on initial changes. Will proceed further with tests.
docstrings.

Use more generalized keyword argument for gyroradius

---

changelog/1213.doc.rst
changelog/1213.trivial.rst
plasmapy/__init__.py

This PR makes two changes:
- Improvements to the docstring for `plasmapy.online_help`
- Have searches for `"quantity"` or `"quantities"` also be redirected to the help for `astropy.units`.  (This was already the case for `"unit"` and `"units"`.)
If this looks good, feel free to merge.

Minor changes to `plasmapy.online_help`

---

changelog/1205.doc.rst
docs/development/release_guide.rst

This PR includes some updates to the release guide prior to 0.7.0, including some minor formatting and reST changes.
The main purpose is to follow up on #1159 by changing `binder/requirements.txt` such that binder installs the version of PlasmaPy that was just released. Some points:
- I haven't tested this step yet, so we might need to update it after the release.
- There might be a better place to put this step in the release guide.
- This step could be automated, but even if so, we would want to keep a step where the binder notebooks are tested on both ``stable`` and the ``<major>.<minor>.x`` branch.

Update release guide including about binder requirements

---

docs/install.rst
requirements/install.txt
setup.cfg
tox.ini

as per report by @qudsiramiz 
at https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$162274090999775hfdGF:matrix.org?via=matrix.org
this is to accomodate the version available at google colab

Bump required tqdm down to 4.41.0

---

changelog/1216.feature.rst
docs/about/credits.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

As mentioned in discussion #1192, this contribution implements the necessary functions in CustomParticles to be used as keys in a dict.
docstrings.

Make CustomParticle usable as keys in a dict

---

changelog/1225.breaking.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

This PR changes the behavior oh the `__eq__` method of |Particle| in instances where an error would be raised if the compared object isn't a |Particle| or a valid str. This make the use of both |Particle| and |CustomParticle| more convenient when mixed in a list or as dict keys.
The only case where an error is raised is when the comparison is maid with an other |Particle| with se same symbol but different attributes.
docstrings.

Changed behavour of Particle.__eq__ to return false when used with other types

---

changelog/999999.trivial.rst
pyproject.toml

On #1223 I accidentally had the wrong pull request number for the changelog files, and noticed that the Giles towncrier check for the changelog entry still passed.  I looked up the documentation for [baldrick](https://baldrick.readthedocs.io/en/latest/plugins.html#towncrier-changelog-checker) and noticed that we were missing `verify_pr_number = true`, which I just added.

Have Giles verify PR number of changelog entries

---

requirements/docs.txt
setup.cfg

Closes #1230.  I hope.  
This is an attempt to fix problems with unordered bullet point lists, following discussion on.  I think doing docutils != 0.17 may have allowed docutils == 0.17.1 since 0.17 is a specific version which they did instead of 0.17.0.
See also https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 and https://github.com/readthedocs/sphinx_rtd_theme/pull/1185.

Specify docutils < 0.17

---

changelog/1238.doc.rst
plasmapy/formulary/dimensionless.py
plasmapy/formulary/drifts.py
plasmapy/formulary/ionization.py
plasmapy/formulary/parameters.py
plasmapy/formulary/quantum.py

Some quick changes to make sure that the reST links show up correctly in the docs for aliases.

Use full namespaces in docstrings for formulary aliases

---

plasmapy/formulary/parameters.py

Closes issue #1228
I searched for ":math:" in all files recursively in the "formulary" folder and went through all the results (100+), changing those referring to units.
I only found one change to make!
I checked by building the documentation again locally and saw the changes had the desired effect.

Make sure units are not in math mode in formulary docstrings (#1228)

---

.github/workflows/testing.yml

We started getting a test failure with Python 3.7 for astropy-dev because they bumped their minimum version of Python to 3.8.  This PR updates our CI tests for astropy-dev to be consistent with the requirements that Astropy will have for their next release.  
If we keep the test at Python 3.8 rather than Python 3.9, we'll get a helpful test failure when Astropy bumps their minimum version again.

Test development version of Astropy with Python 3.8

---

changelog/1257.doc.rst
docs/CODE_OF_CONDUCT.rst
docs/COMMUNICATION.rst
docs/about/citation.rst
docs/about/credits.rst
docs/about/vision_statement.rst
docs/common_links.rst
docs/development/code_guide.rst
docs/development/install_dev.rst
docs/development/release_guide.rst
docs/index.rst
docs/install.rst
docs/whatsnew/0.1.0.rst
docs/whatsnew/0.2.0.rst
docs/whatsnew/0.3.0.rst
plasmapy/formulary/collisions.py
plasmapy/formulary/parameters.py
plasmapy/particles/elements.py
plasmapy/plasma/sources/openpmd_hdf5.py

This PR makes a few quick corrections to web links that were either broken or were redirects.  One of the changes is for an old changelog entry that had linked to the issue it closed rather than the pull request number.  I found these out doing `make linkcheck` in `docs/` which was pretty handy.  (I made a reST update here and there while I was the area too.)

Fix some broken and redirected links

---

changelog/1268.doc.rst
docs/conf.py

According to the results posted in https://github.com/pygments/pygments/issues/1718, `"xcode"` is the only [pygments](https://pygments.org/) style that meets the [WCAG AA contrast standard](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) for web accessibility, apart from `"bw"` for black & white.  This PR changes our code formatting style to meet this accessibility standard.  
This should fix a bunch of the contrast errors that we get when [checking our docs against the WAVE accessibility tool](https://wave.webaim.org/report#/https://docs.plasmapy.org/en/latest/), though there are other style elements that are giving contrast errors too.

Adopt a code highlighting style with higher contrast

---

changelog/1272.doc.rst
docs/COMMUNICATION.rst
docs/common_links.rst

This is an update to our [communication page](https://docs.plasmapy.org/en/stable/COMMUNICATION.html), which has gotten a little out-of-date.  I'm attempting to future-proof it by referring readers to the corresponding page on PlasmaPy's website, which would also be worth updating.  Closes #1265.

Update communication page in docs

---

changelog/1280.trivial.1.rst
changelog/1280.trivial.2.rst
plasmapy/particles/ionization_state_collection.py
tox.ini

This PR adds [dlint](https://github.com/dlint-py/dlint) as one of our static analysis tools run in the linters environment for tox.  
It came up with one "stop using `eval`" error when running locally, so we should get that here too if the tests are running.
An alternative would be to use [bandit](https://bandit.readthedocs.io/en/latest/), but for the time being either one would be helpful.

Add security analysis linter

---

changelog/1281.trivial.1.rst
changelog/1281.trivial.2.rst
plasmapy/formulary/magnetostatics.py
plasmapy/formulary/parameters.py
plasmapy/formulary/radiation.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/utils/datatype_factory_base.py
plasmapy/utils/roman.py
setup.cfg
tox.ini

This PR:
- Adds the [flake8-use-fstring](https://github.com/MichaelKim0407/flake8-use-fstring) linter to `tox.ini`
- Removes the last of our `.format` and `% s` usage with f-strings.

Add linter to enforce usage of f-strings 

---

changelog/1283.trivial.1.rst
changelog/1283.trivial.2.rst
plasmapy/analysis/swept_langmuir/__init__.py
plasmapy/formulary/__init__.py
plasmapy/formulary/collisions.py
plasmapy/formulary/dimensionless.py
plasmapy/formulary/mathematics.py
plasmapy/formulary/tests/test_dimensionless.py
plasmapy/formulary/tests/test_distribution.py
plasmapy/formulary/tests/test_parameters.py
plasmapy/formulary/tests/test_quantum.py
plasmapy/particles/elements.py
plasmapy/particles/particle_class.py
plasmapy/particles/symbols.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/particles/tests/test_pickling.py
plasmapy/plasma/__init__.py
plasmapy/plasma/sources/__init__.py
plasmapy/plasma/sources/tests/test_plasma3d.py
plasmapy/simulation/particle_integrators.py
plasmapy/simulation/particletracker.py
plasmapy/utils/decorators/tests/test_validators.py
tox.ini

- Used [`unimport`](https://unimport.hakancelik.dev/) to remove unused import statements.  
- Modified a docstring example
- Added [flake8-absolute-import](https://github.com/bskinn/flake8-absolute-import) to the tox environment for linters
- Changed imports from relative to absolute
Something I don't understand yet is if these are compatible with pre-commit because they're done through flake8, or if we need to do something else to make it work with pre-commit.

Use flake8 checker for absolute imports and remove unused imports

---

.github/dependabot.yml
.github/labeler.yml
.github/workflows/labeler.yml
.github/workflows/stale.yml
.github/workflows/testing.yml
.github/workflows/weekly.yml
.pre-commit-config.yaml
.readthedocs.yml
changelog/1284.trivial.rst
pyproject.toml
requirements/environment.yml
tox.ini

This PR adds some pre-commit autoformatters for `.ini`, `.toml`, and `.yaml` files, and applies changes from those autoformatters ∀ files ∈PlasmaPy.
There don't seem to be many customization options, but autoformatters for all of these file types were available together so I'm guessing that they should all produce consistent styles.

Add and apply pre-commit hooks for `.ini`, `.toml`, and `.yaml` files

---

changelog/1334.trivial.rst
plasmapy/diagnostics/langmuir.py
requirements/environment.yml
requirements/install.txt
setup.cfg
tox.ini

The `nonposy` keyword was removed from matplotlib 3.5.0, and replaced with `nonpositive` which was added in matplotlib 3.3.0.  The easiest fix was to replace `nonposy` with `nonpositive` and bump the minimum version of matplotlib from 3.2.0 to 3.3.0.  
If we wanted to stay compatible with matplotlib 3.2.0, an alternative would be to put a `try`/`except` clause to catch the `TypeError`.  I don't prefer that approach because that fix is less permanent.

Bump minimum version of matplotlib and enable matplotlib 3.5.0

---

.github/workflows/fortnightly.yml
.github/workflows/monthly.yml
changelog/1333.trivial.rst
tox.ini

- I changed weekly tests to approximately fortnightly since that seemed a more appropriate cadence, and because it's an excuse to use the word "fortnightly".  
- I added tests of the development versions of matplotlib (inspired by #1330) and SciPy so that we can catch any API changes before official releases.

Update cron tests

---

changelog/1316.doc.rst
docs/development/testing_guide.rst

This PR expands the testing guide to include an example where we want to test a function both with and without a keyword argument so that we use argument unpacking. 
I still need to briefly mention what `*args` and `**kwargs` do in this example.

Discuss parametrization with argument unpacking in testing guide

---

.github/workflows/fortnightly.yml
tox.ini

Drops the failing scipy-dev cron job test from #1341.

Drop scipy-dev tests for now

---

changelog/1353.doc.rst
docs/common_links.rst
docs/conf.py
docs/development/doc_guide.rst
requirements/docs.txt
requirements/environment.yml
setup.cfg

This PR enables [sphinx-hoverxref](https://sphinx-hoverxref.readthedocs.io/en/latest/) for our docs.  From their documentation:
> sphinx-hoverxref is a Sphinx extension to show a floating window (tooltips or modal dialogues) on the cross references of the documentation embedding the content of the linked section on them. With sphinx-hoverxref, you don’t need to click a link to see what’s in there.
Many thanks to @StanczakDominik for bringing this up in the chat!

Enable sphinx-hoverxref for documentation

---

plasmapy/analysis/fit_functions.py
plasmapy/plasma/grids.py
plasmapy/plasma/sources/plasmablob.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/validators.py
setup.cfg

This is to fix some linter errors that showed up from an update of `pyflakes rst-docstrings`.  Closes #1355.

Fix linter errors

---

.github/workflows/testing.yml
changelog/1350.trivial.rst
tox.ini

What this does can be best seen in the [Checks tab](https://github.com/PlasmaPy/PlasmaPy/pull/1350/checks). I split tests into two groups, one happening after the other, and moved code coverage to a single run in the latter. If I got it right, the second stage should run conditionally on the first one (linters and one quick run of tests, except the slow ones), and codecov should only trigger once.

Two stages of tests

---

changelog/1359.doc.rst
docs/development/doc_guide.rst

We realized in our community meeting yesterday that we didn't discuss `__all__` at all in our contributor guide.  This adds two quick bullet points to the doc guide on module level docstrings and `__all__`, plus a few minor formatting changes.

Discuss module docstrings and `__all__` in documentation guide

---

changelog/1368.trivial.rst
plasmapy/particles/particle_class.py

Whilst working on #1366, I discovered that dealing with special cases in `Particle.__init__` was becoming a pain since the method is very long with lots of conditionals, etc.  This PR is to put the functionality in `Particle.__init__` into private methods to make it easier to understand and maintain.

Use extract method refactoring pattern on `Particle.__init__`

---

changelog/1360.trivial.rst
plasmapy/utils/tests/test_units_helpers.py
plasmapy/utils/units_helpers.py
requirements/environment.yml
requirements/install.txt
setup.cfg
tox.ini

This PR adds the module named `plasmapy.utils.units_helpers` (though we could change this) which contains a function `get_physical_type_dict`.  This function takes a `list` or `tuple` that is expected to contain `Quantity` instances and possibly other objects, and then create a `dict` that has `astropy.units.PhysicalType` instances as keys and the corresponding `Quantity` instances (or other objects with a physical type) as keys.  
I'm planning to use this for a `Normalizations` class, and it could also be used for perhaps a `UniformPlasma` class or our `PlasmaBlob` class.  An application could look vaguely like this:
```Python
class Normalizations:
def __init__(self, *args):  # allow users to input a bunch of quantities of different physical types in arbitrary order
physical_type_dict = …
```

Create helper function to sort an iterable into a `dict` with `PhysicalType` objects as keys

---

plasmapy/formulary/braginskii.py
plasmapy/formulary/mathematics.py
plasmapy/formulary/parameters.py
plasmapy/formulary/quantum.py
plasmapy/formulary/radiation.py

This follows up on #1375 with some more minor reST and other docstring fixes in a few files in `plasmapy.formulary`.  Again, I don't think that there's anything substantive here.

Minor docstring fixes in `plasmapy.formulary`

---

changelog/1361.doc.rst
docs/conf.py
requirements/docs.txt
requirements/environment.yml
setup.cfg

The default style for pygments has recently been updated to meet web accessibility standards for contrast (https://github.com/pygments/pygments/pull/1940).  This PR reverts #1287 to change the pygments style to `"default"` and sets the minimum version of pygments to 2.11.0.  This PR will need to wait to be merged until pygments 2.11.0 is officially released.
There are a few other styles at the top of the [pygments website](https://pygments.org/styles/) that meet the web accessibility standard for contrast.  Among these, I like `"default"` the best, but we do have a few alternatives if we'd prefer.

Revert pygments style to `"default"` and set minimum version of pygments to 2.11.0

---

changelog/1378.feature.rst
plasmapy/particles/particle_collections.py
plasmapy/particles/tests/test_particle_collections.py

This PR adds the `ParticleList.is_category` method that is analogous to `Particle.is_category`.  I realized the need for this while figuring out how to make `@particle_input` work with `ParticleList` instances.
Currently the docstring for the method refers to the `Particle.is_category` docstring.  I did this to make the docstring for `Particle.is_category` the definitive one, and to avoid the possibility that the docstrings for the two methods could diverge.  I'm open to including the parameters list in the docstring of the new method if preferred.

Add `ParticleList.is_category`

---

changelog/1399.trivial.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

This PR changes `CustomParticle` and `DimensionlessParticle` so that they no longer emit a warning when they are instantiated without either a charge or a mass.  The warnings had stated that that particular attribute was not provided and thus was given a value of `numpy.nan` in the appropriate units.
I'm removing this since it's not uncommon for me to only need to define either a mass or a charge, and the warnings are getting kind of annoying.  If the warnings do end up being helpful to others, though, I'm open to keeping them.  
I'm not quite sure what sort of changelog entry makes the most sense, but I'm going to go with `trivial` for now.

Remove warnings from `CustomParticle` and `DimensionlessParticle` for `nan` attributes

---

docs/conf.py

Refactor the if-else clause that defines the `release`, `version`, and `revision` configuration variables in `docs/conf.py`.
Closes #1406.

[Docs] Refactor `version`, `release`, and `revision` definitions in `conf.py`

---

changelog/1430.bugfix.rst
changelog/1430.trivial.rst
plasmapy/formulary/parameters.py
plasmapy/formulary/tests/test_parameters.py

This PR focuses on...
1. Updating the conditional for generating the `PlasmaPyFutureWarning` to resolve issue #1420.
2. Refactors the tests for `gyroradius` by combining the existing test function and test class into one test class, as well as parametrizing all tests.
closes #1420

Update `gyroradius` FutureWarning and tests

---

plasmapy/formulary/parameters.py

After merging PR #1444 we started getting an `ImportError` from `plasampy.formulary`.  This was coming from the import of `from plasmapy.formulary.parameters import *`.  The reason for this is two fold: (1) the `plasmapy.formulary.dimensionless` pkg existed before the functionality migration done in PR #1444 and thus it contained functionality not originally contained in `plasmapy.formulary.parameters`; and (2) the auto-population scheme of `__all__`, `__aliases__`, and `__lite_funcs__` was adding the names of these "non-parameters" functions to the `parameters` dunders.  This resulted in `from plasmapy.formulary.parameters import *` trying to import functionality not contained in the namespace.

Patch for #1444

---

changelog/1453.feature.rst
changelog/1453.removal.rst
docs/development/testing_guide.rst
docs/formulary/index.rst
docs/formulary/misc.rst
docs/formulary/speeds.rst
docs/plasmapy_sphinx/automodsumm/core.py
plasmapy/formulary/__init__.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/dimensionless.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/misc.py
plasmapy/formulary/parameters.py
plasmapy/formulary/speeds.py
plasmapy/formulary/tests/test_dimensionless.py
plasmapy/formulary/tests/test_frequencies.py
plasmapy/formulary/tests/test_lengths.py
plasmapy/formulary/tests/test_misc.py
plasmapy/formulary/tests/test_parameters.py
plasmapy/formulary/tests/test_speeds.py
plasmapy/plasma/sources/plasmablob.py

This PR moves miscellaneous plasma parameters from `plasmapy.formulary.parameters` to `plasmapy.formulary.misc` in accordance with issue #1433.

Create and populate `plasmapy.formulary.misc`

---

changelog/1456.breaking.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

In a lot of functions in `plasmapy.particles`, we've made the `Z` and `mass_numb` parameters keyword-only because of the potential for errors.  This PR makes these parameters keyword-only for `Particle` also.  This is a breaking change.

Make `Z` and `mass_numb` parameters for `Particle` keyword-only

---

changelog/1471.bugfix.rst
plasmapy/formulary/__init__.py
plasmapy/formulary/misc.py

This is patch for PR #1453 .
1. In `plasmapy.formulary.misc` add `__aliases__` to `__all__`.
2. Expose `plasmapy.formulary.misc` to the `plasmapy.formulary` name space
For some reason the checks for PR #1453 passed with these issues.  These issues only came to my attention when I started seeing documentation build errors for PR #1252 .

Patch for PR #1453 (`plasmapy.formulary.misc`)

---

changelog/1455.doc.rst
plasmapy/particles/_parsing.py
plasmapy/particles/particle_class.py

This PR updates the docstrings for `plasmapy.particles.particle_class.molecule` and associated private functions.  In particular, this expands/edits some parameter descriptions, and makes a few reST edits.  
I also adopted a minor refactoring suggested by Sourcery, which was to explicitly raise an exception from another exception.

Update docstring for `molecule`

---

changelog/1473.feature.rst
plasmapy/dispersion/dispersionfunction.py
plasmapy/dispersion/tests/test_dispersion.py

Creates lite versions of the plasma dispersion function and its derivative.
This just eliminates input validation: future work necessary to cythonize these functions.
Necessary for #974

Lite-Functions Ep. 3 | plasma dispersion functions

---

changelog/1488.doc.1.rst
changelog/1488.doc.2.rst
docs/conf.py
requirements/docs.txt
setup.cfg

Currently documented signatures use the long form name like `plasmapy.particles.particle_class.Particle` instead of the short form like `Particle`.  While I can see the benefit of the long form, I do think it makes the signature unreadable very quick with the addition of multiple type hints.  This PR sets the [sphinx configuration variable `autodoc_typehints_format="short"`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints_format), which will generate the short form type hints.  This also becomes the default behavior in `sphinx>=5.0`.   All the `intersphinx` linking still works as expected.
Long form example:
Short form example:
This also requires `sphinx>=4.4`.

Use short type hints in documented signatures

---

changelog/1494.trivial.rst
plasmapy/formulary/__init__.py
plasmapy/particles/_factory.py
plasmapy/particles/particle_collections.py
plasmapy/plasma/grids.py
plasmapy/utils/decorators/checks.py

This PR implements a recommended refactoring that I learned recently.  Instead of:
```Python
try:
...
except ValueError:
pass
```
we can do:
```Python
with contextlib.suppress(ValueError):
...
```
However, the main purpose of this is to test the pull request labeler in #1492.

Use `contextlib.suppress` to suppress exceptions instead of `try` & `except`

---

.pre-commit-config.yaml
changelog/1504.trivial.rst

The version of `black` that we currently use in `pre-commit` has started having an issue with the newest release of `click`.  This PR temporarily sets a maximum requirement for `click`, since updating to the next version of `black` is going to be really involved (#1503).  When we update to the next version of `black` in `pre-commit`, we should be able to drop this maximum requirement.

Set maximum requirement for `click` in `pre-commit` configuration

---

.pre-commit-config.yaml

I've been getting occasional false positives for the `check-merge-conflict` pre-commit hook.  In particular, after I try to resolve conflicts in a `.rst` file, the `=======` that is used for headings gets treated as a separator line from a merge conflict.  
This PR stops the `check-merge-conflict` hook from being run on `.rst` files (using a Python regular expression to denote file type) to avoid these false positives.

Stop using `check-merge-conflicts` pre-commit hook for `.rst` files

---

changelog/1512.bugfix.rst
plasmapy/__init__.py

This PR adds the `analysis` and `dispersion` subpackages to `plasmapy.__init__`, including in the `__all__` dunder.

Add `analysis` and `dispersion` to `plasmapy.__init__`

---

changelog/1514.feature.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

Currently, if you have a `p = Particle("Li")` and try to `.ionize()` it, you get a `ChargeError` complaining about the charge not being specified.
However, I think a sane default here is to assume `p` is meant as a neutral atom, in which case  we can safely assume the charge number is zero. Whatcha think?
docstrings.

Allow `Particle("Li").ionize()`, assuming meant as neutral atom

---

setup.cfg

The [flake8-rst-docstrings](https://github.com/peterjc/flake8-rst-docstrings) extension to flake8 checks a bunch of things regarding reStructuredText (reST) formatting in our docstrings, including about whether or not there are any undefined [roles](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html) or [directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html).
Unfortunately, it appears to only know the roles/directives from basic reST, and not the roles/directives defined by Sphinx which are a superset of those from basic reST.  This means that we have to specify which reST role/directives are allowed in docstrings via the appropriate variables in `setup.cfg` (`rst-roles` and `rst-directives`).  This PR adds most of the remaining …

Specify allowed reST/Sphinx roles & directives for flake8-rst-docstrings

---

.github/workflows/fortnightly.yml
.github/workflows/testing.yml
changelog/1501.trivial.rst
plasmapy/tests/test_import.py

This PR adds a simple test in our test suite that runs ``import plasmapy`` to make sure that it can be imported.
I decided to include this as a test rather than as a GitHub Action so that:
- We are able to test this on platforms besides GitHub, including locally
- We are able to straightforwardly test this on multiple operating systems and versions of Python.
We also currently have a [tox environment](https://github.com/PlasmaPy/PlasmaPy/blob/9e4cc617e56ce01fea1a5e356d25c659627b208c/tox.ini#L122) that can be used to perform this test.

Test that ``plasmapy`` can be imported

---

.github/workflows/testing.yml
changelog/1530.doc.rst
changelog/1530.trivial.rst
docs/development/testing_guide.rst
tox.ini

This PR follows up on #1493 by adding a GitHub Action for [codespell](https://github.com/codespell-project/codespell).  This is very similar to the GA added in https://github.com/HinodeXRT/xrtpy/pull/37.  
Codespell works by looking for common misspellings rather than by looking for words that aren't in a dictionary, so it has a low (but nonzero) number of false positives.  I was hesitant about including codespell in our pre-commit configuration because of the occasional false positives and the need for human intervention, but I think a GA would be appropriate so long as any failure messages describe what to do to fix any false positives.

Add GitHub Action for codespell

---

docs/conf.py
docs/development/install_dev.rst

Prior to this PR, the html anchors used for each reference in our bibliography was of a form like `id20`, where the number corresponds to the number in the bibliography.  While links created using roles like `:cite:p:` and `:cite:t:` will be updated automatically, external links that point to one bibliography entry at one point in time are not guaranteed to point to that same entry at a later time (for example, if more bibliography entries got added).  This is also true for hard links to bibliography entries that were included in Markdown cells in our example notebooks.
This PR sets the html anchors to the citation key, with colons replaced by dashes.  This provides an extra level of stability, as the anchors won't change as long as the citation key doesn't change.  If a citation key does …

Base bibliography html anchors on citation key

---

changelog/1546.bugfix.rst
plasmapy/formulary/collisions.py

Changed from calling collision_frequency using n_e to calling with n_i, to reflect calculating for electron-ion collisions. This should fix the Z dependence to match e.g. Spitzer thermal conductivity.
Closes #1545

Fix to Z dependence in `fundamental_collision_freq`. 

---

changelog/1528.feature.rst
docs/common_links.rst
docs/glossary.rst
plasmapy/particles/__init__.py
plasmapy/particles/particle_collections.py

This pull request is to create `plasmapy.particles.particle_collections.ParticleListLike` as a typing construct that could be used in `particle_input`.  This PR follows up on #985.
Eventually I'm wondering if it would make sense to create `plasmapy.particles.typing` to contain things like this, but not in this PR.

Create `ParticleListLike` typing construct and "particle-list-like" term

---

changelog/1555.bugfix.rst
plasmapy/particles/_parsing.py

The PR incorporates regex matching into the `_parsing.extract_charge` to better handle white spaces.  The PR was prompted by issue #1553, where a string like `"Ar "` (with a trailing space) would result in a negatively charged ion `"Ar -1"`.  Additionally, the previous functionality couldn't handle scenarios when the isotope and charge info are separated by multiple spaces.
Closes #1553

Update `plasmapy.particles._parsing.extract_charge()` to better handle white spaces

---

changelog/1518.bugfix.rst
plasmapy/analysis/fit_functions.py

While going through #1509, I noticed that `kwargs` was accepted for `fit_functions.Linear.curve_fit`, but it wasn't used in the method when calling `linregress`.  This PR makes it so that the `kwargs` are passed to `linregress`. I also updated the reST link to be `scipy.stats.linregress`.
@rocco8773 — could you take a look at this to make sure the change is consistent with the intended behavior?  Thank you!

Update docs and the use of `kwargs` in `fit_functions.Linear.curve_fit`

---

changelog/1557.trivial.rst
plasmapy/diagnostics/charged_particle_radiography.py
plasmapy/formulary/collisions.py
plasmapy/plasma/grids.py
requirements/tests.txt
setup.cfg
tox.ini

First, this PR adds [flake8-implicit-str-concat](https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat), which checks for situations like the following (which are sometimes created when black reformats a file):
```Python
raise ValueError(
"original first line" "previously was the second line"
)
```
Second, this PR adds [flake8-mutable](https://github.com/ebeweber/flake8-mutable), which checks that functions do not have mutable default arguments, since that can lead to unexpected behavior.

Add `flake8-implicit-str-concat` and `flake8-mutable` extensions to linters

---

docs/about/citation.rst
plasmapy/plasma/sources/plasmablob.py

added  a final line in PlasmaPymodificado/docs/about/citation: "Note that a dev version of plasmapy should NOT be cited or used in published work."  as requested in issue #1536

Note that dev versions should not be used in published work

---

changelog/1572.bugfix.rst
plasmapy/formulary/__init__.py
plasmapy/particles/particle_collections.py

This PR exposes `plasmapy.formulary.radiation` and functions therein to the `plasmapy.formulary` namespace.  These were formerly missing.
Disclaimer: This PR may increase risk of exposure to `radiation`.

Expose `radation` to `formulary` namespace

---

requirements/docs.txt
setup.cfg

Recent release of `sphinx == 5.0` is incompatible with `plasmapy_sphinx`, so, for now, restricting the `sphinx` requirement to `< 5.0`

Set `sphinx` requirement to `>= 4.4, < 5.0`

---

.github/workflows/fortnightly.yml
.github/workflows/testing.yml

I noticed that the next version of `actions/setup-python` came out from a repo which still has dependabot installed.

Bump actions/setup-python from 3 to 4

---

docs/install.rst

This is important to add since the delay can make it seem like it's broken.

Note that `conda` can be slow in installation instructions

---

requirements/docs.txt
setup.cfg

Bump the minimum `sphinx-hoverxref` to `v1.1.1`.  This includes the more robust intersphinx mapping from https://github.com/readthedocs/sphinx-hoverxref/pull/171.

Bump requiremnt to `sphinx-hoverxref>=1.1.1`

---

docs/CODE_OF_CONDUCT.rst
docs/about/vision_statement.rst
docs/install.rst

I did a `make linkcheck` for the docs, and found a few errors & redirects.  This PR updates the corresponding hyperlinks.

Fix hyperlinks prior to 0.8.0 release

---

.pre-commit-config.yaml
plasmapy/__init__.py
plasmapy/diagnostics/thomson.py

This PR adds [pyupgrade](https://github.com/asottile/pyupgrade) as a pre-commit hook, which will automatically upgrade Python code to the specified minimum version. When we upgrade to a newer version of Python, pyupgrade make most of the changes with the next syntax automatically, and it's helpful for general code cleanup too. I'm tentatively excluding `plasmapy_sphinx` from this hook since that might make it harder to pull in changes that were originally elsewhere.
I also bumped the version for a few other pre-commit hooks like black, but there were no code changes as a result.
Closes #1438.

Add pre-commit configuration for pyupgrade and update other pre-commit hooks

---

changelog/1604.feature.rst
plasmapy/formulary/collisions.py
plasmapy/formulary/tests/test_collisions.py

The `impact_parameter` function in `collisions.py` can currently handle a 1D array of densities or temperatures, but not arrays of higher dimension. This PR changes line that handles 1D arrays to work for any shape array. 
`impact_parameter` is called by many of the other functions in the collisions module (for example, `collision_frequency'), so this change will also enable support for higher dimension arrays in some of those functions.

Modify impact_parameter() to work with N-D arrays

---

plasmapy/utils/calculator/__init__.py

This PR uses `pathlib` instead of `os` to create the path to the plasma calculator notebook.  Closes #1612.  I hope.

Use `pathlib` to get path to `plasma-calculator` notebook

---

docs/about/citation.rst

This PR fixes the version number of PlasmaPy that corresponds to the DOI from `v0.8.0` to `v0.8.1`, since I ran into some issues and released `v0.8.1` instead of `v0.8.0` (#1595, #1615, #1616).

Correct version in citation instructions

---

changelog/1626.doc.rst
docs/index.rst
docs/whatsnew/0.1.0.rst
docs/whatsnew/0.1.1.rst
docs/whatsnew/0.2.0.rst
pyproject.toml

This is an experiment to change a few towncrier and see if they work with their latest release.
This is a small subset of the changes we tried in #1623 (see [this comment](https://github.com/PlasmaPy/PlasmaPy/pull/1623#discussion_r914344860)).

Update towncrier settings

---

binder/requirements.txt

During the 0.8.1 release, I mistakenly included a change to `binder/requirements.txt` in #1621 that should not have gone back into `main`.  This PR will revert that change for `main`, so that binder will install PlasmaPy from the `main` branch of the repository and not `pip`.
This will fix part of #1635, but not all.

Install PlasmaPy from repo when launching notebooks with binder for `latest` docs 

---

plasmapy/formulary/tests/test_dielectric.py

There were a few tests in `test_dielectric.py` which were of the form
```Python
assert (
np.isclose(...), "message"
)
```
This was doing an `assert` on a non-empty `tuple`, which consequently always evaluated to `True`.  This PR adjusts the parentheses on the tests.

Fix assertions in tests that were always `True`

---

requirements/docs.txt
setup.cfg

The July 24th release of `sphinx` `v5.1` still has a few bugs, which are causing our documentation builds to fail.
Related issues and PRs are...
* PR https://github.com/sphinx-doc/sphinx/pull/10709
* Issue https://github.com/sphinx-doc/sphinx/issues/10705
* Comment https://github.com/sphinx-doc/sphinx/pull/9856#issuecomment-1193401531
This PR just nots `sphinx` `v5.1`, so hopefully we don't have to come back to update any dependencies.  Assuming everything is fixed in `v5.1.1`.

Restrict `sphinx != 5.1`

---

changelog/1654.trivial.rst
requirements/docs.txt
setup.cfg

Today (2022-07-29) `sphinx_gallery` released [version `0.11.0`](https://pypi.org/project/sphinx-gallery/0.11.0/).  The changes introduced in this version are negatively affecting the display of thumbnail galleries generated by `nbsphinx`, as such I'm restricting `sphinx_gallery` to `< 0.11.0`.
There are likely multiple changes that are sources to this issue, all of which are probably related to https://github.com/sphinx-gallery/sphinx-gallery/issues/905.  I do think the issue can be traced back to the change of the `.spx-glr-thubcontainer` style to a flex container.  **Instead of spending days trying to fix this my(our)selves.  I'm just restricting the `sphinx_gallery` version and hoping `nbsphinx` comes up with their own solution that we can adopt later.** :)
on the change to flex …

Restrict `sphinx_gallery < 0.11`

---

changelog/1651.doc.rst
docs/common_links.rst
docs/contributing/code_guide.rst
docs/contributing/install_dev.rst

In #1305, I updated the section that describes how to use pre-commit in the coding guide.  This PR takes that section and moves it to `install_dev.rst`, which I'm intending to update later.
I still have to...

Move & revise section on installing and using pre-commit

---

changelog/1650.doc.rst
docs/common_links.rst
docs/contributing/code_guide.rst
docs/contributing/doc_guide.rst

This PR is another spin-off from #1305 that focuses on best practices on naming variables and functions.  
This depends on a few things in #1649, and will need to be merged afterwards.

Add a section to the coding guide on naming best practices

---

tox.ini

07ee524db54416a8afc2c44123562238f79641d7 fixes #1646, but I'd still like to play around with this a little to see whether the three `build_docs` tox envs we have now couldn't be compressed into one.
The issue here is that `sphinxdev` is defined in `testenv` rather than in `testenv:build_docs`, and I think there's logic in `tox` that pulls the `commands` field from `all: {env:PYTEST_COMMAND} {posargs}` defined in  `testenv`.

Make docs build off sphinxdev actually build docs

---

changelog/README.rst
docs/contributing/code_guide.rst
docs/contributing/coding_guide.rst
docs/contributing/doc_guide.rst
docs/contributing/install_dev.rst
docs/contributing/release_guide.rst
docs/contributing/testing_guide.rst

Following [this comment](https://github.com/PlasmaPy/PlasmaPy/pull/1660#discussion_r938008046), I'm adding tables of contents to most of the pages in the contributor guide.  
I'm still playing around with where to place the tables of contents.  I'm wondering about either right at the top, or after the preamble text.

Add tables of contents to pages in contributor guide

---

docs/common_links.rst
plasmapy/analysis/fit_functions.py
plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/thomson.py
plasmapy/dispersion/dispersionfunction.py
plasmapy/formulary/dielectric.py
plasmapy/particles/particle_collections.py

This PR adds a substitution for `array_like` from NumPy, and applies it to docstrings.  The docstrings will now link to the entry in NumPy's glossary.

Add and apply substitution for `array_like`

---

changelog/1667.doc.rst
docs/common_links.rst
docs/contributing/doc_guide.rst

This PR updates the documentation guide by saying that the "Raises" section of a docstring should only include the exceptions raised by the function itself, and not exceptions that are raised by decorators.  The motivations are:
- Including the exceptions raised by decorators leads to a lot of repeated text, which should instead be uniquely defined in the docstring of the decorator.  
- The "Raises" section is one of the least useful sections of a docstring, so it should be correspondingly short.
- The "Raises" section of docstrings is one of the most likely to become outdated, at least in my experience.
- The numpydoc guidelines themselves say that this section should be used judiciously.

Update guidelines for "Parameters", "Raises", and "Warns" sections of docstrings

---

.pre-commit-config.yaml

This PR adds two pre-commit pygrep-hooks for reStructuredText files.  The two checks are:
- Making sure that reST directives end with two colons
- Checking for when inline code is next to normal text
I think errors like these would normally lead to doc build failures, but this will catch the issues sooner without having to wait for the doc build to complete.

Add pygrep-hooks to pre-commit

---

changelog/1673.doc.rst
docs/contributing/coding_guide.rst

Following up on #1672, this PR adds a guideline that says that functions should accept and return `nan` (not a number) values.  The reason is that sometimes we will work with arrays that have bad data that are flagged as `nan`, and still need to perform calculations on them.

Add coding guideline that functions should accept and return `numpy.nan` values

---

changelog/1674.doc.rst
changelog/README.rst
docs/common_links.rst

When a code object is deleted, any reST links to the old namespace will break.  While reST links in most of the documentation should be updated, the namespace in old changelog entries should be preserved.  This PR states how to change a reST link into an inline literal in old changelog entries.
An alternative would be to change all reST links in changelog entries into inline literals, which is what some other packages do (like Astropy, I think).  This would be less maintenance, but would make it more difficult for someone reading the changelog entry to access newly created features.

Add tip to changelog guide on updating broken reST links

---

CHANGELOG.rst
changelog/1671.trivial.rst
docs/whatsnew/0.6.0.rst
plasmapy/formulary/dimensionless.py
plasmapy/formulary/quantum.py
plasmapy/formulary/tests/test_dimensionless.py
plasmapy/formulary/tests/test_quantum.py

Resolves #1443 
This pull request moves the `quantum_theta` function definition into `quantum.py`, while still exposing the `dimensionless` namespace to the function to ensure no compatibility issues. Additionally, this pull request rewrites the test functions for `quantum_theta` to include a more thorough test suite
docstrings.

Move `quantum_theta` to `quantum.py`

---

setup.cfg

[Codespell v2.2.0](https://github.com/codespell-project/codespell/releases/tag/v2.2.0) is out! And it checks notebooks now, so this PR fixes [the new codespell failure on `main`](https://github.com/PlasmaPy/PlasmaPy/runs/7897035567?check_suite_focus=true).

Appease codespell, which now peeks into our notebooks

---

.github/labeler.yml

This PR makes some pretty straightforward updates to the GitHub Action that does labeling of pull requests.
- Added "Analysis" & Dispersion
- Added "Contributor Guide"
- Fixed typo for `plasmapy.simulation`

Update labeling of pull requests done by GitHub Actions

---

changelog/1685.bugfix.rst
plasmapy/diagnostics/tests/test_charged_particle_radiography.py

Closes #1458
This is an intermittent test failure, so I've just implemented several possible fixes.
Possible solutions implemented: 
1) Changed `np.copy()` to `copy.deepcopy()` to make sure deep copies are made of the dictionary `sim_results`
2) Updated the calculation of the array `od` to more closely match the method in `SyntheticRadiograph` (to which it is being comapred` 
3) Increased the tolerances by an order of magnitude in case numerical instability in the proton source (which is stochastic) is contributing (per @JaydenR2305 's suggestion)

Attempt to fix intermittent test failure in test_optical_density_histogram

---

changelog/1678.feature.1.rst
changelog/1678.feature.2.rst
changelog/1678.trivial.3.rst
plasmapy/formulary/collisions.py
plasmapy/formulary/quantum.py
plasmapy/formulary/tests/test_collisions.py
plasmapy/formulary/tests/test_quantum.py

Resolves #726 
Floating point errors associated with the `chemical_potential` function seem to have silently been corrected
docstrings.

Resurrect `chemical_potential` and associated functions

---

changelog/1694.trivial.rst
codemeta.json
requirements/install.txt
setup.cfg
tox.ini

This PR bumps the minimum version of NumPy to 1.20, primarily so that we can use type hint annotations from `numpy.typing`. This is in line with the schedule in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule):  
```
On Jun 21, 2022 drop support for NumPy 1.19 (initially released on Jun 20, 2020)
```
This is a spinoff of #1540.

Bump minimum NumPy version to 1.20.0

---

changelog/1540.trivial.rst

I was originally going to bump the minimum version of numpy in #1540, but I ended up splitting that off into its own pull request in #1694.  However, I forgot to delete the corresponding changelog entry in #1540.  This PR fixes that.

Delete redundant changelog entry

---

changelog/1697.breaking.rst
docs/whatsnew/0.7.0.rst
plasmapy/particles/__init__.py
plasmapy/particles/atomic.py
plasmapy/particles/ionization_state.py
plasmapy/particles/particle_collections.py
plasmapy/particles/tests/test_atomic.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/particles/tests/test_particle_collections.py

This PR moves `ionic_levels` from `plasmapy.particles.particle_collections` to `plasmapy.particles.atomic`. 
This PR is a spinoff of #1057.  As noted in [this commit](https://github.com/PlasmaPy/PlasmaPy/pull/1057/commits/59e146763c378f9865ca46b68a5c7cfd99ed594b), this was moved to avoid a circular import during the refactoring of `particle_input`.

Move `ionic_levels` to `plasmapy.particles.atomic`

---

changelog/1676.feature.rst
plasmapy/formulary/collisions.py
plasmapy/formulary/tests/test_collisions.py

Resolves PlasmaPy/hack-week#23
This pull request implements the four types of relaxation described on page 31 of the NRL formulary (see issue for screenshot)
For now, the class relies on a parameter called `coulomb_log`, which is the value of the Coulomb logarithm evaluated for the two interacting plasmas. This is because the current implementation of the Coulomb logarithm is limited to electron-electron interactions... In a future pull request I will be revisiting the Coulomb logarithm to include for a broader array of interactions
docstrings.

Add `CollisionFrequencies`

---

docs/contributing/coding_guide.rst

This is a quick follow-up PR to #1684 and #1690 that says that we should use `pathlib` to deal with paths instead of `os.path`.

Add note in coding guide that we should use `pathlib` instead of `os.path`

---

codemeta.json

A while back I ended up including our software requirements in our `codemeta.json` file.  Thinking more about it, having yet one more place to define requirements will significantly increase the chances that we'll forget to update the requirements everywhere where we need to.  Since we already have the requirements well-defined, I think it'd be better to not include the requirements in `codemeta.json`.  This PR removes the requirements from `codemeta.json`.

Remove software requirements from `codemeta.json`

---

docs/contributing/coding_guide.rst
docs/contributing/doc_guide.rst
docs/whatsnew/0.8.1.rst
plasmapy/diagnostics/thomson.py
plasmapy/formulary/lengths.py
plasmapy/particles/atomic.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_class.py
plasmapy/particles/particle_collections.py
plasmapy/utils/_units_helpers.py
plasmapy/utils/code_repr.py

This PR does a quick search and replace in `.py` files for `, keyword-only` → `, |keyword-only|`, where `|keyword-only|` is a substitution defined in `docs/common_links.rst` for ``` :term:`keyword-only` ```.  This PR also applies this substitution in a few `.rst` files. Linking this to the glossary entry will probably be mildly helpful for new users.

Apply `|keyword-only|` substitution in docstrings and reST files

---

changelog/1710.trivial.rst
docs/whatsnew/index.rst
requirements/docs.txt
setup.cfg

This pull request resolves an error in building documentation that seems to have arisen due to towncrier release 22.8.0.
docstrings.

Fix documentation build errors

---

changelog/1700.feature.1.rst
changelog/1700.feature.2.rst
docs/particles/particle_class.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py
setup.cfg

This PR moves `Particle.is_category` to `AbstractPhysicalParticle` so that it can be inherited by `CustomParticle` too.  It also adds an abstract property for `AbstractPhysicalParticle.categories` and then a concrete property for `CustomParticle.categories`, which will return an empty set if the `CustomParticle` charge is NaN...or `{"charged"}` or `{"uncharged"}` depending on if the charge is zero or not.  
I still need to add tests of `CustomParticle.is_category` and `CustomParticle.categories`, maybe update the documentation, and add a changelog entry.
This PR will be helpful for #1057.

Enable categorization of `CustomParticle` objects

---

changelog/1710.trivial.rst
changelog/1717.trivial.rst
docs/common_links.rst
requirements/docs.txt
setup.cfg

Following the release of `sphinx-changelog` 1.2.0 a few minutes ago, the issues we were getting with our documentation build from the new release of towncrier should be resolved now.  This PR bumps the minimum versions of `sphinx-changelog` and `towncrier` to the most recent releases.
Closes #1711. Follows up on #1710. See also https://github.com/OpenAstronomy/sphinx-changelog/pull/14.

Update requirements for `towncrier` and `sphinx-changelog`

---

.pre-commit-config.yaml
plasmapy/particles/tests/test_particle_class.py

This PR updates the version of `black` from 22.6.0 to 22.8.0,  `nbqa` from 1.3.1 to 1.4.0, and `pyupgrade` from 2.34.0 to 2.37.3.  There is one minor autoformatting fix from `pyupgrade`.

Update versions of `black`, `nbqa`, and `pyupgrade` used by `pre-commit`

---

changelog/1727.trivial.rst
requirements/install.txt
setup.cfg
tox.ini

CI failures regarding `numpy.asscalar` began popping up ~2 days ago, which correlates with numba release 0.56.2. This pull request declares a strict version of 0.56.0 to be used for the python 3.8 minimal environment
docstrings.

Bumping `astropy` dependency to `>= 5.0.1` due to `numpy.asscalar` deprecation

---

changelog/1720.breaking.rst
docs/notebooks/getting_started/particles.ipynb
docs/particles/particle_class.rst
plasmapy/particles/__init__.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

This PR follows a suggestion from @rocco8773 to move `AbstractPhysicalParticle.is_category.valid_categories` elsewhere.  I decided to put it in `plasmapy.particles.particle_class.valid_categories` as its own thing.
We could make it a `frozenset` pretty straightforwardly, but if someone wanted to add their own particle categories, they would not be able to do so, so I kept it as a `set`.
Closes #1719.

Move `valid_categories` to `particle_class.py`

---

plasmapy/analysis/fit_functions.py
plasmapy/formulary/dielectric.py
plasmapy/tests/test_requirements.py
plasmapy/utils/decorators/tests/test_lite_func.py

This is a quick PR to remove a few unused imports that were found and removed by [pycln](https://hadialqattan.github.io/pycln/#/).

Use `pycln` to remove unused imports

---

changelog/1721.breaking.rst
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/particles/tests/test_ionization_state.py

This PR changes `IonicLevel.__eq__`, `IonizationState.__eq__`, and `IonizationStateCollection.__eq__` so that an equality comparison with another type of object doesn't raise an exception but rather returns `False`.  This change is to better match the typical/expected behavior of Python objects.

Return `False` when comparing an ionization object to an object of a different type

---

tox.ini

This PR adds the `--showlocals` flag to our call to `pytest` in `tox.ini` in order to show local variables.  Here's example test output for a purposefully failing test:
```python
def test_that_fails():
x = 1
y = 2
z = 624
>       assert x == y
E       assert 1 == 2
x          = 1
y          = 2
z          = 624
plasmapy/tests/test_whatev.py:5: AssertionError
```
This can be really helpful for debugging, so I figured it'd be easier to have it on as the default.  The downside is that the test output is longer.

Show local variables in test failures

---

changelog/1749.trivial.rst
docs/conf.py
requirements/install.txt
requirements/tests.txt
setup.cfg
tox.ini

Move pytest dep from tests to install and update `nitpick_ignore_regex` to fix new doc build warnings

---

LICENSE.md

Edited `LICENSE.md` to match the text in https://choosealicense.com/licenses/bsd-3-clause.
The `LICENSE.md` file does not include the `BSD 3-Clause License` title which allows GitHub to recognise it as a 3-Clause BSD license.
|  **Before** | **After**  |
|---|---|
| ![image](https://user-images.githubusercontent.com/30223404/196804196-4c226da5-4ab1-47fd-9325-ed1ca6c9950c.png) | ![image](https://user-images.githubusercontent.com/30223404/196804118-b6b2847d-04a4-4870-a3e4-6f2fdfabbd61.png) |
This repository will now show up in GitHub search results as "BSD-3-Clause" licensed, instead of "Other" license, great for users looking for a permissively-licensed package.
nil

Change license header to match OSI format

---

CITATION.cff

`CITATION.cff` is a YAML file, but the `pretty-format-yaml` pre-commit hook does not get applied to it because it does not have the `.yml` or `.yaml` file extension. For this PR, I renamed `CITATION.cff` → `CITATION.yaml`, ran `pre-commit run --all-files`, and renamed `CITATION.yaml` → `CITATION.cff`.  I only made formatting changes to this file.

Use `pretty-format-yaml` pre-commit hook on `CITATION.cff`

---

docs/_static/css/plasmapy.css

Attempt to resolve #1784 
This updates our CSS to prevent href code styled blocks from freely wrapping.

Patch for href code wrapping in cells

---

plasmapy/analysis/tests/test_nullpoint.py
plasmapy/diagnostics/tests/test_charged_particle_radiography.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/formulary/tests/test_collisions.py
plasmapy/formulary/tests/test_quantum.py

This PR decorates a bunch of tests with `@pytest.mark.slow` so that they can be skipped with `pytest -m "not slow"`. 
I've been thinking of slow tests as lasting ≳ 0.1 s.  That's a pretty short cutoff, but given that we have a few thousand tests, the 0.1 s tests can really slow things down.  
There are a few longer tests in docstrings which I don't know how to mark, but we might want to do so.
On my computer, running `pytest -m slow` takes ∼32 s whereas running `pytest -m "not slow"` takes...well...I'll add it in when it finishes.  Edited to add: ∼143 s.
Also: some of the lite functions seem to take ∼0.1–0.5 seconds to run for the first time because they need to be jitted.

Mark tests as slow

---

changelog/1777.trivial.rst
plasmapy/analysis/swept_langmuir/helpers.py
plasmapy/plasma/sources/plasmablob.py
plasmapy/utils/calculator/main_interface.py
plasmapy/utils/calculator/widget_helpers.py
plasmapy/utils/data/downloader.py
plasmapy/utils/decorators/validators.py
requirements/tests.txt
setup.cfg
tox.ini

This PR adds the following flake8 extensions:
- ~~flake8-useless-assert — to make sure that `assert` statements won't always pass or fail~~
- flake8-use-pathlib — to enforce recommend usage of `pathlib`
- flake8-builtins — to avoid name conflicts with Python builtins (like `min` and `max`)
- flake8-comments — to avoid redundant comments
This PR also makes a few minor edits in order for the new flake8 extensions to pass.
Before merging, I'll need to:

Add `flake8` extensions

---

.gitignore
.pre-commit-config.yaml
changelog/1807.trivial.rst
docs/contributing/coding_guide.rst
docs/contributing/doc_guide.rst
docs/contributing/release_guide.rst
docs/contributing/testing_guide.rst
docs/particles/decorators.rst
docs/particles/particle_class.rst
docs/plasma/index.rst
plasmapy/particles/particle_class.py
plasmapy/plasma/grids.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/lite_func.py
plasmapy/utils/pytest_helpers/pytest_helpers.py

This PR adds a pre-commit hook for [blacken-docs](https://github.com/adamchainz/blacken-docs) and applies a bunch of the changes.  It also applies some issues with examples in code blocks that I found with [shed](https://github.com/Zac-HD/shed), which I learned about in a podcast and was trying out for fun.

Add `blacken-docs` to `pre-commit` & apply minor reST fixes

---

changelog/1822.trivial.rst
requirements/tests.txt
setup.cfg
tox.ini

Right now we have an issue where tests run via `pytest-xdist` with more than one process are not able to be run because the test order is not deterministic (i.e., because sets or dicts are used when parametrizing tests).  See also #750.  This has apparently recently caused the tests to fail when they're run via GitHub Actions.
This PR removes `pytest-xdist` from our requirements as a way to (hopefully) resolve this issue.

Remove pytest-xdist from test requirements

---

docs/whatsnew/0.9.1.rst
docs/whatsnew/index.rst

The changelog for on stable still lists `dev`, which is making it show up incorrectly.  This PR removes the `dev` and adds a brief changelog to 0.9.1.

Update changelog for 0.9.1 on `stable`

---

.github/workflows/weekly.yml

Our weekly tests are failing because `3.10` was being treated as `3.1` in `.github/workflows/weekly.yml`.  This PR fixes that by making the `3.10` into a string.  
If only this was the first time I've introduced this error! 👀 😅 😹 🎈 🎆 🎂

Fix weekly test configuration error

---

changelog/1825.feature.rst
docs/about/credits.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_atomic.py
plasmapy/particles/tests/test_exceptions.py
plasmapy/particles/tests/test_particle_class.py

In particle_class, NaN values are now returned instead of throwing exceptions.
In addition, test_atomic, test_exceptions, and test_particle_class are changed to reflect changes to particle_class and new tests are added to test_particle_class to ensure that NaN values are returned when accessing undefined properties.
By returning NaN values, numpy.nan can keep track of what is undefined and what is not, avoiding dealing with exceptions as a special case. Also makes the behavior of Particles and CustomParticles more consistent
This issue was brought up in #1061

Return NaN values instead of throw exceptions for particle attributes

---

docs/contributing/testing_guide.rst

Minor/trivial change to the testing guide.
I was reading the sample code output, but the sample output did do what the sample code said it should do.
Reversed order in reverse_order 'if' statement (a+b) -> (b+a)

Fixed functional typo in testing_guide.rst

---

.readthedocs.yml
tox.ini

- Fixes #1838 by adding a `graphviz` dependency (see also https://github.com/sphinx-doc/sphinx/issues/10948 and https://github.com/sphinx-doc/sphinx/pull/11040) in order to fix a problem with inheritance diagrams not showing up in the doc build
- Updates the Read the Docs configuration file
- Adds a link to the troubleshooting guide
- Sets `fail_on_warning` to `true` which is equivalent to the settings we have for the CI doc build
- Corrects the link anchor to the troubleshooting guide in `tox.ini`

Update Read the Docs configuration and add `graphviz` dependency

---

docs/index.rst

This PR adds a link to the GitHub repository in the documentation sidebar for the landing page.  Yet another PR inspired by a [podcast](https://pythonbytes.fm/episodes/show/310/calling-all-tools-for-readmes).  📻

Link to GitHub repository from documentation landing page

---

.readthedocs.yml

Based on discussion at community meeting, to make sure we keep the preview for the RTD build.

Revert fail-on-warning option for Read the Docs build

---

.github/workflows/testing.yml
.github/workflows/weekly.yml
pyproject.toml
tox.ini

The weekly tests have been failing because apparently the `NIGHTLY` builds of NumPy are no longer pointing to the right place.  This PR aims to update the test setup to point it to the right location.
My first try is to point to NumPy's GitHub repository, which would unfortunately mean that it would have to rebuild NumPy (which could be time-consuming and unnecessary).  Going with this route would be a temporary fix, and I'd raise another issue to fix that.

Fix weekly test against development version of NumPy

---

pyproject.toml

This PR adds sections to `pyproject.toml` for [configuring](https://github.com/charliermarsh/ruff#configuration) [`ruff`](https://github.com/charliermarsh/ruff).  
Related to #1845, #1846, and #1847.

Add `ruff` section to `pyproject.toml`

---

docs/whatsnew/0.9.1.rst
docs/whatsnew/dev.rst
docs/whatsnew/index.rst
pyproject.toml

There was a doc build failure that started in #1847:
```
/home/runner/work/PlasmaPy/PlasmaPy/docs/whatsnew/index.rst:11: WARNING: toctree contains reference to document 'whatsnew/dev' that doesn't have a title: no link will be generated
```
There was just a release of towncrier `22.12.0`, so I suspect it might have something to do with that.
This PR is to try two separate things for fixing it.
- Pin `towncrier` an older version (preferred)
- Add a title to `whatsnew/dev.rst` and make sure it looks okay in the outputted docs
I'm also adding the brief changelog from `0.9.1` that I forgot to copy over from #1819 and #1820.

Pin version of `towncrier` to address doc build error

---

changelog/1853.trivial.rst
plasmapy/analysis/fit_functions.py
plasmapy/analysis/nullpoint.py
plasmapy/analysis/swept_langmuir/floating_potential.py
plasmapy/analysis/swept_langmuir/ion_saturation_current.py
plasmapy/analysis/tests/test_nullpoint.py
plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_detector_stacks.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_synthetic_radiography.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/numerical/hollweg_.py
plasmapy/particles/tests/test_atomic.py
plasmapy/particles/tests/test_ionization_collection.py
plasmapy/particles/tests/test_nuclear.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/particles/tests/test_particle_collections.py
plasmapy/plasma/grids.py
plasmapy/plasma/plasma_base.py
plasmapy/plasma/tests/test_grids.py

This PR applies changes from `ruff` and `refurb` on a few other subpackages.  This follows up on #1845, #1846, and #1847.

Use `ruff` and `refurb` on remainder of `plasmapy`

---

.github/workflows/add_comments.yml

This PR pins the GitHub Action used for posting the code review checklist to v0.1.0 instead of the development branch.
Whilst hanging out on another repository, I heard some good security advice that it is best to pin GitHub Actions to specific releases.  This is to prepare for the unlikely eventuality that malicious code ends up getting put into a development branch.  Pinning it to a specific release is better than pinning it to a particular commit also (because a force push could have the same commit hash).  
#1729

Pin GitHub Action to specific version for posting code review checklists

---

.github/workflows/add_comments.yml

This PR fixes the error I introduced in #1852 (oops!) by reverting the version of `actions/checkout` to `v3` instead of the incorrect `v0.1.0`.

Fix version of GitHub Action

---

.github/workflows/add_comments.yml

This follows up on the error I introduced in #1850 and successfully didn't fix in #1855.  I'm going to briefly give myself admin superpowers once again to merge this to make sure it works.

Pin GitHub Action to a specific commit

---

.github/workflows/add_comments.yml

This PR reverts #1857, #1855, and #1852 to go back to...I hope...the last commit where the GitHub Action to post the code review checklist was actually working.  This has been an adventure (sigh).  
I'm temporarily changing `pull_request_target` to `pull_request`, which after reading the docs, I think will let me test this GA while it's still in the PR stage.  
Update: ↑ doesn't actually let me check the action, since it requires permissions (sigh).

Revert updates to GitHub Action

---

.github/workflows/citation_updater.py
.pre-commit-config.yaml
changelog/1854.trivial.rst
pyproject.toml

This PR is the final in the series of PRs to get [`ruff`](https://github.com/charliermarsh/ruff) ~~and [`refurb`](https://github.com/dosisod/refurb)~~ applied to the repo and into our `pre-commit` suite.  
`ruff` is awesome in that it runs really quickly (since it's written in Rust) and automagically applies a lot of fixes that would be found by `flake8`. We might have some duplication between `flake8` and `ruff`, but it'd be helpful to keep both for the time being.
~~A less nice thing about `refurb` is that it takes a long time to run compared to other pre-commit hooks. However, some of the fixes that refurb caught were pretty important.  In particular, it caught a couple of cases where there were two tests named the same thing, which probably meant that the first of those tests were not …

Add `ruff` to `pre-commit` configuration

---

.pre-commit-config.yaml

`ruff`, added in #1854, was missing the `--fix` flag. We can use that one to have pre-commit.ci autofix work as expected.

Adjust ruff for pre-commit

---

changelog/1856.doc.rst
docs/contributing/coding_guide.rst

This PR reorganizes the coding guide by moving things around, adding new section headers, and changing some sections to subsections.  I have not changed any of the content of the coding guide here, only the overall layout and document structure.  Hopefully that'll simplify the code review.
Closes #1715.

Restructure coding guide

---

.pre-commit-config.yaml
pyproject.toml

This PR adds a pre-commit hook using [`pyproject-fmt`](https://pyproject-fmt.readthedocs.io/en/latest/) and drops the pre-commit hook using `pretty-format-toml`.  
It looks like the only TOML file that we have is our `pyproject.toml`, so it makes sense to use a tool that has more specific and standardized formatting for `pyproject.toml`s.  (Or is it `pyprojects.toml`?  I don't know what the plural of `pyproject.toml` is.)
We're also running into a problem with our pre-commit config due to a new inconsistency upstream of `pretty-format-toml`.  Removing `pretty-format-toml` will address this problem (though that issue will probably get fixed in a few days anyway).
This time I did *not* hear about this tool from a podcast!  I read about it in the show notes of a podcast instead. 😬

Use `pyproject-fmt` instead of `pretty-format-toml`

---

changelog/1866.feature.1.rst
changelog/1866.feature.2.rst
changelog/1866.removal.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py

I made the following changes to `CustomParticle`:
- Added `Z` as a keyword-only parameter (which can be real, and not just an integer)
- Added the `charge_number` attribute
- Updated the serialization functionality
Long story short, this is to make it easier to change `particle_input` and the particle factory function to allow non-integer charges, which will allow `particle_input` to decorate functions that have `Z_mean` as a parameter, and thus let us deprecate `Z_mean` in favor of `Z`.

Expand charge number functionality for `CustomParticle`

---

CITATION.cff
changelog/1813.feature.rst
changelog/1816.trivial.rst
changelog/1824.breaking.rst
changelog/1824.removal.rst
changelog/1825.feature.rst
changelog/1854.trivial.rst
docs/about/credits.rst

This PR makes a few minor updates to changelog entries, and updates the author lists in `credits.rst` and `CITATION.cff` prior to `2023.1.0`. 
Tasks remaining:

Update changelog entries and author lists

---

changelog/1880.trivial.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/utils/_units_helpers.py
plasmapy/utils/tests/test_units_helpers.py

Added additional keyword arguments to `plasmapy.utils._units_helpers._get_physical_type_dict`.
This PR adds capabilities that will be used when implementing a custom constructor method for `CustomParticle`.
This PR was originally part of #1874, which I'm splitting up into different pull requests.

Add `strict` and `allowed_physical_types` keyword arguments to `_get_physical_type_dict`

---

pyproject.toml

I tried doing the release yesterday, but [as seen in the logs](https://github.com/PlasmaPy/PlasmaPy/actions/runs/3904848534/jobs/6671146694), when you upload a pyproject.toml-based package to pypi it can't depend on "floating" dependencies such as
```
"codespell @ git+https://github.com/codespell-project/codespell/ ;   
```
Which is, of course, a smart decision from them. So I'm removing that one from test dependencies, but it'll still be specified in the tox env we have for codespell. So it should be fine.

Drop codespell from pyproject.toml reqs

---

changelog/1822.trivial.rst
plasmapy/particles/tests/conftest.py
plasmapy/particles/tests/test_ionization_state.py
plasmapy/particles/tests/test_parsing.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/particles/tests/test_special_particles.py
tox.ini

- I wrapped most of the lists of particles that go into `pytest.mark.parametrize` into `list(sorted(...))`. Turns out that's enough. Not entirely sure why, tbh. See https://pytest-xdist.readthedocs.io/en/latest/known-limitations.html#workarounds for where I found this trick.
- I reverted the removal of pytest-xdist.
https://github.com/StanczakDominik/PlasmaPy/actions/runs/3701946161 was just one example of the recently happening test failure resulting from parameters for tests in the particle subpackage being "insufficiently ordered", as it turns out. See commit message for the first one, because I'm still pretty confused about it. We previously removed pytest-xdist from dependencies as a temporary measure in https://github.com/PlasmaPy/PlasmaPy/pull/1822, where I promised to fix the root …

Ensure ordering for particles in tests

---

changelog/1906.trivial.rst
pyproject.toml
tox.ini

[`dlint`](https://github.com/duo-labs/dlint) is a nice tool to help enforce coding best practices and improve code security.  Because: 
- The repo has been archived, with the last commit/release in 2020, and
- `dlint` has an upper limit of `flake8<6`,
we should drop `dlint` from our linters.  In particular, using up-to-date versions of `flake8` is more important than to keep using `dlint`.  If `dlint` starts being maintained again and drops the flake8 upper limit, I'd be happy to bring it back.

Drop `dlint` from linters

---

changelog/1883.doc.rst
plasmapy/particles/decorators.py

This PR makes a few minor updates to the docstring for `@particle_input`, including some edits to the content and fixes for minor formatting issues.
The docstring is also significantly more verbose than would be optimal, which makes it hard to parse and find things in it.  I might try to add subsections to the examples and/or notes sections (though I'm not sure if Sphinx can handle it), or maybe a bullet point list near the top of what `@particle_input` can do.  This might end up needing an example notebook though.
It also removes a mention regarding Python 3.9+, so this should be merged **after** the `2023.1.0` release when we drop support for Python 3.8 (#1796).

Edit the docstring for `particle_input`

---

.github/dependabot.yml
CODEOWNERS

This does three things:
- assigns me to dependabot PRs and to their review 
- adjusts CODEOWNERS so it doesn't sidestep the former setup
-  automatically gives dependabot PRs the changelog skip label

Adjust dependabot config

---

.github/workflows/testing.yml
.pre-commit-config.yaml
docs/contributing/testing_guide.rst
tox.ini

This PR moves `codespell` from `tox` and into the `pre-commit` configuration.
We use `codespell` to catch common misspellings.  We currently have a separate `tox` environment and GitHub Action for codespell. However, if we move `codespell` to `pre-commit`, we can remove both the `tox` environment and the GitHub Action.
This is based off of https://github.com/astropy/astropy/pull/13982 and https://github.com/astropy/astropy/pull/13985.

Move codespell to pre-commit

---

changelog/1992.bugfix.rst
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_exceptions.py

Previously, calling `Particle("H", Z=1, mass_numb=1)` mistakenly issued an unnecessary warning for redundant particle information.  This PR removes that warning and adds a specific error message for protons.  
Closes #1991.

Remove warning and improve error messages for invalid protons

---

README.md
docs/contributing/workflow.rst

This PR updates our documentation to refer to the "good first issue" label rather than the "Good first contribution" label.  The reason is that "good first issue" has become the most common wording for this, and there are sites that look specifically for "good first issue" labels.  So, it'd be helpful to update it for us too.

Rename label: "Good first contribution" → "good first issue"

---

CODEOWNERS
pyproject.toml

This PR removes the `looponfailroots` option, which has been deprecated for `pytest-xdist`.  I also added myself as the code owner for the `pre-commit` configuration file.

Remove deprecated `pytest-xdist` option and update `CODEOWNERS`

---

docs/notebooks/diagnostics/charged_particle_radiography_film_stacks.ipynb
docs/notebooks/diagnostics/charged_particle_radiography_particle_tracing.ipynb
docs/notebooks/diagnostics/charged_particle_radiography_particle_tracing_custom_source.ipynb
requirements.txt

This PR does an update of `requirements.txt` using the command:
```bash
pip-compile --all-extras --output-file=requirements.txt --resolver=backtracking
```
This is in lieu of using dependabot for each one.  The goal is to automate this in #1994.

Use `pip-compile` to update `requirements.txt`

---

changelog/1987.feature.rst
plasmapy/particles/particle_collections.py
plasmapy/particles/tests/test_particle_collections.py

The goal of this PR is to make `ParticleList` accept `Quantity` arrays with physical types of mass or electrical charge.  This also makes `ParticleList.append` accept `Quantity` non-arrays.  Each `Quantity` of the appropriate physical type will be converted into a `CustomParticle`.  
The motivation is primarily to allow `particle_input` to process `Quantity` arrays, which is needed for #1871 (if I recall correctly).
This PR originated as part of #1874.

Make `ParticleList` accept `Quantity` arrays

---

changelog/2031.feature.rst
docs/about/credits.rst
plasmapy/formulary/lengths.py

This PR refactors the gyroradius function for better readability and maintainability. The changes include:
- Replacing nested conditionals with separate functions
- Extracting error checks and warnings into separate functions
- Simplifying the calculation of Vperp and Lorentz factor using helper functions
- Descriptive function names for better understanding
The motivation behind this PR is to reduce the cognitive complexity of ``plasmapy.formulary.lengths.gyroradius``. By simplifying the code and separating the logic into different functions, future contributors will have an easier time understanding and modifying the code.

Reduce cognitive complexity of gyroradius

---

.github/labeler.yml
.github/workflows/labeler.yml

This PR (hopefully!) repairs our implementation of the [labeler](https://github.com/marketplace/actions/labeler) GitHub Action. 
It appears that the problem was that we deleted our `.github/workflows/labeler.yml` action in #1800, when we were trying to repair the size-labeler GitHub Action.  My bad!
This is one of those pull requests where we won't be able to test it until after we merge it, but if there are any problems with it, then I'll submit a follow-up pull request shortly thereafter.
Closes #2042. Hopefully!

Repair GitHub Action that labels pull requests

---

changelog/2041.doc.rst
docs/contributing/testing_guide.rst

This PR changes the order of sections in the testing guide so that the parts about writing tests come before the parts about running tests. I'll comment on the (minimal) changes to the content. 
Here's the [**preview of the testing guide**](https://plasmapy--2041.org.readthedocs.build/en/2041/contributing/testing_guide.html).

Reorganize testing guide

---

.pre-commit-config.yaml
plasmapy/particles/decorators.py
plasmapy/particles/particle_class.py

We just got a new linter error, which is essentially that we should switch `something.get('key', None)` with `something.get('key')`.  
I'm also going to take a moment to update our pre-commit configuration, I think.

Update pre-commit versions and fix linter error

---

changelog/2034.breaking.rst
changelog/2034.trivial.rst
plasmapy/particles/decorators.py
plasmapy/particles/tests/test_decorators.py
tox.ini

A feature of `@particle_input` is that if a parameter to a function is named `ion`, then it will ensure that the particle is indeed an ion. This feature is syntactic sugar for the categorization criteria that can be specified in `@particle_input`.  
However, this feature doesn't work for positively charged particles that represent (for example) *mean* ions. The purpose of this pull request is to enable `@particle_input` to accept `CustomParticle` objects that have a mass and are positively charged.  
This is needed for #2022 to enable compatibility with charge numbers that are not integers.

Allow `@particle_input` to accept custom ions when parameter is named `ion`

---

changelog/2055.doc.rst
docs/about/citation.rst
docs/examples.rst
docs/index.rst

- I updated the first paragraph on the landing page of PlasmaPy's documentation.
- I added an admonition on the landing page on citing PlasmaPy, largely based on Astropy's.
- I made some edits to the citation instructions, such as by organizing content in admonitions and noting that people using a technique originally from a paper referenced in a docstring should also cite that paper.

Update doc landing page and citation instructions

---

.github/labeler.yml
.pre-commit-config.yaml

The GitHub Action for labeling PRs has been working inconsistently.  My suspicion is that there need to be quotes surrounding the patterns in lists in `.github/labeler.yml`. I'm thinking (guessing?) that the quotes are needed because all of the examples in the [labeler documentation](https://github.com/actions/labeler#pull-request-labeler) have quotes.  
The quotes were being deleted by the YAML reformatter in our pre-commit configuration, so I set it to exclude that particular file.
I'm going to merge this quickly since it's one of those PRs that need to be merged before they can be tested (sigh).

Update YAML file defining labels to apply to pull requests

---

.github/labeler.yml
.pre-commit-config.yaml

This PR updates the [labeler](https://github.com/actions/labeler) GitHub Action with some more rules for when GitHub labels get applied to PRs.

Update the labeler GitHub Action

---

.github/workflows/testing.yml

This PR modifies when the GitHub Action to check packaging PlasmaPy is run during continuous integration.  
At the moment, the packaging check is started after all other checks have passed. This means that the time to finish our continuous integration checks is $t_\mathrm{doc build} + t_\mathrm{packaging}$ (since the doc build takes significantly longer than everything else and is thus our CI critical path).
This PR makes it so that the packaging check is done after the initial tests are run without waiting for the comprehensive tests and the documentation build. As a consequence, our CI timescale will become $∼t_\mathrm{doc build}$.

Run packaging GitHub Action sooner

---

.github/workflows/testing.yml
requirements.txt

The goal of this PR is to fix an issue we just started having with codecov.
```
python -m pip install --progress-bar off --upgrade "tox<4" codecov
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
Collecting tox<4
Downloading tox-3.28.0-py2.py3-none-any.whl (86 kB)
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
Error: Process completed with exit code 1.
```

Update requirements and fix issue with version conflict related to coverage

---

changelog/1656.doc.3.rst
changelog/1665.feature.rst
changelog/1864.trivial.rst
changelog/1992.bugfix.rst
changelog/2038.doc.rst
changelog/2041.doc.rst

We plan to release PlasmaPy 2023.5.0 next month.  This PR contains a few minor edits to changelog entries for other PRs in advance of that release.  The changes include more details and/or reST links to functions that were added.

Made minor edits to changelog entries

---

CODEOWNERS

This PR updates the `CODEOWNERS` file, which is used to specify who gets requested for review by default.  I attempted to make it more fine-grained, which will make it less likely that we'll need to change reviewers around and that we preferentially get assigned reviews of subpackages that we're familiar with.  
I've also commented out a few lines so that those of us who aren't available to review right now are less likely to get assigned reviews, but I'd be happy to uncomment those lines when they're available to review again.  (By the way, I hope you're doing okay!)

Update codeowners for different files and subpackages

---

.readthedocs.yml

Our Read the Docs (RTD) configuration started failing within the last day, presumably after their newest release of [v9.12.0](https://docs.readthedocs.io/en/stable/changelog.html#version-9-12-0).
The purposes of this PR are to:
- Fix the RTD build somehow.
- See what happens when we use the melty face emoji in a branch name.

Fix and update Read the Docs configuration

---

plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/plasma/grids.py
plasmapy/utils/_units_helpers.py
plasmapy/utils/decorators/tests/test_checks.py
plasmapy/utils/decorators/tests/test_validators.py
pyproject.toml

This PR enables the [PLW](https://beta.ruff.rs/docs/rules/#warning-plw) rule set for ruff, and adds `noqa` comments for lines that ruff flagged.

Enable PLW rule set for ruff

---

plasmapy/analysis/nullpoint.py
plasmapy/analysis/swept_langmuir/floating_potential.py
plasmapy/analysis/swept_langmuir/helpers.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_synthetic_radiography.py
plasmapy/diagnostics/langmuir.py
plasmapy/diagnostics/thomson.py
plasmapy/dispersion/analytical/stix_.py
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/numerical/hollweg_.py
plasmapy/dispersion/numerical/kinetic_alfven_.py
plasmapy/formulary/braginskii.py
plasmapy/particles/_parsing.py
plasmapy/particles/_special_particles.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/plasma/grids.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/validators.py
pyproject.toml

This PR enables some ruff [rules](https://beta.ruff.rs/docs/rules/#refactor-plr) for pylint refactorings.  I added a bunch of `# noqa` comments for the functions that were flagged already.
There are some rules that we might want to revisit again in the future.
- `PLR0912` limits the number of branches (i.e., conditionals) in a function to 12
- `PLR0915` limits the number of statements in a function to 50
If we have a good reason to exceed these limits, we can add a comment like `# noqa: PLR0912" to turn off the rule for a function.

Enable ruff rules for pylint refactorings

---

plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/diagnostics/tests/test_langmuir.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/plasma/grids.py
plasmapy/simulation/tests/test_particletracker.py
pyproject.toml

Following up on #2080, this PR enables both of the [NPY rules](https://beta.ruff.rs/docs/rules/#numpy-specific-rules-npy) for ruff.  Previously, only `NPY001` had been enabled.  `NPY002` warns about usage of deprecated NumPy random number generation tools.  I also added `# noqa: NPY002` to lines that currently use the deprecated tools to silence the warning.
I plan to create an issue to update to newer NumPy random number functionality, but I don't think we need to be in any hurry about it.

Enable NPY rules for ruff

---

plasmapy/analysis/nullpoint.py
plasmapy/analysis/swept_langmuir/floating_potential.py
plasmapy/analysis/swept_langmuir/helpers.py
plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/diagnostics/charged_particle_radiography/tests/test_synthetic_radiography.py
plasmapy/diagnostics/tests/test_thomson.py
plasmapy/diagnostics/thomson.py
plasmapy/dispersion/analytical/stix_.py
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/numerical/hollweg_.py
plasmapy/dispersion/numerical/kinetic_alfven_.py
plasmapy/formulary/collisions/lengths.py
plasmapy/formulary/collisions/tests/test_frequencies.py
plasmapy/formulary/lengths.py
plasmapy/particles/_parsing.py
plasmapy/particles/_special_particles.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/plasma/grids.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/validators.py
plasmapy/utils/pytest_helpers/pytest_helpers.py
pyproject.toml

[Cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) is "a quantitative measure of the number of linearly independent paths through a program's source code."  When cyclomatic complexity is high, functions tend to be harder to understand, modify, & test.
This PR enables ruff rule [`C901`](https://beta.ruff.rs/docs/rules/#mccabe-c90) that issues warnings when the cyclomatic complexity exceeds a certain threshold.  I set the threshold to the default value of 10, but we may want to adjust it later since I don't know if that's the best value for scientific software development.  
A good first strategy for [reducing cyclomatic complexity](https://blog.codacy.com/reduce-cyclomatic-complexity/) is to write small functions that do one thing with no side effects.  A high …

Enable ruff rule for cyclomatic (McCabe) complexity

---

plasmapy/formulary/collisions/helio/collisional_analysis.py

I just merged #2119 without pulling in the changes from `main` after #1986 was merged, and noticed that another `# noqa` comment was needed which this PR adds.

Add `# noqa` comment for cognitive complexity rule

---

.editorconfig

This PR sets the indent sizes in `.editorconfig` for the very few `.cff`, `.bib`, `.ini`, and `.html` files in our repo.

Update indent sizes in `.editorconfig`

---

changelog/2133.bugfix.rst
plasmapy/analysis/nullpoint.py
plasmapy/analysis/tests/test_nullpoint.py

Resolves #2101 
The `_vector_space` function in the `nullpoint` module returns an array for its delta values in each dimension. This is problematic because each dimension can have a different precision, meaning a different size for the delta array. The solution is to instead simply return a list.

Fix tests in `test_nullpoint`

---

changelog/2138.trivial.rst
tox.ini

Resolves #2100 
Tox has removed their `indexserver` configuration in favor of using environment variables.
See https://tox.wiki/en/4.5.1/faq.html#using-two-pypi-servers

Fix failing weekly numpy test

---

changelog/2134.feature.rst
changelog/2134.removal.rst
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/numerical/hollweg_.py
plasmapy/dispersion/numerical/kinetic_alfven_.py
plasmapy/formulary/speeds.py
plasmapy/formulary/tests/test_speeds.py

This PR decorates the `plasmapy.formulary.speeds.ion_sound_speed` with `@particle_input` in order to enhance compatibility with `ParticleList` and `CustomParticle` objects. The `z_mean` parameter for `ion_sound_speed` has been deprecated.

Decorate `ion_sound_speed` with `@particle_input`

---

changelog/2140.feature.rst
plasmapy/formulary/distribution.py
plasmapy/formulary/lengths.py

If a function is decorated with `@particle_input` and also has `mass_numb` and `Z` as parameters to the function, then we can specify the mass number via `mass_numb` and charge number via `Z`.  This PR adds `mass_numb` and `Z` to a few functions in `plasampy.formulary.lengths` and `plasmapy.formulary.distribition` since I forgot to add it before.
Follows up on #1732.  Related to #341.

Add `mass_numb` and `Z` as parameters to functions decorated with `@particle_input`

---

.github/workflows/stale.yml

This PR makes some updates to the GitHub Action that marks PRs and issues as stale. I noticed that a lot of recent issues got labeled as stale, and I suspect that default settings may have changed.
I made it so that issues get marked as stale after five years of inactivity.  Issues have the potential to remain relevant for several years, so I want to err on the side of letting them stay open for longer.
PRs still get marked as stale after a year of inactivity, which seems reasonable.

Update configuration for GitHub Action that marks issues & PRs as stale

---

changelog/2136.feature.rst
plasmapy/formulary/speeds.py

This PR decorates `plasmapy.formulary.speeds.kappa_thermal_speed` with `@particle_input` in order to make it more compatible with a broader range of particle-like arguments.

Decorate `kappa_thermal_speed` with `@particle_input`

---

.github/workflows/testing.yml
.github/workflows/weekly.yml
.pre-commit-config.yaml

The GitHub Action for setting up Python has an option for caching dependencies. This PR attempts to enable it for our CI in several places.

Add basic caching to GitHub Actions CI

---

.github/workflows/weekly.yml

Resolves #1638
Adds a weekly test to the workflow to ensure that PlasmaPy can be installed via the conda-forge channel.

Add a weekly test for conda-forge installation

---

.github/workflows/update-pinned-reqs.yml

This PR updates the message posted by this GitHub Action, and also changes a token so that CI checks will actually be run by this automatically generated PR.

Refine GitHub Action for updating pinned requirements

---

.github/workflows/release.yml

This PR makes some updates to the release script:
- It removes the step for running `pre-commit autoupdate`. The pre-commit autoupdates are now done on a weekly basis, so this step is no longer necessary.
- It updates the Python version to 3.11.
- It updates the default version to be something date-based with an `rc1` tag.

Update GitHub Action for release

---

.github/workflows/release.yml

We renamed `whatsnew` → `changelog` in the docs, but didn't update it in this GitHub Action. This PR fixes that oversight.

Change `whatsnew` to `changelog` in `release` GitHub Action 

---

.github/workflows/pr-lableler.yml

This PR changes the labeler GitHub Action so that it doesn't remove labels that no longer meet the criteria. 
This setting had been causing a problem where it would remove the "No changelog entry needed" label that I had set manually because of a rule for adding that label.  I didn't see an option for turning off syncing for certain labels, unfortunately.

Set labeler GitHub Action to not remove labels

---

.pre-commit-config.yaml
docs/bibliography.bib

Minor formatting updates to `docs/bibliography.bib` using [bibtex-tidy](https://flamingtempura.github.io/bibtex-tidy). 
I attempted to set up a pre-commit hook for `bibtex-tidy` but wasn't able to get it to work successfully.

Use `bibtex-tidy` on `bibliography.bib`

---

.pre-commit-config.yaml

Just started getting a deprecation warning regarding the `--nbqa-mutate` flag for `nbqa-black`, so I'm removing that there.  The message said that the flag is now unnecessary so this shouldn't cause any issues.

Remove deprecated flag pre-commit configuration

---

plasmapy/utils/decorators/tests/test_validators.py
pyproject.toml

A few years ago, a convention with type hints allowed us to skip using `typing.Optional` when the default value was `None`.  That convention is now not recommended.  This PR applies ruff rule `RUF012` which changes things like `f(x: int = None)` to `f(x: Optional[int] = None)`.
Feel free to merge if this looks good!

Add ruff rule that prohibits implicit `typing.Optional`

---

.github/scripts/authors_in_cff.py

This PR amends the author check error message with some contextual information about how some of the fields are needed for abstract submission. It also adds the `email` field to the example entry for `CITATION.cff`.

Update author check error message

---

changelog/2262.trivial.rst
plasmapy/formulary/speeds.py
plasmapy/formulary/tests/test_speeds.py

This PR improves the error message for `Alfven_speed` when `density` is a number density and `ion` is not provided. Previously, there was an error message about being able to do an operation with a `NoneType` object.
Thank you to @ejohnson-96 for bringing this up!

Improve error message for `Alfven_speed`

---

docs/conf.py
plasmapy/__init__.py
plasmapy/analysis/nullpoint.py
plasmapy/analysis/swept_langmuir/floating_potential.py
plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/diagnostics/tests/test_langmuir.py
plasmapy/diagnostics/thomson.py
plasmapy/dispersion/analytical/tests/test_two_fluid_.py
plasmapy/dispersion/analytical/two_fluid_.py
plasmapy/dispersion/numerical/kinetic_alfven_.py
plasmapy/dispersion/numerical/tests/test_hollweg_.py
plasmapy/dispersion/numerical/tests/test_kinetic_alfven_.py
plasmapy/formulary/collisions/helio/collisional_analysis.py
plasmapy/formulary/collisions/lengths.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/plasma/sources/openpmd_hdf5.py
plasmapy/plasma/sources/tests/test_plasmablob.py
plasmapy/utils/calculator/widget_helpers.py
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/tests/test_checks.py
plasmapy/utils/decorators/tests/test_helpers.py
plasmapy/utils/decorators/validators.py
pyproject.toml

This PR adds a `ruff` rule that goes through code and removes the `# noqa` comments that are no longer needed.  There are no actual substantive changes.

Apply `ruff` rule RUF100 to remove unused `noqa` directives

---

.github/workflows/testing.yml
changelog/2268.doc.rst
docs/conf.py

This PR adds [`sphinx.ext.duration`](https://www.sphinx-doc.org/en/master/usage/extensions/duration.html) as a Sphinx extension to provide output on the durations for creating documentation. It could help us figure out where the performance bottlenecks are.  
I'm not sure if it'll be helpful to add this, or just use it when figuring out how to improve performance of doc builds.

Add Sphinx extension for measuring durations in doc builds

---

docs/conf.py

We use sphinx-codeautolink (added in #1410) to create links within code blocks to code objects that were imported and have documentation pages.  This PR sets [`codeautolink_concat_default`](https://sphinx-codeautolink.readthedocs.io/en/latest/reference.html#confval-codeautolink_concat_default) such that it is not required that the import statement be in the same code block, but rather can be in a previous one.

Set default concatenation option for sphinx-codeautolink

---

changelog/2269.doc.rst
docs/conf.py
docs/contributing/doc_guide.rst

This PR enables [`sphinx.ext.viewcode`](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) which adds links to highlighted source code.

Enable Sphinx extension for adding links to source code pages

---

.github/labeler.yml

I don't think this setting has been working correctly, so I'm removing it.

Remove labeler configuration for adding "No changelog entry needed"

---

.github/workflows/testing.yml
changelog/2272.doc.rst
docs/changelog/0.7.0.rst
docs/changelog/0.8.1.rst
docs/changelog/0.9.0.rst
docs/changelog/2023.5.0.rst
docs/common_links.rst
docs/contributing/doc_guide.rst

We use `docs/common_links.rst` as a place to define links and substitutions across the documentation.  Essentially the content in `common_links.rst` gets added to the epilogue of each `.rst` file and docstring.  This has the potential to slow down documentation builds.
This PR is an attempt to consolidate some of the shortcuts into the documentation guide, since that's the main place that they get used.  
Unfortunately we don't have a good or consistent way to benchmark documentation builds yet, so I don't know for sure that it'll speed things up noticeably.  At the very least, it'll keep these definitions in a place that's closer to where they get used.

Move substitutions from `common_links.rst` to `doc_guide.rst`

---

.pre-commit-config.yaml
.pre-commit-search-and-replace.yaml
CHANGELOG.rst
docs/contributing/coding_guide.rst
plasmapy/dispersion/analytical/stix_.py

I had set up one of the patterns to replace incorrectly, so this PR fixes that.
I'm also adding a few more to automagically change to use some substitutions.
I had to exclude `.pre-commit-search-and-replace.yaml` from the yaml autoformatter in pre-commit because it kept removing quotes.

Fix and expand pre-commit-search-and-replace configuration

---

.github/workflows/update-pinned-reqs.yml

One of the options is no longer needed because it became the default.

Update `pip-compile` command for regenerating `requirements.txt`

---

changelog/2311.doc.rst
docs/notebooks/getting_started/particles.ipynb

We had been doing a `from plasmapy.particles import *`, so this PR changes that to import everything directly.

Remove star imports from particles notebook

---

plasmapy/dispersion/analytical/tests/test_stix_.py
plasmapy/dispersion/numerical/tests/test_hollweg_.py
plasmapy/dispersion/numerical/tests/test_kinetic_alfven_.py

This PR applies `@pytest.mark.filterwarnings` to many of the tests in `plasmapy.dispersion`.  I did not attempt this with doctests yet.
See also #844.

Reduce warnings emitted during tests of `plasmapy.dispersion`

---

plasmapy/plasma/tests/test_grids.py
pyproject.toml

Make it so no warnings are issued during tests by `plasmapy.plasma`

---

changelog/2324.doc.rst
docs/contributing/coding_guide.rst

Was going through old issues and figured I could close this one quickly.  Then I did some more cleanup of the coding guide (i.e., using the `:py:` role so that in-line code gets formatted as Python code).
Closes #1214.

Discuss when to use aliases in coding guide and adopt usage of `:py:` role

---

CITATION.cff
changelog/2307.doc.rst
changelog/2307.trivial.rst
docs/_cff_to_rst.py
docs/cff_to_rst.py
docs/conf.py
pyproject.toml
requirements.txt

- Added ORCID IDs for several contributors who I could disambiguate
- Updated and fixed GitHub usernames which had been causing errors when doing `make linkcheck`
- Improved the functionality that converts author information in `CITATION.cff` to a reStructuredText list.  In addition to breaking up large functions into smaller functions, this PR fixed a problem where the `:user:` role was being used even when the `alias` key representing GitHub username is unavailable (which was causing broken links to be generated).
- Perform a Unicode to ASCII conversion in the sorting key for authors.  This way, if someone's surname starts with an Á, it will get sorted as A. 
I recently also just updated the author list in our `v2023.5.1` release.

Update author information and improve functionality that generates the author list for the docs

---

CONTRIBUTING.md
changelog/2266.doc.rst

This PR adds `CONTRIBUTING.md` and adds high-level information about how to contribute to PlasmaPy.  Because of the risk of duplicating content, this page should:
- Include high-level content that is unlikely to change over time;
- Refer contributors to the relevant sections of the Contributor Guide, Code of Conduct, and other resources (in the `latest` version of the documentation).
One of the requirements for pyOpenSci peer review is to have a `CONTRIBUTING.md`.  We previously did not have it because we referred contributors to our Contributor Guide instead.
https://github.com/PlasmaPy/plasmapy-project/issues/11

Add `CONTRIBUTING.md` and link it to Contributor Guide

---

.github/workflows/weekly.yml
changelog/2328.trivial.rst
tox.ini

- I added a `tox` environment called `build_docs_linkcheck` which verifies hyperlinks in the documentation.  This is essentially `make linkcheck`.
- I added this environment to our weekly GitHub Actions, which can also be run by workflow dispatch. 
This PR is a way to make sure hyperlinks in our docs are up-to-date and we don't have any new cases of [link rot](https://en.wikipedia.org/wiki/Link_rot).
Closes #1266.  See also #2309.

Add weekly test of hyperlinks in documentation

---

.github/workflows/weekly.yml

A follow-up of #2328.  
This PR renames the environment so that pandoc and graphviz get installed.

Fix new GitHub Action that checks hyperlinks

---

docs/conf.py
plasmapy/formulary/collisions/frequencies.py
requirements.txt

This PR fixes a few doctests that just started failing.
One thing that's strange...  The doctests are now failing both for the newly pinned dependencies as well as the minimal dependencies.  This should not be the case.

Update doctests that were not being run until a recent pytest bugfix

---

.github/workflows/stale.yml

There was a syntax error in our [stale](https://github.com/actions/stale) GitHub Action.  I put in a list/sequence when it was supposed to be a comma-separated string.  Will merge this so that I can see if it is working now.

Update stale GitHub Action

---

plasmapy/analysis/swept_langmuir/tests/test_ion_saturation_current.py

- Updated the value of `b` in a test of finding the ion saturation current.
- Added values for `rtol` and `atol` in this test.
There also seem to be slight differences ($𝒪(10^{-3}$?) in some of the fitted values depending on if it's NumPy 1.24 or 1.25.  Hm...
See #2347.

Update tolerances in Langmuir tests

---

.github/workflows/testing.yml
.github/workflows/weekly.yml
tox.ini

- The testing environment defined in `tox.ini` for running tests against our minimal dependencies now only contains the dependencies listed in `pyproject.toml` for regular installation (i.e. excluding docs & tests dependencies)
- I updated a GitHub Action so that the OS for an environment actually matches the name of the test.

Make minor updates related to testing and CI

---

changelog/2346.trivial.rst
plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/tests/test_validators.py
plasmapy/utils/decorators/validators.py

This PR makes it so that `@validate_quantities` accepts annotations of the style:
```python
@validate_quantities
def convert_to_meters(x: u.Quantity[u.m]) -> u.Quantity[u.m]:
return x
```
I still need to update the documentation and make more thorough tests.
~~**This might not work for Python 3.9, but it should work for Python 3.10+.** We can add the capability now, but we will not be able to apply it in our repository until we drop Python 3.9 support for our 2024.5.0 release.~~
I was pleasantly surprised that this is working for Python 3.9 as well as 3.10 & 3.11.  Not sure why...but I'll take it!
Before this pull request, annotations used by `@validate_quantities` had to be unit-like objects, like `f(x: u.m):`.  However, this is incompatible with mypy, which is expecting `Quantity` as an …

Make `@validate_quantities` accept `Quantity[Unit]` style annotations

---

changelog/2068.feature.rst
changelog/2195.doc.rst
changelog/2229.trivial.rst
changelog/2248.bugfix.rst
changelog/2262.trivial.rst
changelog/2268.doc.rst
changelog/2269.doc.rst
changelog/2272.doc.rst
changelog/2282.doc.rst
changelog/2289.feature.rst
changelog/2295.trivial.rst
changelog/2296.trivial.rst
changelog/2308.doc.rst
changelog/2309.doc.rst
changelog/2328.trivial.rst
changelog/2346.trivial.rst
docs/contributing/doc_guide.rst

This PR revises some changelog entries that have been made since the previous release.
I applied the "No changelog entry needed" label so that the Giles check doesn't give errors related to editing changelog entries for pull requests other than this one.

Update changelog prior to next release

---

docs/contributing/doc_guide.rst
plasmapy/analysis/nullpoint.py
plasmapy/formulary/lengths.py
plasmapy/formulary/relativity.py
plasmapy/particles/atomic.py
plasmapy/particles/decorators.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/particles/nuclear.py
plasmapy/particles/particle_class.py
plasmapy/particles/symbols.py
plasmapy/utils/code_repr.py

This PR makes some autoreplacements and a couple of manual changes to type specifications, in this order:
- `optional, |keyword-only|` → `|keyword-only|, optional` 
- `optional, default:` → `default:` (since we don't need to say it's optional if there's a default)
- Moving default values from parameter description to type specification

Consistentify type specifications in docstrings

---

.pre-commit-search-and-replace.yaml
docs/contributing/doc_guide.rst

This PR updates the settings for pre-commit-search-and-replace to help us have a consistent style for docstrings:
- `optional, |keyword-only|` → `|keyword-only|, optional`
- `, optional, default:` → `, default:`
Related to #2358.

Update search and replace for type specifications

---

changelog/2356.doc.rst
docs/contributing/doc_guide.rst
plasmapy/diagnostics/thomson.py
plasmapy/formulary/lengths.py

I'm updating the docstring of `gyroradius`, including some reorganization and more narrative examples.
I was looking through the online documentation and noticed that some of the symbols in the docstring for `gyroradius` were specific to ions.

Update docstrings and annotations in formulary length calculations

---

changelog/2369.breaking.rst
plasmapy/analysis/swept_langmuir/tests/test_ion_saturation_current.py
plasmapy/formulary/collisions/frequencies.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/tests/test_dielectric.py
plasmapy/formulary/tests/test_plasma_frequency.py
plasmapy/particles/particle_class.py
plasmapy/particles/tests/test_particle_class.py
plasmapy/plasma/tests/test_grids.py
plasmapy/utils/calculator/main_interface.py

This PR reduces the number of warnings issued by tests.  I'm resolving a few of them and filtering others.
This PR also removes the (previously deprecated) ability to pass a real number to the `charge` parameter in `CustomParticle`, since the preferred behavior is now to pass it to `Z`.  I made sure to issue a descriptive error.
I'm filtering deprecation warnings for `MultiIndex` in `test_grids.py` (see #2319) and traitlets (see #2370).  These deprecations could possibly cause problems later on, but we don't need to see the warnings every time tests run since we have issues now created.

Reduce warnings issued in tests & deprecate passing real number to `charge` in `CustomParticle`

---

changelog/2377.doc.rst
docs/particles/particle_class.rst
plasmapy/particles/particle_class.py

This PR extends the narrative docs for the `Particle` class to include `CustomParticle`, `DimensionlessParticle`, and `ParticleList` objects.
These are a bunch of changes I've been meaning to make for probably years.
Closes #1038.

Update narrative docs for particle objects

---

.github/workflows/add-no-changelog-label.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
changelog/2380.trivial.rst

In #2379, I ended up noticing (with the help of PyCharm) that there were a few mistakes in our GitHub workflows.  I don't think these actually did any harm, but there were inconsistencies with the schema.
This PR adds a pre-commit hook that validates GitHub workflows, and makes a few fixes.

Add pre-commit hook to validate GitHub workflows

---

plasmapy/diagnostics/langmuir.py
plasmapy/formulary/__init__.py
plasmapy/formulary/collisions/dimensionless.py
plasmapy/formulary/relativity.py
plasmapy/particles/_factory.py
plasmapy/particles/_parsing.py
plasmapy/particles/_special_particles.py
plasmapy/particles/particle_class.py
plasmapy/plasma/grids.py
plasmapy/simulation/particletracker.py
plasmapy/utils/_pytest_helpers/pytest_helpers.py
plasmapy/utils/data/downloader.py
plasmapy/utils/decorators/lite_func.py

This PR removes most comments which say that code coverage checks should be ignored.
We currently use `# coverage: ignore` when we have a block of code that do not want to include in code coverage checks.  We've used that somewhat liberally in the past.  The problem with this practice is that we end up sweeping lines of code under the rug, which means that we think our code coverage is higher than it is.  Removing the `# coverage: ignore` comments will make it so that the lines of code that aren't tested show up as not being tested.  Also, some lines of code with that comment might actually be run during tests.
It's common for other projects to use `# pragma: no cover`, but we decided on using `# coverage: ignore` because it's less confusing to newcomers to the project.
This PR is also a …

Remove `# coverage: ignore` in most places for more realistic coverage reports

---

docs/contributing/release_guide.rst

In #2376, we'll be adding a GitHub Action that will post a new release checklist.  Because that PR won't be merged before the release, this PR adds an admonition to the release guide to check the latest version.

Add admonition to see latest version of release guide

---

.github/workflows/check-hyperlinks.yml
.github/workflows/weekly-tests.yml
changelog/2392.trivial.rst

This PR moves the `make linkcheck` GitHub Action from the weekly tests into a separate file so that it can be run separately.
Because [link rot](https://en.wikipedia.org/wiki/Link_rot) is so pervasive, our hyperlink check frequently fails.  We will sometimes get intermittent test failures when a hyperlink temporarily becomes unavailable before being restored.  The nature of this failure is quite different than other failures in our cron tests since it is in an external, changing environment.

Separate GitHub Action for checking hyperlinks into its own action

---

CITATION.cff
plasmapy/formulary/braginskii.py

Updated the docstring in formulary/braginskii.py, where it said `see also: ion_thermal_conductivity` in the documentation instead of `see also: electron_thermal_conductivity`.
Closes #2365

Update ion_thermal_conductivity docstring

---

CITATION.cff
changelog/2402.bugfix.rst
plasmapy/plasma/sources/openpmd_hdf5.py

While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [openpmd_hdf5.py](https://github.com/PlasmaPy/PlasmaPy/blob/main/plasmapy/plasma/sources/openpmd_hdf5.py#L75), class: HDF5Reader, there is a special method `__exit__` that contains an unexpected number of parameters. Each call to this method will result in a TypeError. iCR suggested that special methods should have an expected number of parameters. More infomation can be found in the [Python documentation on the various special method](https://docs.python.org/3/reference/datamodel.html#object.__exit__).
Let's take the code example below. We're using a sample HDF5 file from this [link](https://github.com/openPMD/openPMD-example-datasets/blob/draft/example-femm-3d.h5).
```py
from …
```

Fixed Improper Method Call: `__exit__()`

---

CITATION.cff
changelog/2403.breaking.rst
plasmapy/dispersion/dispersionfunction.py
plasmapy/formulary/braginskii.py
plasmapy/formulary/collisions/coulomb.py
plasmapy/formulary/collisions/misc.py
plasmapy/formulary/collisions/tests/test_coulomb.py
plasmapy/formulary/collisions/tests/test_dimensionless.py
plasmapy/formulary/collisions/tests/test_frequencies.py
plasmapy/formulary/collisions/tests/test_lengths.py
plasmapy/formulary/collisions/tests/test_misc.py
plasmapy/formulary/quantum.py
plasmapy/formulary/relativity.py
plasmapy/formulary/tests/test_dimensionless.py
plasmapy/particles/decorators.py
plasmapy/particles/exceptions.py
plasmapy/particles/tests/test_decorators.py
plasmapy/plasma/exceptions.py
plasmapy/utils/__init__.py

I've deleted imports from sub-packages from pyplasma.utils, also I've adjusted imports in code
Resolving issue #921, this would prevent from namespace pollution
Closes #921

Removed imports from subpackages from `plasmapy/utils/__init__.py`

---

plasmapy/utils/decorators/checks.py
plasmapy/utils/decorators/converter.py
plasmapy/utils/decorators/validators.py

This PR does some minor reformatting of the validators docstrings, since we added those before we started using black as an autoformatter.

Reformat validators docstrings in the style of black

---

CITATION.cff
changelog/2410.breaking.rst
docs/changelog/0.8.1.rst
plasmapy/formulary/densities.py
plasmapy/formulary/misc.py
plasmapy/formulary/tests/test_densities.py
plasmapy/formulary/tests/test_misc.py

Function `mass_density` moved from `plasmapy.formulary.misc` to `plasmapy.formulary.densities` 
Class `Test_mass_density` moved from `plasmapy.formulary.tests.test_misc` to `plasmapy.formulary.tests.test_densities`.
Added myself to authors in CITATION.cff file
In `plasmapy.formulary` functions are broken by physical type so it makes sense to move `mass_density` into `plasmapy.formulary.densities` modul.
Closes #1919

Function mass_density moved from misc.py to densities.py

---

changelog/2428.feature.rst
plasmapy/particles/decorators.py
plasmapy/particles/tests/test_decorators.py

This PR enables `@particle_input` to decorate functions with a signature like:
```python
@particle_input
def f(*args, particle: ParticleLike = "p+"):
...
```
This fix does not extend to functions where there are positional arguments prior to variadic positional arguments, and instead adds an xfailing test for this.
This PR also does some minor refactoring of `@particle_input` (including how it processes arguments) and updates some docstrings.
I ran into this problem again when coming back to #1029, since I'm considering adding a signature that uses this pattern. 
I can't think of a straightforward way to address the case where there are positional arguments before variadic positional arguments, so I decided to not address that here and instead do an incremental change.
This is a partial …

Improve `@particle_input`'s ability to handle variadic positional arguments

---

pyproject.toml
tox.ini

We just started getting an error related to lxml when we run our tests with minimum dependencies for Python 3.9 on Windows.  It appeared that lxml was needed by voila, so I tried bumping the minimum version of voila, which seems to have fixed it.

Increase minimum version of voila to 0.5.0

---

.github/workflows/tests.yml
changelog/2431.trivial.rst
mypy.ini
pyproject.toml
tox.ini

This PR adds a tox environment for running the mypy static type checking tool.  This tox environment will be added to our suite of continuous integration tests in #2432.
I am separating this PR out so that I can use this tox environment in other PRs, like #2429.
Related to #268. The motivation for using mypy is discussed in #2424.

Add a tox environment for running mypy

---

docs/plasmapy_sphinx/autodoc/automodapi.py
docs/plasmapy_sphinx/automodsumm/core.py
plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/thomson.py
plasmapy/particles/decorators.py
plasmapy/particles/particle_collections.py
plasmapy/utils/_pytest_helpers/pytest_helpers.py
plasmapy/utils/code_repr.py
plasmapy/utils/decorators/lite_func.py

Python's docs said that `typing.Callable` is a deprecated alias to `collections.abc.Callable`. This PR updates our usage of `typing.Callable`.

Replace deprecated `typing.Callable` with `collections.abc.Callable`

---

changelog/2442.trivial.rst
mypy.ini
type_stubs/wrapt.pyi

This PR adds a [type stub file](https://mypy.readthedocs.io/en/stable/stubs.html) for [`wrapt`](https://wrapt.readthedocs.io/).
A few of our widely used decorators like `@particle_input` make use of `@wrapt.decorator`. Because `wrapt` is untyped, we were running into issues with mypy not type checking some of our code because `@wrapt.decorator` is untyped. Adding a type stub file lets us get past that.  This also serves as a prototype type stub file.
This came up in #2429.

Add type stub file for `@wrapt.decorator`

---

pyproject.toml
type_stubs/wrapt.pyi

There are some aliases in the `typing` module of the standard library that have been deprecated. For example, instead of `typing.Dict` we should use `dict`, and instead of using `typing.Iterable` we should use `collections.abc.Iterable`.  
There might be a tool that comes along in the future that will handle these changes for us, at which point we'll no longer need the rule.

Disallow deprecated aliases from `typing`

---

plasmapy/analysis/nullpoint.py
plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
plasmapy/particles/ionization_state_collection.py
plasmapy/plasma/grids.py
plasmapy/plasma/sources/openpmd_hdf5.py
plasmapy/plasma/sources/plasmablob.py
plasmapy/plasma/tests/test_plasma_base.py
plasmapy/utils/_pytest_helpers/tests/test_pytest_helpers.py
plasmapy/utils/calculator/widget_helpers.py
plasmapy/utils/decorators/tests/test_lite_func.py
plasmapy/utils/decorators/tests/test_validators.py
plasmapy/utils/tests/test_code_repr.py

This is another in a series of PRs that use autotyping to automatically add type hints. This one is using the `--scalar-return` flag.

Use autotyping on return values

---

changelog/2443.trivial.rst
mypy.ini
plasmapy/particles/decorators.py
plasmapy/particles/tests/test_decorators.py

This PR adds & improves type hint annotations in `plasmapy.particles.decorators` which is where `@particle_input` is defined, along with the tests.
There are some `# type: ignore[...]` statements for errors due to mypy's limitation as a static (rather than dynamic) type checker. We'll probably need to add that to the contributor guide.  
See #2434.  
This PR is a spinoff of #2429, and the motivation for #2442.  Closes #2434.

Improve type hint annotations for `@particle_input`

---

changelog/2440.doc.rst
docs/_global_substitutions.py
docs/contributing/testing_guide.rst

This PR adds some discussion of type hint annotations used in tests, including the `-> None` return annotation that is used by mypy to verify that there are no return statements.  
I'm using Python 3.10+ style annotations since we'll be dropping Python 3.9 support as per NEP soon after our next release.
One of the things we'll need to do if we implement mypy in our CI (#2432) is discuss it in the contributor guide.  I'm starting with the testing guide.  I expect that type hint annotations will make our tests a lot more maintainable, especially in cases where we use `@pytest.mark.parametrize` with `args` and `kwargs`.
This PR came about because #2439 is adding a lot of `-> None` return annotations to tests.

Discuss type hint annotations in testing guide

---

.gitignore
docs/Makefile

The `Makefile` we use for our Sphinx documentation build was autogenerated many years ago by `sphinx-quickstart`.  This PR updates it to be closer to what `sphinx-quickstart` provides nowadays.
One thing to note: we currently do not have separate `docs/source` and `docs/build` directories, which now seems to be the preferred way to organize our documentation.  That's discussed in #1877.

Modernize `docs/Makefile` with help from `sphinx-quickstart`

---

.github/workflows/create-release-issue.yml

The GitHub Action to create an issue with a release checklist failed when I ran it because I had forgotten to update the file path.  This PR makes that correction.

Fix path in GitHub Action for creating issue with release checklist

---

.github/workflows/check-hyperlinks.yml
changelog/2476.trivial.rst

The [Sphinx linkcheck builder](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) supports a [`-q / --quiet` flag](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-q) that reduces output verbosity while continuing to output warnings and errors.
This change enables the flag for the scheduled [`Check hyperlinks` GitHub Actions worklow](https://github.com/PlasmaPy/PlasmaPy/blob/46f59fc2d2d4d14cf3c6367adbe1d903472fd3f0/.github/workflows/check-hyperlinks.yml).
For projects like this one that feature large numbers of healthy hyperlinks, the default linkchecker output to stdout can be overly verbose, with broken/problem hyperlink reports interspersed among many reports of healthy links, making it …

ci: run hyperlink checking with quiet mode flag enabled

---

CITATION.cff
docs/conf.py

There was an update in `sphinx-issues` which set the default for the `:user:` role to point to `github.com/sponsors/username` instead of `github.com/username` (https://github.com/sloria/sphinx-issues/issues/129, https://github.com/sloria/sphinx-issues/pull/131). This led to a number of redirects to show up when we did a linkcheck build, so I added a line to `docs/conf.py` to specify that these redirects should be allowed when doing a linkcheck.  
I added some links to the docstring for `docs/conf.py` that point to helpful locations like our documentation guide and Sphinx's documentation.
I also updated the GitHub username of a past contributor.

Add new hyperlink redirects and add links to docstring of documentation configuration file

---

.github/workflows/check-hyperlinks.yml
docs/contributing/doc_guide.rst
tox.ini

- I renamed the `tox` environment from `build_docs_linkcheck` to `linkcheck` since that's what I kept trying to use.
- I moved the (incredibly helpful!) `-q` flag from the GitHub Action to the `tox` environment. This way, it is in place when we run linkcheck through `tox` locally. The new setup makes it so that only errors and warnings show up in the output of doing `tox -e linkcheck`.
- I updated the documentation guide to mention `tox -e linkcheck`.

Revise testing environment for performing linkchecks of documentation builds

---

.pre-commit-config.yaml

@pheuer and @JaydenR2305 recently ran into a problem in #2245 where pre-commit complained that it couldn't find the Ruby executable which was needed by a particular pre-commit hook.  I happened across https://github.com/pre-commit/pre-commit/issues/1930 that says that we can bypass this problem by specifying the version of Ruby that pre-commit should use.  Non-intuitive but helpful to know!

Specify a version for Ruby in pre-commit configuration

---

.pre-commit-config.yaml
plasmapy/particles/decorators.py

While we mostly switched over to the `ruff` formatter, we still use `black` via `blacken-docs` to autoformat code in documentation.  There was a breaking change in the most recent release, so this PR specifies the version of `black` used by `blacken-docs`.

Specify version of `black` in `pre-commit` hook for `blacken-docs` 

---

docs/conf.py
pyproject.toml

After switching our documentation build over to Python 3.12 in #2368, I found in the weekly tests that we need to declare `setuptools` as a dependency for Python 3.12+ so that we can use `pkg_resources` in `docs/conf.py`.  I'm adding this dependency for the time being, though later on we want to stop using `pkg_resources` (#1620).

Add setuptools as documentation build dependency for Python 3.12+

---

CITATION.cff

A quick PR to alphabetize the author list in `CITATION.cff` following the `v2024.2.0` release. This'll make it easier in the next release when adding new contributors to the author list on the Zenodo record.

Alphabetize authors in `CITATION.cff`

---

changelog/2505.doc.rst
plasmapy/particles/decorators.py

Prior to #2504, optional arguments to functions decorated with `@particle_input` had annotations like `typing.Optional[ParticleLike]`. Since PlasmaPy is now Python 3.10+, we can instead use annotations like `ParticleLike | None` or `ParticleListLike | None`. This PR updates the docstring of `@particle_input` to reflect that.
Follows up on #2501, #2502, #2504.

Update `@particle_input` docstring to use type union syntax instead of `Optional`

---

CITATION.cff
plasmapy/formulary/lengths.py

This pull request fixes a small typo in the non-relativistic gyroradius formula.

Fix typo in gyroradius formula

---

changelog/2519.trivial.rst
plasmapy/plasma/grids.py
plasmapy/simulation/particle_tracker.py

Addresses issue #2514 by adding a keyword `warn_on_replace_with_zeros` to `AbstractGrid.require_quantites`, then calling `require_quantities` twice in particle_tracker. The first time, for the E&B fields, the warnings are silenced, while the second time, for any other required quantities, they are not.

Silence some require_quantities warnings in particle_tracker

---

docs/formulary/radiation.rst

Rather than adding our own function for blackbody radiation, this PR will point users to Astropy's.

Add a "See Also" to the `formulary.radiation` docs on `astropy.modeling.BlackBody`

---

.github/scripts/authors_in_cff.py
CITATION.cff

This PR does some refactoring of the script that checks whether each author of a pull request is included in `CITATION.cff`.  
This PR also fixes an error in the link to edit `CITATION.cff`.  The link had previously pointed to the `PlasmaPy/PlasmaPy` repo instead of the fork.  It does still assume that the fork is named "PlasmaPy" which will be true most of the time but possibly not all.

Refactor script for checking `CITATION.cff`

---

changelog/2526.trivial.rst
tox.ini

For a while we've had a test environment for conda with Python 3.10.  However, we haven't used it in CI for quite a while.  It's also one more place where we have to specify requirements.  Since we're not using it, it also has the potential to become outdated.  This PR removes this unused environment.

Drop the `py310-conda` tox environment

---

plasmapy/analysis/time_series/excess_statistics.py
plasmapy/analysis/time_series/running_moments.py
plasmapy/dispersion/analytical/stix_.py
plasmapy/formulary/radiation.py
plasmapy/particles/ionization_state.py
plasmapy/particles/ionization_state_collection.py
plasmapy/utils/calculator/widget_helpers.py

- I added `>>> import astropy.units as u` to the Examples sections of several docstrings
- I changed some docstring section titles from `Example` to `Examples` to be consistent with the numpydoc docstring standard.

Minor updates of docstrings

---

changelog/2542.internal.rst
plasmapy/formulary/lengths.py

This pull request refactors `plasmapy.formulary.lengths.gyroradius`  to reduce the complexity of the function. 
The reduction of complexity is mainly achieved by broadcasting all inputs to the appropriate output shape right at the start of the function which allows to eliminate a significant number of special cases and simplifies the control flow. Several guard clauses are added to catch problematic input early. 
It also stops the "UserWarning: lorentzfactor is given along with Vperp or T, will lead to inaccurate predictions unless they correspond" warning being emitted whenever 'lorenzfactor' is given, regardless weather 'Vperp' or 'T' are actually given or not.
Currently `plasmapy.formulary.lengths.gyroradius` has a complex control flow and several nested conditionals making it hard to …

Refactor gyroradius to reduce cognitive complexity

---

changelog/2543.internal.rst
changelog/2543.trivial.rst
mypy.ini
plasmapy/formulary/collisions/dimensionless.py
plasmapy/formulary/collisions/frequencies.py
plasmapy/formulary/collisions/lengths.py
plasmapy/formulary/collisions/misc.py
plasmapy/formulary/densities.py
plasmapy/formulary/dielectric.py
plasmapy/formulary/dimensionless.py
plasmapy/formulary/frequencies.py
plasmapy/formulary/lengths.py
plasmapy/formulary/misc.py
plasmapy/formulary/quantum.py
plasmapy/formulary/radiation.py
plasmapy/formulary/relativity.py
plasmapy/formulary/speeds.py
plasmapy/formulary/tests/test_densities.py
plasmapy/formulary/tests/test_dimensionless.py
plasmapy/formulary/tests/test_speeds.py
plasmapy/formulary/tests/test_thermal_speed.py

This PR adds and updates a bunch of type hint annotations in `plasmapy.formulary`. It also makes a few minor refactoring changes.
A limiting factor in doing this is that `@validate_quantities` is currently largely unannotated (#2435), but is being used to decorate a whole bunch of different functions. However, I'm going to leave that for another day (or more likely, another month).

Update type hints and docstrings in `plasmapy.formulary`

---

.github/content/release-checklist.md

This PR is to include updates to the release checklist for the `v2024.5.0` release.  It follows up on #2469.
So far, this PR adds a checklist item about updating requirements in the conda-forge feedstock, which doesn't seem to be done automatically.  We might want to automate this.

Update release checklist

---

tox.ini

This PR follows the advice in this blog post on [turbocharging tox](https://hynek.me/articles/turbo-charge-tox/).
> ```toml
> [testenv]
> package = wheel
> wheel_build_env = .pkg
> ```
>
> The first line tells tox to build and install wheels instead of source distributions, and the second line tells it to share the same build environment – and thus wheel – across all tox environments.

Create universal wheel in tox environments

---

.github/workflows/tests.yml
.github/workflows/weekly-tests.yml
changelog/2552.internal.rst
tox.ini

Continuous integration tests are most beneficial when they provide rapid 🚀 feedback. One of the time sinks in tests has been that `tox` has had to recreate Python environments every time tests are run.  
This PR enables caching for our test suite and documentation build via GitHub Actions. **Caching speeds up our Python 3.12 tests in CI (which skip slow tests but include doctests) from ∼3.5 min to ≲ 1 min!** We save the ∼2.5 minutes by not having to always recreate Python environments.
I renamed tox environments to make them easier to keep track of (at least for me). In particular, I reduced the extent to which `tox.ini` makes use of [generative environments](https://tox.wiki/en/4.13.0/user_guide.html#generative-environments) when specifying the commands for pytest to run. This is less …

Speed up tests by caching `.tox` in GitHub Actions and update tox environments

---

.github/workflows/update-pinned-reqs.yml

I recently updated the GitHub Action and tox environment to regenerate requirements files. However, for some reason I dropped the tox installation step, which broke the workflow. This PR adds this step back.

Fix GitHub Action to regenerate requirements

---

changelog/2558.internal.rst
setup.py

Since PlasmaPy has `pyproject.toml`, our `setup.py` file is no longer necessary. In particular, the `setup.py` configuration [is now considered legacy](https://pip.pypa.io/en/stable/reference/build-system/setup-py/). This PR removes `setup.py`.
We had previously kept a simple `setup.py` around because `pip install -e` had only recently been implemented for projects without `setup.py`.
Cross-references: #1680, #1758

Remove `setup.py`

---

CITATION.cff
changelog/2560.doc.rst
plasmapy/formulary/lengths.py

There was an unfinished sentence in the gyroradius description, warning about ``Vperp`` or ``T`` in the relativistic case.  I simply finished the sentence, which presumably was warning users to use the Lorentz factor.  
More complete documentation!

Fix sentence in gyroradius documentation

---

changelog/2559.breaking.rst
plasmapy/particles/atomic.py
plasmapy/particles/tests/test_atomic.py
plasmapy/particles/tests/test_particle_class.py

Whilst working on #2458, I noticed that a few of the functions in `plasmapy.particles.atomic` each returned a `list` containing `Particle` objects.  This PR changes it so that they return a `ParticleList`.

Make `common_isotopes`, `known_isotopes`, and `stable_isotopes` each return a `ParticleList`

---

.pre-commit-config.yaml
changelog/2561.internal.rst
changelog/README.rst
docs/plasma/index.rst
licenses/sphinx_license.rst

This PR adds [sphinx-lint](https://github.com/sphinx-contrib/sphinx-lint) as a pre-commit hook.

Add `sphinx-lint` to pre-commit configuration

---

.github/workflows/tests.yml
tox.ini

This PR switches to using `cffconvert --validate` to using the [cff-validator](https://github.com/marketplace/actions/cff-validator) GitHub Action, as brought up in https://github.com/spacepy/spacepy/issues/736.  As a plus, we get to drop the `linters` environment in `tox.ini`!

Switch to a GitHub Action for validating CITATION.cff

---

changelog/2588.doc.rst
plasmapy/formulary/densities.py

Fix typo in docs

---

plasmapy/analysis/tests/test_fit_functions.py
plasmapy/plasma/grids.py
plasmapy/plasma/plasma_base.py
plasmapy/utils/decorators/checks.py
pyproject.toml

This PR adds a few rules in ruff's [`RUF`](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf) rule set that have been taken out of ruff's nursery and thus are ready to be used in production.

Add some new ruff rules

---

CITATION.cff
plasmapy/particles/atomic.py
plasmapy/particles/symbols.py

Moved the `mass_numb` and `Z` to the Other Parameters section in `plasmapy.particles.atomic` and `plasmapy.particles.symbols`.

Moved charge/mass number to Other Parameters

---

.github/workflows/weekly-tests.yml

The code coverage reports have been acting a little weird lately.  In #2598, for example, the BASE commit is from two months ago (with the nearest commits being #2477, #2478, & #2481).  This PR is an attempt to get coverage reports uploaded from `main`.  
Even if this PR does work, it's more of a patch 🩹 rather than a complete fix.  It might be helpful to set it up so that the coverage test gets run every time a pull request is merged.
It may also be that we have code coverage set up incorrectly, or that the github token expired or something.

Include coverage in a weekly test

---

.github/workflows/tests.yml
.github/workflows/weekly-tests.yml

I forgot this step in #2615.  Following [these instructions](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions).  
Again, I need to merge it to see if it works (sigh).

Include `CODECOV_TOKEN` in the GitHub workflows that it is used in

---

.github/workflows/tests.yml
.github/workflows/weekly-tests.yml
codecov.yml

This PR does some clean-up of the Codecov configuration file in `codecov.yml`, as well as how the Codecov action gets used in CI and in weekly tests.
This PR sets `fail_ci_if_error` to `true`, which will help us notice a lot sooner when our Codecov configuration breaks. 
I recently noticed that we had not been uploading coverage reports from `main` to Codecov for approximately two months. Coverage reports from forks were still getting uploaded correctly (since they can be done tokenlessly), which meant that we hadn't noticed it for a while.  However, the coverage reports from pull requests were being compared against a commit to `main` from two months ago (around the time of #2478).  I recently fixed this problem by setting `CODECOV_TOKEN` as a GitHub secret, and wanted to follow up with …

Update Codecov settings and usage

---

codecov.yml

This PR is an attempt to fix our Codecov configuration which I fixed after it broke, and then broke after I had fixed it.  I suspect taking the token out of the configuration file is what broke it.  
This PR is also an attempt to see if I can include emojis in branch names.  Apparently, yes! Unicode FTW!
This follows up on #2612, #2613, #2615, #2616, and #2617.

Put token for Codecov back in configuration file

---

changelog/2623.bugfix.rst
plasmapy/diagnostics/thomson.py

Addresses #2620 without capping the version of `lmfit`
Supercedes #2621 
Instead of passing `settings` to `Model` and relying on `lmfit` to pass that to `_spectral_density_model`, this PR uses a lambda function to freeze in the settings (which are constant) prior to giving the function to `lmfit`.
```python
def _spectral_density_model_lambda(wavelengths, **params):
return _spectral_density_model(wavelengths, settings=settings, **params)
return Model(
_spectral_density_model_lambda,
independent_vars=["wavelengths"],
nan_policy="omit",
)
```

Modify the way settings are passed to the _spectral_density_model function 

---

changelog/2618.doc.rst
plasmapy/formulary/radiation.py

I've added a few examples to the docstring of `thermal_bremsstrahlung`.
Fixes #2529

Add examples to `thermal_bremsstrahlung` docstring

---

changelog/2627.bugfix.rst
plasmapy/formulary/radiation.py

Fixes #2619 
A `ValueError` was raised when supplying `~formulary.radiation.thermal_bremsstrahlung` multiple density values.  
This issue occurred because `if np.min(ω) < ω_pe:` is ambiguous in comparisons if `ω_pe` is an array.  The fix changes this to use the maximum electron plasma frequency, and raises the `PhysicsError` if any input frequencies are less than this.
(As a sidenote, is this the correct intended functionality?  Or would it be better to return the f-f emission for array values where it is valid?)
#2619

Fix bug when giving `thermal_bremsstrahlung multiple` density values

---

changelog/2636.feature.rst
src/plasmapy/diagnostics/thomson.py
tests/diagnostics/test_thomson.py

This PR makes updates to the OTS fitting module to address the following changes listed in #2591: 
Requested new features
- Allow ion_z and ion_mass to be parameters that can be fit.
- Add constant background parameter 
Changes made in this PR
- Added a new `background` parameter that is added as a constant offset to the normalized Skw to represent noise floor. 
- Changed the way the notch keyword in the lite function is applied to fix a bug. 
- Changed _model function to look for `ion_mu` and `ion_z` in params instead of settings. 
- Changed Model creation function to create fixed parameters for any `ion_mu` or `ion_z` parameters not set explicitly.  Remove old `ions` validation that doesn't apply anymore. 
- Refactored tests to get rid of support changes, get rid of some warnings. 
- …

Several improvements to OTS fitting

---

pyproject.toml
requirements.txt
requirements/requirements_docs_py312.txt

In #2497, we described an error that was occurring in the dev version of Sphinx, so we preemptively pinned `sphinx == 7.2.6`.  There were a few Sphinx 7.3.* releases in the last week or two, so this PR removes the strict requirement.  And the documentation build is passing, so yay! 🎆

Remove upper limit on Sphinx

---

.github/labeler.yml
codecov.yml
docs/contributing/testing_guide.rst

We've been having some problems with our Codecov configuration the last few months.  This PR makes it so that CI can pass if the Codecov report doesn't upload correctly.  I've correspondingly set it so that the codecov/patch check is now required, so it's more apparent if it is missing.  This is a bandaid 🩹 which we'll have to look into further.

Update Codecov settings

---

.github/workflows/ci.yml
.github/workflows/linkcheck.yml
.github/workflows/tests.yml
MANIFEST.in
changelog/2656.internal.rst
docs/_global_substitutions.py
docs/about/citation.rst
docs/conf.py
docs/contributing/doc_guide.rst
docs/contributing/getting_ready.rst
noxfile.py
src/plasmapy/__init__.py

This PR switches some GitHub workflows from being run with tox to being run with nox, including:
- Documentation
- mypy
- linkcheck
Presently, our tox configuration file is difficult to understand and maintain. Using nox lets us have a configuration file that is written in Python.
This PR is a follow-up on #2654. See also #1734 & #1735.

Use nox for some testing environments in GitHub workflows

---

changelog/2670.doc.rst
docs/contributing/coding_guide.rst

This PR updates the section of the coding guide that describes support for older versions of Python and for dependencies of PlasmaPy.  It now also discusses [SPEC 0](https://scientific-python.org/specs/spec-0000/) which is an analog of [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). 
I also added a little more discussion about testing against PlasmaPy.

Update the dependency version support policy in the coding guide

---

changelog/2682.internal.rst
noxfile.py

This PR adds three quick nox sessions:
- `import`, which installs PlasmaPy and then attempts to run `import plasmapy`
- `cff`, which validates `CITATION.cff`
- `build`, which builds a source distribution (sdist) and wheel, and then uses twine to validate them.
📝 The `import` session is based off of an existing tox environment, while the `cff` and `build` are coming from commands in GitHub workflows.
✨ Setting these up in `noxfile.py` probably took me perhaps ∼30–50% of the time it would have taken me to set these up in `tox.ini`, largely because I would have had to go back to the tox docs to look up how to do this.  
While tox is an incredible tool, I never want to edit a `tox.ini` file ever again!  😹

Add `import`, `cff`, and `build` sessions for nox

---

.pre-commit-search-and-replace.yaml
CHANGELOG.rst
changelog/2664.internal.rst
changelog/2681.internal.rst
changelog/2682.internal.rst
docs/_global_substitutions.py
docs/changelog/2024.5.0.rst
docs/contributing/doc_guide.rst
docs/contributing/testing_guide.rst

It turns out that Nox is capitalized except when used as a command.  I started making this change in #2685, but decided to put it in its own PR to isolate it in code review.

Apply search-and-replace for `|nox|` to `|Nox|` as a reStructuredText substitution

---

.readthedocs.yml
ci_requirements/all-3.12.txt
ci_requirements/docs-3.12.txt
ci_requirements/tests-3.10-lowest-direct.txt
ci_requirements/tests-3.10.txt
ci_requirements/tests-3.11-lowest-direct.txt
ci_requirements/tests-3.11.txt
ci_requirements/tests-3.12-lowest-direct.txt
ci_requirements/tests-3.12.txt
noxfile.py

I recently accidentally removed the code that regenerated the `docs` and `all` requirements files in the `requirements session of `noxfile.py`.  This PR adds them back, and regenerates the requirements files.  
This PR also makes it so that Read the Docs builds the docs using the requirements file generated by doing `nox -s requirements`.

Fix error in nox session for regenerating requirements files and update requirements file used by Read the Docs

---

.github/workflows/label-pr.yml

Quick follow-up of #2690, to fix when the labeler action is run.
(I started the title of this PR with "Minor" to test some changes to the workflow to add the "no changelog entry needed" label.)

Minor fix of labeler action

---

.github/workflows/ci.yml
MANIFEST.in
changelog/2695.internal.rst
noxfile.py
pyproject.toml

- I added a `lint` session for Nox as a shortcut to run `pre-commit run --all-files`.  This is mostly syntactic sugar, but does remove the need to install `pre-commit` manually.
- I added the `manifest` session for Nox to run `check-manifest`, which checks that all appropriate files are included in `MANIFEST.in`.  
- I added a configuration for `check-manifest` in `pyproject.toml`
- I updated `MANIFEST.in` accordingly

Add Nox sessions for running pre-commit and checking `MANIFEST.in`

---

CHANGELOG.rst
changelog/2664.internal.rst
changelog/2685.internal.rst
changelog/2693.feature.1.rst
changelog/2693.feature.2.rst
changelog/2694.internal.2.rst
changelog/2694.internal.3.rst
changelog/2694.internal.4.rst
changelog/2704.trivial.rst
ci_requirements/all-3.12.txt
ci_requirements/docs-3.12.txt
ci_requirements/tests-3.10-lowest-direct.txt
ci_requirements/tests-3.10.txt
ci_requirements/tests-3.11.txt
ci_requirements/tests-3.12.txt
docs/_global_substitutions.py
docs/changelog/0.7.0.rst
docs/changelog/0.8.1.rst
docs/changelog/0.9.0.rst
docs/changelog/0.9.1.rst
docs/changelog/2023.1.0.rst
docs/changelog/2023.10.0.rst
docs/changelog/2023.5.0.rst
docs/changelog/2024.2.0.rst
docs/changelog/2024.5.0.rst
docs/contributing/testing_guide.rst
pyproject.toml

We recently completed our switch from tox → Nox as our test runner. This is a quick follow-up PR to drop usage of the `|tox|` global substitution (mostly in the changelog) since we no longer need to refer to it, and to drop `tox` and `tox-uv` from the requirements. While I was at it, I also did some minor justifying of text in changelog files (since it sometimes gets formatted awkwardly).

Drop `|tox|` global substitution and adjust changelog formatting

---

changelog/2738.doc.rst
src/plasmapy/diagnostics/langmuir.py
src/plasmapy/diagnostics/thomson.py
src/plasmapy/plasma/grids.py

This PR makes some minor updates to docstrings in `plasmapy.dispersion`.
Changes include:
- Using unicode characters instead of LaTeX symbols (which makes docstrings more readable when using `help()`)
- Removing extra brackets in equations (which makes it easier to keep track of brackets)
- Justifying docstring text

Update docstrings in `plasmapy.diagnostics`

---

changelog/2736.doc.rst
src/plasmapy/formulary/braginskii.py
src/plasmapy/formulary/collisions/coulomb.py
src/plasmapy/formulary/collisions/frequencies.py
src/plasmapy/formulary/collisions/helio/collisional_analysis.py
src/plasmapy/formulary/collisions/lengths.py

This PR makes some minor updates to docstrings in `plasmapy.formulary.collisions`.
Changes include:
- Using unicode characters instead of LaTeX symbols (which makes docstrings more readable when using `help()`)
- Removing extra brackets in equations (which makes it easier to keep track of brackets)
- Justifying docstring text

Update docstrings in `plasmapy.formulary.collisions`

---

changelog/2734.internal.rst
mypy.ini
src/plasmapy/utils/_units_helpers.py
tests/utils/test_units_helpers.py

This PR adds type hint annotations to `plasmapy.utils._units_helpers`.

Add type hints to `plasmapy.utils._units_helpers`

---

changelog/2746.breaking.rst
src/plasmapy/simulation/particle_tracker/particle_tracker.py
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py
tests/simulation/test_particle_tracker.py

Implements `particle` as a required argument for the load particle method of the particle tracker.
Resolves #2725

Require `particle` for `ParticleTracker.load_particles`

---

.github/scripts/authors_in_cff.py
changelog/2750.internal.rst
noxfile.py

This PR makes some fairly minor updates to `noxfile.py`
- I made it so that the troubleshooting messages would only print out when running in CI (since they were starting to get annoying when running Nox in the terminal).
- I added emojis to make where to start in troubleshooting messages more apparent.  (In doing this, I learned that the Unicode modifier character `U+F0EF` causes some problems for the tests with lowest-direct dependencies, at least when run on Windows.)
- I updated the content of some troubleshooting messages.

Update Nox sessions including docstrings and troubleshooting messages

---

changelog/2735.doc.rst
src/plasmapy/dispersion/analytical/mhd_waves_.py
src/plasmapy/dispersion/analytical/stix_.py
src/plasmapy/dispersion/analytical/two_fluid_.py
src/plasmapy/dispersion/numerical/kinetic_alfven_.py

This PR makes some minor updates to docstrings in `plasmapy.dispersion`.
Changes include:
- Using unicode characters instead of LaTeX symbols (which makes docstrings more readable when using `help()`)
- Removing extra brackets in equations (which makes it easier to keep track of brackets)
- Justifying docstring text

Update docstrings for `plasmapy.dispersion` and `plasmapy.plasma.grids`

---

src/plasmapy/dispersion/analytical/mhd_waves_.py
src/plasmapy/dispersion/analytical/stix_.py
src/plasmapy/dispersion/analytical/two_fluid_.py
src/plasmapy/dispersion/numerical/hollweg_.py
src/plasmapy/dispersion/numerical/kinetic_alfven_.py
src/plasmapy/formulary/braginskii.py
src/plasmapy/formulary/collisions/coulomb.py
src/plasmapy/formulary/collisions/frequencies.py
src/plasmapy/formulary/collisions/lengths.py
src/plasmapy/particles/atomic.py
src/plasmapy/particles/particle_class.py
src/plasmapy/utils/decorators/checks.py
tests/formulary/test_transport.py
tests/particles/test_special_particles.py

This PR applies autofixes from ruff rule [PLR6201](https://docs.astral.sh/ruff/rules/literal-membership/), which makes it so that sets are used when testing for membership because:
> When testing for membership in a static sequence, prefer a set literal over a list or tuple, as Python optimizes set membership tests.
This particular ruff rule is in preview and not currently enabled in our ruff setup, but might be enabled at some point in the future so it's worth getting it out of the way now.
I'm also using this as a test PR to see if it gets any errors from the "Add no changelog label" workflow which was grumpy in #2755.  And, it's working here, so yay!

Apply autofixes from ruff rule PLR6201 

---

changelog/2715.bugfix.rst
src/plasmapy/dispersion/analytical/mhd_waves_.py

This PR adds an if statement to prevent array shape mismatch due to `np.squeeze` in `mhd_waves_.py`.
`np.squeeze` will convert column vectors to row vectors, for example, which causes problems where the array shape is assumed to be preserved.

Prevent array shape mismatch due to NumPy squeeze in `mhd_waves_.py`

---

changelog/2775.doc.rst
docs/conf.py

We've been getting incorrect versions in our documentation builds. Sometimes it's starts with `2023.1.0dev...` (where it gets the version from the most recent git hash) and other times it starts with `0.1...`.  This PR changes it so that the version that appears in the documentation includes the current date and the git hash.
I haven't been able to figure out what the problem has been with the version, so this is probably best considered as a temporary quasi-fix.
Closes #2632.

Modify version in latest docs to be based on current date and git hash

---

src/plasmapy/simulation/particle_integrators.py
src/plasmapy/simulation/particle_tracker/particle_tracker.py
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py
tests/formulary/collisions/test_collisions_misc.py
tests/simulation/test_particle_tracker.py

For this PR, I ran `nox -s 'autotyping(safe)'` followed by `nox -s 'autotyping(aggressive)'` to automatically add type hint annotations ahead of the 2024.7.0 release.

Use `autotyping` to add type hint annotations

---

.pre-commit-config.yaml
src/plasmapy/diagnostics/thomson.py
tests/particles/test_factory.py

This PR bumps the version of ruff, and changes a few type comparisons from `==` and `!=` to `is` and `is not`.

Update version of ruff

---

.github/content/release-checklist.md
changelog/2784.internal.rst

This PR makes some corrections to the release checklist.  More specifically, it's not currently possible to make a PR from a tag, so the checklist is from the release branch to `main`.

Update the checklist for releases

---

pyproject.toml

Previously a bug on sphinx-doc's side caused builds to fail. This bug has been fixed in subsequent releases, meaning we can unpin sphinx.
Resolves #2764

Unpin sphinx

---

noxfile.py
pyproject.toml

Previously, we included a line in the Nox sessions to build documentation like:
```python
session.install("-r", docs_requirements, ".")
```
The problem is that this does not explicitly include the `docs` dependency set, which has the consequence of hiding errors resulting from inconsistencies between the requirements file and `docs` requirements set.
🔧 This PR makes it so that the installation step explicitly includes the `docs` dependency set via `.[docs]`. 
I'm also repinning `sphinx==7.3.7` (sigh!) since the problem with the `docs` Nox session masked the warnings that we were trying to fix (see also #2762 and #2764).

Fix problem with installation step in Nox sessions to build documentation

---

.github/workflows/comment-on-pr.yml

GitHub allows `[!TIP]` admonitions, but unlike in reStructuredText, not `[!HINT]` admonitions.  This PR changes a `[!HINT]` to a `[!TIP]`.

Fix welcome message

---

tests/dispersion/analytical/test_mhd_wave_class.py

There was a change to the namespace in `astropy.units` so that `astropy.units.core.UnitTypeError` no longer exists (https://github.com/astropy/astropy/pull/16868). 
Based on the discussion in that issue, it sounds better to import something directly from `astropy.units` rather than the specific modules (i.e., use `u.UnitTypeError` vs `astropy.units.core.UnitTypeError`). Fortunately, this pattern is what we usually do anyway. 
Note: there's still another error in the development version of `astropy.units` that this PR doesn't fix.

Fix minor test failure from change to `astropy.units` namespace

---

changelog/2857.internal.rst
docs/conf.py

As per <https://about.readthedocs.com/blog/2024/07/addons-by-default/>,
RTD is currently simplifying their pipeline - they're removing "hidden"
manipulations of the `conf.py` context.
I've been getting emails about needing to add this snippet to preserve
current behavior, so there you go :)

Adjust sphinx config for RTD default changes

---

changelog/2868.feature.1.rst
changelog/2868.feature.2.rst
changelog/2868.feature.rst
src/plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
src/plasmapy/simulation/particle_tracker/save_routines.py
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py
tests/simulation/test_save_routines.py

A couple updates to how Tracker and the CPR module deal with saving, to make it a bit more convenient: 
1) `Tracker` save routines now take an optional `output_name` keyword that provides a basename for the save files. This is useful if you want your output files to have names based on context, or if you're saving multiple files. 
2) `synthetic_radiograph` now also works if you give it a path to an HDF5 file of Tracker output, which is now the default output format for Tracker.

Update saving for CPR synthetic radiography

---

changelog/2871.breaking.rst
changelog/2871.internal.rst
docs/notebooks/plasma/grids_cartesian.ipynb
src/plasmapy/plasma/grids.py
src/plasmapy/simulation/particle_tracker/particle_tracker.py
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py

Closes #2870
Technically a breaking change since `recognized_quantities` is now a callable and needs that syntax to access, but really this is only used internally.

Changed recognized_quantities from class property to property (Closes #2870)

---

tests/utils/decorators/test_checks.py

We've been getting a test failure for astropy-dev, and this PR updates the `assert` statement to include an error message to give more information about the failure.

Add error message in `test_checks.py`

---

pyproject.toml
src/plasmapy/__init__.py

We've been getting an occasional test collection error in `tools/export_ionization_energy.py`. However, we don't have any tests in `tools/` that we should run, so this PR makes pytest skip looking for tests in the `tools/` directory.

Make pytest ignore the `tools` directory

---

README.md

While GitHub has new syntax for admonitions, other sites do not (yet) recognize it.  Hence, I'm removing it here for the `README.md` file. The weird formatting can (or could) be seen on [PlasmaPy's PyPI page](https://pypi.org/project/plasmapy).  
The top-level `README.md` is the primary Markdown file that shows up on different sites, so it should be no problem to use it in other places.

Remove GitHub-style admonition that does not get recognized on PyPI page

---

ci_requirements/all-3.13-linux.txt
ci_requirements/all-3.13-macos.txt
ci_requirements/all-3.13-windows.txt
ci_requirements/docs-3.13-linux.txt
ci_requirements/docs-3.13-macos.txt
ci_requirements/docs-3.13-windows.txt
ci_requirements/tests-3.11-linux.txt
ci_requirements/tests-3.11-macos.txt
ci_requirements/tests-3.11-windows.txt
ci_requirements/tests-3.12-linux.txt
ci_requirements/tests-3.12-macos.txt
ci_requirements/tests-3.12-windows.txt
ci_requirements/tests-3.13-linux.txt
ci_requirements/tests-3.13-macos.txt
ci_requirements/tests-3.13-windows.txt
noxfile.py
pyproject.toml

#2933 added a strict requirements for `pygments == 2.18.0` because a change in how `pygments` handled whitespace broke `sphinx-codeautolink` (https://github.com/felix-hilden/sphinx-codeautolink/issues/152).  
We can merge this once a new version of `sphinx-codeautolink` is released.  We might need to run `nox -s requirements` if other requirements have been updated in the meantime.
`sphinx-codeautolink` is the awesome Sphinx extension that adds links to objects in code blocks in the documentation (like in [this section](https://docs.plasmapy.org/en/stable/contributing/coding_guide.html#validating-quantities)).

Unpin `pygments` and `sphinx-codeautolink` requirements

---

.pre-commit-config.yaml
pyproject.toml
src/plasmapy/particles/ionization_state.py

This PR enables a few more of the [`RUF`](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf) rule set for ruff that have come out of preview and are now suitable for production. The changes are pretty straightforward.

Enable new ruff rules

---

.github/workflows/ci.yml
.github/workflows/weekly.yml
CODEOWNERS
MANIFEST.in
noxfile.py
pyproject.toml

This PR is a direct follow-up to #2937, which switched us from using requirements files in `ci_requirements` to `uv.lock` to pin requirements for use by Nox and in CI.  
- I updated the cache key in our GitHub workflow so that the cache gets invalidated when `uv.lock` changes.
- Now `.venv` gets cached along with `.nox`. 
- Switch `ci_requirements` → `uv.lock` in `CODEOWNERS` so that I get assigned to PRs where it changes
- Updated some comments.
I still need to:

Update caching and cache invalidation in CI

---

.github/workflows/ci.yml
.github/workflows/weekly.yml

Our documentation builds depend on Graphviz (used by `sphinx.ext.graphviz`) and pandoc (for working with Jupyter notebooks, I believe).  This PR adopts a separate action to install Graphviz, and makes a few minor updates to the pandoc installation.  The pandoc installation step only works on Ubuntu at the moment.

Update GitHub workflows for CI

---

changelog/2961.internal.rst
noxfile.py

This PR adds the capability for `nox` to be run with commands like `python noxfile.py -s session_name` or `uv run noxfile.py -s session_name` by specifying dependency information within `noxfile.py`.  
For more details, see the [Nox docs](https://nox.thea.codes/en/stable/tutorial.html#running-without-the-nox-command-or-adding-dependencies) and [PEP 723](https://peps.python.org/pep-0723/).

Enable Nox to be run as a script

---

noxfile.py

This PR is a quick follow-up to #2964, since it failed when I tried to run the requirements workflow.

Improve handling of unexpected lines of `uv lock` output in Nox session to update requirements

---

changelog/2968.feature.rst
src/plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py

The SyntheticRadiography module tracks particles (usually randomly generated by the `create_particles` method) through a grid onto a detector plane (defined by two perpendicular vectors and a center point). The initial particle velocities are distributed around the source-detector axis.
In the current version, these vectors are set up automatically in a reasonable way (e.g. assuming the detector is looking at the origin, particles go along the source-detector axis). However, experimental setups are sometimes non-ideal, and in those cases the user might want direct control over the orientation of the detector and the initial velocity vector. 
This PR just adds a couple keywords to explicitly set the detector_vdir (a keyword already existed for detector_hdir) and the vector around which the …

Add optional keywords to SyntheticRadiograph to directly control detector orientation & source particle orientation

---

README.md

We recently consolidated our project and community meetings to be on Thursdays at 2 pm ET, so this change reflects that.  We'll be continuing office hours through the end of our current NSF award, which is coming up quite soon.

Update meeting times on `README.md`

---

.pre-commit-config.yaml
pyproject.toml
src/plasmapy/particles/ionization_state_collection.py

I noticed from an Astropy PR that ruff v0.11.0 came out a few days ago.  This PR runs `pre-commit autoupdate`, enables a few more rules in the `RUF` rule set, and applies changes with `pre-commit run --all-files`.  
I kept the old version of `pre-commit-search-and-replace`, and specified the exact version of `typos` (since exact versions like `1.30.2` are more secure than abbreviated versions like `v1`).

Update pre-commit configuration after new releases of `ruff`

---

.github/labeler.yml
changelog/2984.trivial.rst

This PR makes some updates to `.github/labeler.yml`, which is the file that specifies which labels get add for each file that gets added to a pull request.  I remembered that we needed to update this to include `uv.lock`, and then noticed that there were a few things that were out-of-date. In particular, we renamed a few GitHub workflows, and haven't had any files related to Azure pipelines or Appveyor for a long time.

Update the configuration for labeling pull requests

---

.gitignore
CODEOWNERS
MANIFEST.in
changelog/2997.internal.rst

This PR reorganizes `.gitignore` to put custom & PlasmaPy content is near the top, while having templates below.  I tried to minimally edit the templates so that it's easier to do a `git diff` later on to see what in the templates have changed.
Instead of ignoring `.idea` — the PyCharm settings folder — I put in the template from JetBrains. My hope is that we'll be able to set up certain test configurations that will be common across projects, so that it isn't necessary for everyone to set this up.  
> [!NOTE]
> I thought about including the .gitignore template specific to VS Code, but decided to keep ignoring the entirety of the configuration directory (`.vscode/`).  I plan to maintain the PyCharm configuration, but we would need someone to maintain the VS Code configuration.
I also made …

Organize `.gitignore` to use templates from GitHub

---

CITATION.cff
src/plasmapy/particles/particle_class.py

This small PR resolves the `datetime` deprecation warnings which you can find in the [CI logs](https://github.com/PlasmaPy/PlasmaPy/actions/runs/14848126109/job/41686437483#step:6:291):
```python
/Users/runner/work/PlasmaPy/PlasmaPy/src/plasmapy/particles/particle_class.py:173: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```
Please note that I added `noqa: UP017` because `datetime.UTC` alias (to `datetime.timezone.utc`) was introduced in Python 3.11, meaning previous versions will fail to use it.

Migrate to new datetime API

---

.gitignore

In #2997, I added a `.gitignore` template for the `.idea/` folder, which is where JetBrains products such as PyCharm store project configuration files.  This PR updates `.gitignore` to ignore the `.idea/` folder again. 
My motivation for #2997 included that it would be helpful to have common PyCharm settings for PlasmaPy development, such as shared test configurations so that PyCharm users don't need to recreate them independently.  The drawback is that these settings would need to be maintained, and we likely won't have the capacity to maintain these configurations after the conclusion of the current NSF award supporting PlasmaPy development.

Ignore `.idea` folder in `.gitignore` again

---

.github/workflows/weekly.yml
noxfile.py

The `weekly.yml` workflow had been failing since `nox` was trying to be run directly while it had not been explicitly installed.  This appears to have occurred when moving to `setup-uv` in PR #2959.
This was easily resolved by running the `nox` command with `uv run --with nox`.
After solving the above issue, I noticed the documentation tests (specifically for `sphinx`) were not working as intended.  Since `sphinx` had an upper dependency limit placed on it, the installer could not properly resolve dependencies with `plasmapy` and the latest `sphinx`.  To resolve this issue...
1. I created the `_get_dependencies_from_pyproject_toml()` helper function (in `noxfile.py`), so I could extract the package dependencies directly from the `pyproject.toml`.
2. I then removed the target package …

Repair the `weekly.yml` workflow

---

CONTRIBUTING.md
README.md
changelog/3013.doc.rst
docs/_global_substitutions.py
docs/contributing/getting_ready.rst
docs/contributing/index.rst
docs/contributing/workflow.rst
docs/index.rst

Because the NSF award supporting the development of PlasmaPy will be ending shortly, we will be putting office hours on an indefinite hiatus. Members of the broader community will continue to be able to stop by our [community meetings](https://www.plasmapy.org/meetings/weekly/) on most Thursdays at 2 pm ET.

Put office hours on an indefinite hiatus

---

docs/contributing/coding_guide.rst

This changes the coding guide to use reStructuredText literals instead of the `:command:` role since I prefer the formatting of literals.

Fix formatting in coding guide

---

src/plasmapy/plasma/equilibria1d.py

The documentation for [Harris Sheet](https://docs.plasmapy.org/en/stable/api/plasmapy.plasma.equilibria1d.HarrisSheet.html#plasmapy.plasma.equilibria1d.HarrisSheet) includes an equation that does not render correctly:
It appears a parenthesis is used to close the right curly bracket in the denominator of the first fraction. This pull changes the parenthesis to a curly bracket.

Fix Math Rendering in HarrisSheet Docs

---

.github/workflows/comment-on-pr.yml

This PR reverts a change made in #2975, which appears to have broken the workflow that posts a welcome comment in PRs (e.g., #3028).

Revert changes to the workflow that posts the welcome comment

---

changelog/3039.internal.rst
tests/diagnostics/charged_particle_radiography/test_synthetic_radiography.py

Closes #3026 
This PR should go a long way to reducing the CPR module test execution time. The following changes are made: 
1) test_multiple_grids and test_multiple_grids2 were literally just duplicate tests - I have deleted the second one. 
2) test_multiple_grids is just a "does it run" test: no actual validation, so it definitely didn't need 1E5 particles. I've dropped it down to just 100 particles, so that should run much faster. 
3) test_add_wire_mesh was a badly structured test that was actually running a BUNCH of simulations to test a variety of things. I've broken the input validation tests into two other parametrized tests. 
4) The remaining `test_add_wire_mesh_accuracy` is actually a pretty important test for the CPR module: it checks that a radiograph of a grid returns the …

Reduce CPR test time

---

.github/workflows/update-pinned-reqs.yml

We have a weekly cron job to update `uv.lock`, which locks the dependencies used in continuous integration tests.  This PR makes it so that this job is run on Thursdays a few hours ahead of the weekly PlasmaPy community meeting.  
> This must be Thursday. I never could get the hang of Thursdays.

Update pinned requirements on Thursdays instead of Mondays

---

changelog/3069.doc.rst
docs/CODE_OF_CONDUCT.rst

PlasmaPy has adopted the Contributor Covenant Code of Conduct for many years, and is currently at version 2.1 (#1324). This PR updates PlasmaPy's Code of Conduct to the Contributor Covenant version 3.0.  Notable changes include an enhanced enforcement ladder with elements of restorative justice including strategies for repairing harm.
See also: #9, https://github.com/PlasmaPy/PlasmaPy/commit/3570b3fffa5ff439dafb3b9d3cd4355d87410fb7

Update the code of conduct to the Contributor Covenant v3.0

---

pyproject.toml

This PR enables a few new rules for the `ruff` linter, including the [`FURB`](https://docs.astral.sh/ruff/rules/#refurb-furb) and [`Q`](https://en.wikipedia.org/wiki/Q_(Star_Trek)) rule sets.  Running `ruff check` with these new rules resulted in no violations, so no changes to the code base were necessary. 🎉🎂💖🎆🪩🌌🥦

Enable new rules for `ruff check`

---

.github/workflows/mint-release.yml

This PR makes a few quick follow-ups to #3081, #3083, & #3084.
The step to build the changelog is being skipped for prereleases because we only want to compile changes between full releases.

Fix changelog and pre-commit steps in workflow to mint a release
